In [1]:
import pandas as pd
import numpy as np
import seaborn as sns#It is used for data visualization and exploratory data analysis.
import matplotlib.pyplot as plt #pyplot is a collection of functions that make matplotlib work like MATLAB. Each pyplot function makes some change to a figure: e.g., creates a figure, creates a plotting area in a figure, plots some lines in a plotting area, decorates the plot with labels, etc. In matplotlib.
%matplotlib inline#It provides interactivity with the backend in the frontends like the jupyter notebook. It also provides the feature where, the plotting commands below the output cell of the previous plot, will not affect the previous plot, which means it separates different plots.

UsageError: unrecognized arguments: provides interactivity with the backend in the frontends like the jupyter notebook. It also provides the feature where, the plotting commands below the output cell of the previous plot, will not affect the previous plot, which means it separates different plots.

In [2]:
df = pd.read_csv(r'C:\Users\Narasimha Reddy\OneDrive\Desktop\sih\project.csv')

In [3]:
df

,Institute ID,Name,City,State,infra,placements,academic,Year,branch,gender,Rank
0,IR17-I-2-18243,Indian Institute of Science Bangalore,Bengaluru,Karnataka,83.33,1,52.74,2017,cse,coed,1
1,IR17-I-2-1-319,Jawaharlal Nehru University,New Delhi,Delhi,47.27,3,51.75,2017,cse,coed,2
2,IR17-I-2-18500,Banaras Hindu University,Varanasi,Uttar Pradesh,44.01,4,51.46,2017,cse,coed,3
3,IR17-I-2-30673,Jawaharlal Nehru Centre for Advanced Scientifi...,Bengaluru,Karnataka,6.92,55,51.36,2017,cse,coed,4
4,IR17-I-2-10326,Jadavpur University,Kolkata,West Bengal,28.81,9,51.20,2017,cse,coed,5
...,...,...,...,...,...,...,...,...,...,...,...
495,IR-O-U-0121,Goa University,Goa,Goa,20.01,115,38.96,2021,it,coed,96
496,IR-O-U-0043,"Vignan's Foundation for Science, Technology an...",Guntur,Andhra Pradesh,18.00,142,38.92,2021,it,coed,97
497,IR-O-U-0555,Graphic Era University,Dehradun,Uttarakhand,32.17,45,38.91,2021,ai,coed,98
498,IR-O-U-0223,Jain University,Bengluru,Karnataka,25.52,76,38.89,2021,cse,coed,99
499,IR-O-U-0564,University of Petroleum and Energy Studies,Dehradun,Uttarakhand,21.90,97,38.88,2021,ece,coed,100

In [4]:
df.describe()

            infra  placements    academic        Year        Rank
count  500.000000  500.000000  500.000000   500.00000  500.000000
mean    19.604140   70.248000   45.946420  2019.00000   50.500000
std     17.372008   54.832287    8.060343     1.41563   28.894979
min      0.000000    1.000000   32.990000  2017.00000    1.000000
25%      4.700000   27.000000   40.240000  2018.00000   25.750000
50%     16.585000   58.500000   44.065000  2019.00000   50.500000
75%     30.700000  100.000000   50.077500  2020.00000   75.250000
max    100.000000  243.000000   84.180000  2021.00000  100.000000

In [5]:
df.isnull().sum() #returns the number of missing values in the data set

Institute ID    0
Name            0
City            0
State           0
infra           0
placements      0
academic        0
Year            0
branch          0
gender          0
Rank            0
dtype: int64

In [6]:
len_I = df['Institute ID'].unique() #used to find the unique elements of an array

In [7]:
len(len_I)

324

In [8]:
list_N = df['Name'].unique()

In [9]:
len(list_N)

177

In [10]:
df.drop('Institute ID',axis=1,inplace=True) #The drop() method removes the specified row or column.

In [11]:
df.drop('City',axis=1,inplace=True)

In [12]:
df.drop('State',axis=1,inplace=True)

In [13]:
df.drop('branch',axis=1,inplace=True)

In [14]:
df.drop('gender',axis=1,inplace=True)

In [15]:
df

,Name,infra,placements,academic,Year,Rank
0,Indian Institute of Science Bangalore,83.33,1,52.74,2017,1
1,Jawaharlal Nehru University,47.27,3,51.75,2017,2
2,Banaras Hindu University,44.01,4,51.46,2017,3
3,Jawaharlal Nehru Centre for Advanced Scientifi...,6.92,55,51.36,2017,4
4,Jadavpur University,28.81,9,51.20,2017,5
...,...,...,...,...,...,...
495,Goa University,20.01,115,38.96,2021,96
496,"Vignan's Foundation for Science, Technology an...",18.00,142,38.92,2021,97
497,Graphic Era University,32.17,45,38.91,2021,98
498,Jain University,25.52,76,38.89,2021,99
499,University of Petroleum and Energy Studies,21.90,97,38.88,2021,100

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        500 non-null    object
 1   infra       500 non-null    float64
 2   placements  500 non-null    int64
 3   academic    500 non-null    float64
 4   Year        500 non-null    int64
 5   Rank        500 non-null    int64
dtypes: float64(2), int64(3), object(1)
memory usage: 23.6+ KB

In [17]:
df_2017 = df[df['Year']==2017]

In [18]:
df_2017

,Name,infra,placements,academic,Year,Rank
0,Indian Institute of Science Bangalore,83.33,1,52.74,2017,1
1,Jawaharlal Nehru University,47.27,3,51.75,2017,2
2,Banaras Hindu University,44.01,4,51.46,2017,3
3,Jawaharlal Nehru Centre for Advanced Scientifi...,6.92,55,51.36,2017,4
4,Jadavpur University,28.81,9,51.20,2017,5
...,...,...,...,...,...,...
95,Sri Krishnadevaraya University,0.04,205,33.76,2017,96
96,Alagappa University,4.17,77,33.66,2017,97
97,Narsee Monjee Institute of Management Studies ...,6.10,59,33.60,2017,98
98,Jawaharlal Nehru Technological University,4.32,76,33.44,2017,99
99,B.S. Abdur Rahman Institute of Science and Tec...,6.07,60,32.99,2017,100

In [19]:
df_2018 = df[df['Year']==2018]

In [20]:

df_2018

,Name,infra,placements,academic,Year,Rank
100,Indian Institute of Science Bangalore,100.00,1,82.16,2018,1
101,Jawaharlal Nehru University,46.28,3,67.57,2018,2
102,Banaras Hindu University,43.62,4,63.52,2018,3
103,Anna University,63.22,2,62.82,2018,4
104,University of Hyderabad,21.66,19,60.54,2018,5
...,...,...,...,...,...,...
195,The University of Burdwan,2.40,100,37.68,2018,96
196,D. Y. Patil Educational Society,0.00,203,37.61,2018,97
197,International Institute of Information Technology,8.87,45,37.52,2018,98
198,PES University,3.17,88,37.51,2018,99
199,Jaypee Institute of Information Technology,18.35,22,37.47,2018,100

In [21]:
df_2019 = df[df['Year']==2019]

In [22]:
df_2019

,Name,infra,placements,academic,Year,Rank
200,Indian Institute of Science Bangalore,100.00,1,82.28,2019,1
201,Jawaharlal Nehru University,55.27,3,68.68,2019,2
202,Banaras Hindu University,47.28,5,64.55,2019,3
203,University of Hyderabad,36.71,8,61.85,2019,4
204,Calcutta University,37.39,7,60.87,2019,5
...,...,...,...,...,...,...
295,Central University of Punjab,7.91,57,38.68,2019,96
296,Assam University-Silchar,4.70,83,38.67,2019,97
297,Kurukshetra University,8.25,55,38.60,2019,98
298,Rajiv Gandhi University,0.41,200,38.48,2019,99
299,Meenakshi Academy of Higher Education and Rese...,0.00,222,38.45,2019,100

In [23]:
df_2020 = df[df['Year']==2020]

In [24]:
df_2020

,Name,infra,placements,academic,Year,Rank
300,Indian Institute of Science Bangalore,100.00,1,84.18,2020,1
301,Jawaharlal Nehru University,67.24,3,70.16,2020,2
302,Banaras Hindu University,53.99,6,63.15,2020,3
303,Amrita Vishwa Vidyapeetham,44.33,13,62.27,2020,4
304,Jadavpur University,71.44,2,61.99,2020,5
...,...,...,...,...,...,...
395,Utkal University,39.00,20,40.05,2020,96
396,Graphic Era University,26.73,64,40.04,2020,97
397,Chettinad Academy of Research and Education,18.74,129,39.97,2020,98
398,Kurukshetra University,33.21,37,39.79,2020,99
399,"Vignan's Foundation for Science, Technology & ...",20.52,100,39.71,2020,100

In [25]:
df_2021 = df[df['Year']==2021]

In [26]:
df_2021

,Name,infra,placements,academic,Year,Rank
400,Indian Institute of Science Bangalore,100.00,1,82.67,2021,1
401,Jawaharlal Nehru University,67.88,2,67.99,2021,2
402,Banaras Hindu University,58.57,5,64.02,2021,3
403,Calcutta University,45.77,14,62.06,2021,4
404,Amrita Vishwa Vidyapeetham,48.36,10,61.23,2021,5
...,...,...,...,...,...,...
495,Goa University,20.01,115,38.96,2021,96
496,"Vignan's Foundation for Science, Technology an...",18.00,142,38.92,2021,97
497,Graphic Era University,32.17,45,38.91,2021,98
498,Jain University,25.52,76,38.89,2021,99
499,University of Petroleum and Energy Studies,21.90,97,38.88,2021,100

In [27]:
df_suffix = pd.merge(df_2017, df_2018, left_on='Name',right_on='Name',how='outer',suffixes=('_2017','_2018'))

df_suffix

,Name,infra_2017,placements_2017,academic_2017,Year_2017,Rank_2017,infra_2018,placements_2018,academic_2018,Year_2018,Rank_2018
0,Indian Institute of Science Bangalore,83.33,1.0,52.74,2017.0,1.0,100.00,1.0,82.16,2018.0,1.0
1,Jawaharlal Nehru University,47.27,3.0,51.75,2017.0,2.0,46.28,3.0,67.57,2018.0,2.0
2,Banaras Hindu University,44.01,4.0,51.46,2017.0,3.0,43.62,4.0,63.52,2018.0,3.0
3,Jawaharlal Nehru Centre for Advanced Scientifi...,6.92,55.0,51.36,2017.0,4.0,NaN,NaN,NaN,NaN,NaN
4,Jadavpur University,28.81,9.0,51.20,2017.0,5.0,35.50,6.0,59.68,2018.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...
127,Yenepoya,NaN,NaN,NaN,NaN,NaN,0.41,167.0,38.53,2018.0,92.0
128,Nagaland University,NaN,NaN,NaN,NaN,NaN,0.41,167.0,38.14,2018.0,95.0
129,The University of Burdwan,NaN,NaN,NaN,NaN,NaN,2.40,100.0,37.68,2018.0,96.0
130,D. Y. Patil Educational Society,NaN,NaN,NaN,NaN,NaN,0.00,203.0,37.61,2018.0,97.0
131,International Institute of Information Technology,NaN,NaN,NaN,NaN,NaN,8.87,45.0,37.52,2018.0,98.0

In [28]:
df_suffix.isna().sum()# returns the number of missing values in each column.

Name                0
infra_2017         32
placements_2017    32
academic_2017      32
Year_2017          32
Rank_2017          32
infra_2018         32
placements_2018    32
academic_2018      32
Year_2018          32
Rank_2018          32
dtype: int64

In [29]:
df_suffix['infra_2017'].describe()

count    100.000000
mean      10.840900
std       13.184734
min        0.020000
25%        2.715000
50%        5.960000
75%       14.450000
max       83.330000
Name: infra_2017, dtype: float64

In [30]:
df_suffix['placements_2017'].fillna(14.5,inplace=True)

In [31]:
df_suffix['academic_2017'].describe()

count    100.000000
mean      41.926300
std        8.007775
min       32.990000
25%       36.195000
50%       39.820000
75%       44.867500
max       83.280000
Name: academic_2017, dtype: float64

In [32]:
df_suffix['infra_2017'].describe()

count    100.000000
mean      10.840900
std       13.184734
min        0.020000
25%        2.715000
50%        5.960000
75%       14.450000
max       83.330000
Name: infra_2017, dtype: float64

In [33]:
df_data = pd.merge(df_2017, df_2018, on='Name',suffixes=('_2017','_2018'))

In [34]:
df_data

,Name,infra_2017,placements_2017,academic_2017,Year_2017,Rank_2017,infra_2018,placements_2018,academic_2018,Year_2018,Rank_2018
0,Indian Institute of Science Bangalore,83.33,1,52.74,2017,1,100.00,1,82.16,2018,1
1,Jawaharlal Nehru University,47.27,3,51.75,2017,2,46.28,3,67.57,2018,2
2,Banaras Hindu University,44.01,4,51.46,2017,3,43.62,4,63.52,2018,3
3,Jadavpur University,28.81,9,51.20,2017,5,35.50,6,59.68,2018,6
4,Anna University,43.94,5,48.90,2017,6,63.22,2,62.82,2018,4
...,...,...,...,...,...,...,...,...,...,...,...
63,Cochin University of Science and Technology,1.89,109,35.42,2017,86,18.88,20,40.53,2018,69
64,Bharathidasan University,8.03,48,35.14,2017,88,26.30,11,41.63,2018,67
65,Assam University-Silchar,5.65,64,34.38,2017,92,2.40,100,38.79,2018,87
66,PES University,13.75,29,33.94,2017,94,3.17,88,37.51,2018,99
67,Alagappa University,4.17,77,33.66,2017,97,24.50,15,48.25,2018,27

In [35]:
df_data_1920 = pd.merge(df_data,df_2019,on='Name',suffixes=('','_2019'))

In [36]:
df_data_1920

,Name,infra_2017,placements_2017,academic_2017,Year_2017,Rank_2017,infra_2018,placements_2018,academic_2018,Year_2018,Rank_2018,infra,placements,academic,Year,Rank
0,Indian Institute of Science Bangalore,83.33,1,52.74,2017,1,100.00,1,82.16,2018,1,100.00,1,82.28,2019,1
1,Jawaharlal Nehru University,47.27,3,51.75,2017,2,46.28,3,67.57,2018,2,55.27,3,68.68,2019,2
2,Banaras Hindu University,44.01,4,51.46,2017,3,43.62,4,63.52,2018,3,47.28,5,64.55,2019,3
3,Jadavpur University,28.81,9,51.20,2017,5,35.50,6,59.68,2018,6,51.83,4,60.53,2019,6
4,Anna University,43.94,5,48.90,2017,6,63.22,2,62.82,2018,4,62.72,2,60.35,2019,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,Periyar University,5.85,61,35.44,2017,85,4.30,71,38.58,2018,90,19.25,25,40.99,2019,68
60,Cochin University of Science and Technology,1.89,109,35.42,2017,86,18.88,20,40.53,2018,69,14.84,32,41.42,2019,65
61,Bharathidasan University,8.03,48,35.14,2017,88,26.30,11,41.63,2018,67,24.17,18,43.41,2019,60
62,Assam University-Silchar,5.65,64,34.38,2017,92,2.40,100,38.79,2018,87,4.70,83,38.67,2019,97
63,Alagappa University,4.17,77,33.66,2017,97,24.50,15,48.25,2018,27,26.65,17,48.54,2019,28

In [37]:
df_data_20 = pd.merge(df_data_1920,df_2020,on='Name',suffixes=('','_2020'))

In [38]:
df_data_20

,Name,infra_2017,placements_2017,academic_2017,Year_2017,Rank_2017,infra_2018,placements_2018,academic_2018,Year_2018,...,infra,placements,academic,Year,Rank,infra_2020,placements_2020,academic_2020,Year_2020,Rank_2020
0,Indian Institute of Science Bangalore,83.33,1,52.74,2017,1,100.00,1,82.16,2018,...,100.00,1,82.28,2019,1,100.00,1,84.18,2020,1
1,Jawaharlal Nehru University,47.27,3,51.75,2017,2,46.28,3,67.57,2018,...,55.27,3,68.68,2019,2,67.24,3,70.16,2020,2
2,Banaras Hindu University,44.01,4,51.46,2017,3,43.62,4,63.52,2018,...,47.28,5,64.55,2019,3,53.99,6,63.15,2020,3
3,Jadavpur University,28.81,9,51.20,2017,5,35.50,6,59.68,2018,...,51.83,4,60.53,2019,6,71.44,2,61.99,2020,5
4,Anna University,43.94,5,48.90,2017,6,63.22,2,62.82,2018,...,62.72,2,60.35,2019,7,65.89,4,58.71,2020,12
5,University of Hyderabad,27.06,11,48.84,2017,7,21.66,19,60.54,2018,...,36.71,8,61.85,2019,4,58.32,5,61.70,2020,6
6,University of Delhi,30.76,7,48.27,2017,8,33.15,8,58.69,2018,...,41.11,6,57.59,2019,13,53.44,7,60.10,2020,11
7,Amrita Vishwa Vidyapeetham,26.12,12,48.19,2017,9,31.44,9,58.46,2018,...,31.01,12,59.22,2019,8,44.33,13,62.27,2020,4
8,Savitribai Phule Pune University,11.20,35,46.72,2017,10,15.04,26,58.24,2018,...,16.55,28,58.40,2019,10,44.99,11,61.13,2020,9
9,Aligarh Muslim University,16.62,21,83.28,2017,11,26.30,11,57.78,2018,...,18.46,27,58.36,2019,11,38.99,23,54.30,2020,17
10,Jamia Millia Islamia,9.73,42,61.53,2017,12,11.76,33,56.18,2018,...,14.26,37,58.07,2019,12,31.60,41,61.07,2020,10
11,Vellore Institute of Technology,32.95,6,58.25,2017,14,36.71,5,52.68,2018,...,35.31,9,51.44,2019,19,49.00,8,55.22,2020,16
12,Calcutta University,17.15,20,56.50,2017,16,26.30,11,53.38,2018,...,37.39,7,60.87,2019,5,47.99,9,61.53,2020,7
13,Manipal Academy of Higher Education-Manipal,27.67,10,55.37,2017,18,26.30,11,57.37,2018,...,30.21,14,58.50,2019,9,43.95,15,61.51,2020,8
14,Visva Bharati,4.71,69,54.70,2017,19,5.03,67,47.62,2018,...,11.52,44,46.27,2019,37,19.30,121,46.84,2020,50
15,Homi Bhabha National Institute,8.70,47,46.45,2017,21,9.85,42,48.98,2018,...,4.33,87,51.95,2019,17,33.54,34,56.04,2020,14
16,Bharath Institute of Higher Education & Research,3.79,84,46.45,2017,22,2.40,100,50.74,2018,...,3.19,103,46.32,2019,36,21.87,89,45.67,2020,59
17,Osmania University,11.16,36,45.52,2017,23,5.76,59,48.02,2018,...,9.26,50,49.86,2019,26,39.00,20,51.15,2020,29
18,Institute of Chemical Technology,20.69,16,44.95,2017,25,15.90,25,51.39,2018,...,20.28,21,52.62,2019,15,44.07,14,54.10,2020,18
19,Jamia Hamdard,1.87,110,44.84,2017,26,2.01,115,50.31,2018,...,6.86,64,51.73,2019,18,23.16,83,52.60,2020,21
20,Gauhati University,2.48,102,44.42,2017,27,6.11,57,45.44,2018,...,9.59,49,45.57,2019,42,22.20,87,47.10,2020,47
21,Bharathiar University,9.11,45,44.29,2017,28,22.63,17,55.08,2018,...,31.20,11,57.23,2019,14,37.18,26,58.30,2020,13
22,Kerala University,0.89,132,43.95,2017,29,7.17,51,47.72,2018,...,8.59,51,51.21,2019,22,21.54,92,52.35,2020,23
23,Tezpur University,7.09,54,43.78,2017,30,10.82,37,48.00,2018,...,15.71,31,48.47,2019,29,34.88,30,48.77,2020,40
24,Panjab University,18.99,18,43.13,2017,33,23.58,16,50.94,2018,...,27.09,16,51.25,2019,21,42.39,16,51.85,2020,26
25,Pondicherry University,4.67,70,42.70,2017,37,14.76,28,42.36,2018,...,19.25,25,44.88,2019,48,28.88,58,45.82,2020,58
26,University of Madras,10.82,40,41.85,2017,41,26.52,10,51.52,2018,...,30.01,15,51.34,2019,20,38.30,24,52.55,2020,22
27,Sri Venkateswara University,1.94,108,41.48,2017,42,2.01,115,43.44,2018,...,6.51,66,44.88,2019,49,37.00,27,48.84,2020,38
28,Andhra University,20.72,15,41.38,2017,43,9.53,43,50.39,2018,...,14.55,34,52.11,2019,16,39.82,19,53.82,2020,19
29,Sathyabama Institute of Science and Technology,11.08,38,41.30,2017,44,4.30,71,44.34,2018,...,2.41,123,45.58,2019,41,19.47,114,48.77,2020,39
30,Dr. D. Y. Patil Vidyapeeth Pune,11.61,33,40.59,2017,47,1.22,134,43.15,2018,...,7.56,59,45.11,2019,46,33.54,34,47.92,2020,46
31,North Eastern Hill University,3.24,93,40.51,2017,48,5.03,67,42.34,2018,...,6.51,66,45.99,2019,39,23.48,81,46.88,2020,49
32,Kalinga Institute of Industrial Technology,20.95,14,40.47,2017,49,3.55,82,44.81,2018,...,14.55,34,47.97,2019,31,31.30,45,52.33,2020,24
33,AMITY University,18.06,19,39.17,2017,52,5.40,64,42.99,2018,...,7.22,61,43.53,2019,58,30.10,54,49.02,2020,37
34,Banasthali Vidyapith,7.46,52,38.74,2017,53,4.30,71,41.88,2018,...,4.33,87,43.22,2019,61,20.18,105,46.32,2020,55
35,Bharati Vidyapeeth,30.64,8,38.73,2017,54,14.76,28,41.71,2018,...,13.66,39,42.89,2019,62,39.00,20,44.84,2020,63
36,Saveetha Institute of Medical and Technical Sc...,5.81,62,38.68,2017,55,3.17,88,44.00,2018,...,0.00,222,45.42,2019,43,19.11,122,48.56,2020,42
37,Calicut University,4.74,68,38.45,2017,57,5.76,59,40.06,2018,...,7.22,61,42.22,2019,64,21.21,95,46.37,2020,54
38,Mizoram University,0.03,214,38.36,2017,58,0.81,146,39.36,2018,...,2.02,135,40.27,2019,76,20.52,100,43.49,2020,67
39,Kurukshetra University,2.33,106,38.26,2017,59,3.93,75,39.45,2018,...,8.25,55,38.60,2019,98,33.21,37,39.79,2020,99
40,Shiv Nadar University,5.24,66,37.95,2017,60,0.00,203,43.68,2018,...,6.15,70,44.45,2019,52,21.54,92,46.11,2020,56
41,Symbiosis International University,14.31,28,37.67,2017,61,6.11,57,44.62,2018,...,3.19,103,43.65,2019,56,31.82,40,48.35,2020,43
42,KLE Academy of Higher Education and Research,0.69,141,37.25,2017,62,2.79,96,42.76,2018,...,4.33,87,40.92,2019,69,28.20,60,43.10,2020,70
43,University of Jammu,0.59,157,37.23,2017,63,1.22,134,43.19,2018,...,2.02,135,40.43,2019,74,31.47,42,46.55,2020,52
44,Goa University-Goa,5.09,67,37.16,2017,64,2.01,115,40.66,2018,...,1.63,148,38.76,2019,94,19.82,107,41.37,2020,81
45,Kalyani University,0.02,223,36.84,2017,66,3.17,88,38.87,2018,...,4.70,83,38.85,2019,91,19.47,114,40.91,2020,89
46,Dayalbagh Educational Institute,15.65,22,36.36,2017,72,12.38,30,41.95,2018,...,11.83,43,40.24,2019,77,30.70,48,41.21,2020,82
47,University of Kashmir,0.10,184,36.32,2017,73,0.00,203,43.96,2018,...,1.63,148,44.19,2019,53,25.82,68,46.99,2020,48
48,Dibrugarh University,0.68,143,36.28,2017,74,2.79,96,39.13,2018,...,5.07,80,39.30,2019,86,22.20,87,41.05,2020,84
49,Guru Nanak Dev University,4.65,71,35.83,2017,80,7.17,51,42.36,2018,...,5.80,73,43.69,2019,55,35.48,29,46.58,2020,51
50,Guru Gobind Singh Indraprastha University,3.37,90,35.60,2017,82,2.40,100,40.05,2018,...,3.58,98,41.21,2019,66,4.53,229,40.24,2020,95
51,Sri Balaji Vidyapeeth Mahatma Gandhi Medical C...,4.34,74,35.50,2017,83,0.00,203,40.25,2018,...,0.00,222,40.87,2019,72,18.74,129,40.92,2020,88
52,NITTE University,3.95,79,35.50,2017,84,8.53,46,39.70,2018,...,6.51,66,40.88,2019,70,22.85,85,42.19,2020,74
53,Periyar University,5.85,61,35.44,2017,85,4.30,71,38.58,2018,...,19.25,25,40.99,2019,68,28.09,61,41.09,2020,83
54,Cochin University of Science and Technology,1.89,109,35.42,2017,86,18.88,20,40.53,2018,...,14.84,32,41.42,2019,65,29.39,56,45.02,2020,62
55,Bharathidasan University,8.03,48,35.14,2017,88,26.30,11,41.63,2018,...,24.17,18,43.41,2019,60,40.09,18,46.41,2020,53
56,Alagappa University,4.17,77,33.66,2017,97,24.50,15,48.25,2018,...,26.65,17,48.54,2019,28,44.76,12,49.22,2020,36

In [39]:
df_data_20

,Name,infra_2017,placements_2017,academic_2017,Year_2017,Rank_2017,infra_2018,placements_2018,academic_2018,Year_2018,...,infra,placements,academic,Year,Rank,infra_2020,placements_2020,academic_2020,Year_2020,Rank_2020
0,Indian Institute of Science Bangalore,83.33,1,52.74,2017,1,100.00,1,82.16,2018,...,100.00,1,82.28,2019,1,100.00,1,84.18,2020,1
1,Jawaharlal Nehru University,47.27,3,51.75,2017,2,46.28,3,67.57,2018,...,55.27,3,68.68,2019,2,67.24,3,70.16,2020,2
2,Banaras Hindu University,44.01,4,51.46,2017,3,43.62,4,63.52,2018,...,47.28,5,64.55,2019,3,53.99,6,63.15,2020,3
3,Jadavpur University,28.81,9,51.20,2017,5,35.50,6,59.68,2018,...,51.83,4,60.53,2019,6,71.44,2,61.99,2020,5
4,Anna University,43.94,5,48.90,2017,6,63.22,2,62.82,2018,...,62.72,2,60.35,2019,7,65.89,4,58.71,2020,12
5,University of Hyderabad,27.06,11,48.84,2017,7,21.66,19,60.54,2018,...,36.71,8,61.85,2019,4,58.32,5,61.70,2020,6
6,University of Delhi,30.76,7,48.27,2017,8,33.15,8,58.69,2018,...,41.11,6,57.59,2019,13,53.44,7,60.10,2020,11
7,Amrita Vishwa Vidyapeetham,26.12,12,48.19,2017,9,31.44,9,58.46,2018,...,31.01,12,59.22,2019,8,44.33,13,62.27,2020,4
8,Savitribai Phule Pune University,11.20,35,46.72,2017,10,15.04,26,58.24,2018,...,16.55,28,58.40,2019,10,44.99,11,61.13,2020,9
9,Aligarh Muslim University,16.62,21,83.28,2017,11,26.30,11,57.78,2018,...,18.46,27,58.36,2019,11,38.99,23,54.30,2020,17
10,Jamia Millia Islamia,9.73,42,61.53,2017,12,11.76,33,56.18,2018,...,14.26,37,58.07,2019,12,31.60,41,61.07,2020,10
11,Vellore Institute of Technology,32.95,6,58.25,2017,14,36.71,5,52.68,2018,...,35.31,9,51.44,2019,19,49.00,8,55.22,2020,16
12,Calcutta University,17.15,20,56.50,2017,16,26.30,11,53.38,2018,...,37.39,7,60.87,2019,5,47.99,9,61.53,2020,7
13,Manipal Academy of Higher Education-Manipal,27.67,10,55.37,2017,18,26.30,11,57.37,2018,...,30.21,14,58.50,2019,9,43.95,15,61.51,2020,8
14,Visva Bharati,4.71,69,54.70,2017,19,5.03,67,47.62,2018,...,11.52,44,46.27,2019,37,19.30,121,46.84,2020,50
15,Homi Bhabha National Institute,8.70,47,46.45,2017,21,9.85,42,48.98,2018,...,4.33,87,51.95,2019,17,33.54,34,56.04,2020,14
16,Bharath Institute of Higher Education & Research,3.79,84,46.45,2017,22,2.40,100,50.74,2018,...,3.19,103,46.32,2019,36,21.87,89,45.67,2020,59
17,Osmania University,11.16,36,45.52,2017,23,5.76,59,48.02,2018,...,9.26,50,49.86,2019,26,39.00,20,51.15,2020,29
18,Institute of Chemical Technology,20.69,16,44.95,2017,25,15.90,25,51.39,2018,...,20.28,21,52.62,2019,15,44.07,14,54.10,2020,18
19,Jamia Hamdard,1.87,110,44.84,2017,26,2.01,115,50.31,2018,...,6.86,64,51.73,2019,18,23.16,83,52.60,2020,21
20,Gauhati University,2.48,102,44.42,2017,27,6.11,57,45.44,2018,...,9.59,49,45.57,2019,42,22.20,87,47.10,2020,47
21,Bharathiar University,9.11,45,44.29,2017,28,22.63,17,55.08,2018,...,31.20,11,57.23,2019,14,37.18,26,58.30,2020,13
22,Kerala University,0.89,132,43.95,2017,29,7.17,51,47.72,2018,...,8.59,51,51.21,2019,22,21.54,92,52.35,2020,23
23,Tezpur University,7.09,54,43.78,2017,30,10.82,37,48.00,2018,...,15.71,31,48.47,2019,29,34.88,30,48.77,2020,40
24,Panjab University,18.99,18,43.13,2017,33,23.58,16,50.94,2018,...,27.09,16,51.25,2019,21,42.39,16,51.85,2020,26
25,Pondicherry University,4.67,70,42.70,2017,37,14.76,28,42.36,2018,...,19.25,25,44.88,2019,48,28.88,58,45.82,2020,58
26,University of Madras,10.82,40,41.85,2017,41,26.52,10,51.52,2018,...,30.01,15,51.34,2019,20,38.30,24,52.55,2020,22
27,Sri Venkateswara University,1.94,108,41.48,2017,42,2.01,115,43.44,2018,...,6.51,66,44.88,2019,49,37.00,27,48.84,2020,38
28,Andhra University,20.72,15,41.38,2017,43,9.53,43,50.39,2018,...,14.55,34,52.11,2019,16,39.82,19,53.82,2020,19
29,Sathyabama Institute of Science and Technology,11.08,38,41.30,2017,44,4.30,71,44.34,2018,...,2.41,123,45.58,2019,41,19.47,114,48.77,2020,39
30,Dr. D. Y. Patil Vidyapeeth Pune,11.61,33,40.59,2017,47,1.22,134,43.15,2018,...,7.56,59,45.11,2019,46,33.54,34,47.92,2020,46
31,North Eastern Hill University,3.24,93,40.51,2017,48,5.03,67,42.34,2018,...,6.51,66,45.99,2019,39,23.48,81,46.88,2020,49
32,Kalinga Institute of Industrial Technology,20.95,14,40.47,2017,49,3.55,82,44.81,2018,...,14.55,34,47.97,2019,31,31.30,45,52.33,2020,24
33,AMITY University,18.06,19,39.17,2017,52,5.40,64,42.99,2018,...,7.22,61,43.53,2019,58,30.10,54,49.02,2020,37
34,Banasthali Vidyapith,7.46,52,38.74,2017,53,4.30,71,41.88,2018,...,4.33,87,43.22,2019,61,20.18,105,46.32,2020,55
35,Bharati Vidyapeeth,30.64,8,38.73,2017,54,14.76,28,41.71,2018,...,13.66,39,42.89,2019,62,39.00,20,44.84,2020,63
36,Saveetha Institute of Medical and Technical Sc...,5.81,62,38.68,2017,55,3.17,88,44.00,2018,...,0.00,222,45.42,2019,43,19.11,122,48.56,2020,42
37,Calicut University,4.74,68,38.45,2017,57,5.76,59,40.06,2018,...,7.22,61,42.22,2019,64,21.21,95,46.37,2020,54
38,Mizoram University,0.03,214,38.36,2017,58,0.81,146,39.36,2018,...,2.02,135,40.27,2019,76,20.52,100,43.49,2020,67
39,Kurukshetra University,2.33,106,38.26,2017,59,3.93,75,39.45,2018,...,8.25,55,38.60,2019,98,33.21,37,39.79,2020,99
40,Shiv Nadar University,5.24,66,37.95,2017,60,0.00,203,43.68,2018,...,6.15,70,44.45,2019,52,21.54,92,46.11,2020,56
41,Symbiosis International University,14.31,28,37.67,2017,61,6.11,57,44.62,2018,...,3.19,103,43.65,2019,56,31.82,40,48.35,2020,43
42,KLE Academy of Higher Education and Research,0.69,141,37.25,2017,62,2.79,96,42.76,2018,...,4.33,87,40.92,2019,69,28.20,60,43.10,2020,70
43,University of Jammu,0.59,157,37.23,2017,63,1.22,134,43.19,2018,...,2.02,135,40.43,2019,74,31.47,42,46.55,2020,52
44,Goa University-Goa,5.09,67,37.16,2017,64,2.01,115,40.66,2018,...,1.63,148,38.76,2019,94,19.82,107,41.37,2020,81
45,Kalyani University,0.02,223,36.84,2017,66,3.17,88,38.87,2018,...,4.70,83,38.85,2019,91,19.47,114,40.91,2020,89
46,Dayalbagh Educational Institute,15.65,22,36.36,2017,72,12.38,30,41.95,2018,...,11.83,43,40.24,2019,77,30.70,48,41.21,2020,82
47,University of Kashmir,0.10,184,36.32,2017,73,0.00,203,43.96,2018,...,1.63,148,44.19,2019,53,25.82,68,46.99,2020,48
48,Dibrugarh University,0.68,143,36.28,2017,74,2.79,96,39.13,2018,...,5.07,80,39.30,2019,86,22.20,87,41.05,2020,84
49,Guru Nanak Dev University,4.65,71,35.83,2017,80,7.17,51,42.36,2018,...,5.80,73,43.69,2019,55,35.48,29,46.58,2020,51
50,Guru Gobind Singh Indraprastha University,3.37,90,35.60,2017,82,2.40,100,40.05,2018,...,3.58,98,41.21,2019,66,4.53,229,40.24,2020,95
51,Sri Balaji Vidyapeeth Mahatma Gandhi Medical C...,4.34,74,35.50,2017,83,0.00,203,40.25,2018,...,0.00,222,40.87,2019,72,18.74,129,40.92,2020,88
52,NITTE University,3.95,79,35.50,2017,84,8.53,46,39.70,2018,...,6.51,66,40.88,2019,70,22.85,85,42.19,2020,74
53,Periyar University,5.85,61,35.44,2017,85,4.30,71,38.58,2018,...,19.25,25,40.99,2019,68,28.09,61,41.09,2020,83
54,Cochin University of Science and Technology,1.89,109,35.42,2017,86,18.88,20,40.53,2018,...,14.84,32,41.42,2019,65,29.39,56,45.02,2020,62
55,Bharathidasan University,8.03,48,35.14,2017,88,26.30,11,41.63,2018,...,24.17,18,43.41,2019,60,40.09,18,46.41,2020,53
56,Alagappa University,4.17,77,33.66,2017,97,24.50,15,48.25,2018,...,26.65,17,48.54,2019,28,44.76,12,49.22,2020,36

In [40]:
df_data_check = pd.merge(df_data_20,df_2021,on='Name',suffixes=('','_2021'))

In [41]:
df_data_check

,Name,infra_2017,placements_2017,academic_2017,Year_2017,Rank_2017,infra_2018,placements_2018,academic_2018,Year_2018,...,infra_2020,placements_2020,academic_2020,Year_2020,Rank_2020,infra_2021,placements_2021,academic_2021,Year_2021,Rank_2021
0,Indian Institute of Science Bangalore,83.33,1,52.74,2017,1,100.00,1,82.16,2018,...,100.00,1,84.18,2020,1,100.00,1,82.67,2021,1
1,Jawaharlal Nehru University,47.27,3,51.75,2017,2,46.28,3,67.57,2018,...,67.24,3,70.16,2020,2,67.88,2,67.99,2021,2
2,Banaras Hindu University,44.01,4,51.46,2017,3,43.62,4,63.52,2018,...,53.99,6,63.15,2020,3,58.57,5,64.02,2021,3
3,Jadavpur University,28.81,9,51.20,2017,5,35.50,6,59.68,2018,...,71.44,2,61.99,2020,5,67.31,3,60.33,2021,8
4,Anna University,43.94,5,48.90,2017,6,63.22,2,62.82,2018,...,65.89,4,58.71,2020,12,67.20,4,54.97,2021,16
5,University of Hyderabad,27.06,11,48.84,2017,7,21.66,19,60.54,2018,...,58.32,5,61.70,2020,6,52.49,7,59.71,2021,9
6,University of Delhi,30.76,7,48.27,2017,8,33.15,8,58.69,2018,...,53.44,7,60.10,2020,11,55.37,6,57.09,2021,12
7,Amrita Vishwa Vidyapeetham,26.12,12,48.19,2017,9,31.44,9,58.46,2018,...,44.33,13,62.27,2020,4,48.36,10,61.23,2021,5
8,Savitribai Phule Pune University,11.20,35,46.72,2017,10,15.04,26,58.24,2018,...,44.99,11,61.13,2020,9,41.49,20,58.34,2021,11
9,Aligarh Muslim University,16.62,21,83.28,2017,11,26.30,11,57.78,2018,...,38.99,23,54.30,2020,17,42.90,17,58.97,2021,10
10,Jamia Millia Islamia,9.73,42,61.53,2017,12,11.76,33,56.18,2018,...,31.60,41,61.07,2020,10,32.17,45,60.74,2021,6
11,Vellore Institute of Technology,32.95,6,58.25,2017,14,36.71,5,52.68,2018,...,49.00,8,55.22,2020,16,51.16,8,56.63,2021,13
12,Calcutta University,17.15,20,56.50,2017,16,26.30,11,53.38,2018,...,47.99,9,61.53,2020,7,45.77,14,62.06,2021,4
13,Manipal Academy of Higher Education-Manipal,27.67,10,55.37,2017,18,26.30,11,57.37,2018,...,43.95,15,61.51,2020,8,40.93,21,60.58,2021,7
14,Visva Bharati,4.71,69,54.70,2017,19,5.03,67,47.62,2018,...,19.30,121,46.84,2020,50,16.35,165,42.76,2021,64
15,Homi Bhabha National Institute,8.70,47,46.45,2017,21,9.85,42,48.98,2018,...,33.54,34,56.04,2020,14,34.35,39,53.24,2021,18
16,Bharath Institute of Higher Education & Research,3.79,84,46.45,2017,22,2.40,100,50.74,2018,...,21.87,89,45.67,2020,59,21.90,97,46.44,2021,51
17,Osmania University,11.16,36,45.52,2017,23,5.76,59,48.02,2018,...,39.00,20,51.15,2020,29,39.67,24,49.16,2021,32
18,Institute of Chemical Technology,20.69,16,44.95,2017,25,15.90,25,51.39,2018,...,44.07,14,54.10,2020,18,45.43,15,56.10,2021,15
19,Jamia Hamdard,1.87,110,44.84,2017,26,2.01,115,50.31,2018,...,23.16,83,52.60,2020,21,23.67,88,48.02,2021,41
20,Gauhati University,2.48,102,44.42,2017,27,6.11,57,45.44,2018,...,22.20,87,47.10,2020,47,25.34,79,47.35,2021,45
21,Bharathiar University,9.11,45,44.29,2017,28,22.63,17,55.08,2018,...,37.18,26,58.30,2020,13,35.22,37,56.44,2021,14
22,Kerala University,0.89,132,43.95,2017,29,7.17,51,47.72,2018,...,21.54,92,52.35,2020,23,21.44,102,50.52,2021,27
23,Tezpur University,7.09,54,43.78,2017,30,10.82,37,48.00,2018,...,34.88,30,48.77,2020,40,32.14,47,47.27,2021,46
24,Panjab University,18.99,18,43.13,2017,33,23.58,16,50.94,2018,...,42.39,16,51.85,2020,26,50.12,9,51.59,2021,23
25,Pondicherry University,4.67,70,42.70,2017,37,14.76,28,42.36,2018,...,28.88,58,45.82,2020,58,30.52,57,44.36,2021,58
26,University of Madras,10.82,40,41.85,2017,41,26.52,10,51.52,2018,...,38.30,24,52.55,2020,22,38.17,26,50.46,2021,28
27,Sri Venkateswara University,1.94,108,41.48,2017,42,2.01,115,43.44,2018,...,37.00,27,48.84,2020,38,33.90,40,45.61,2021,54
28,Andhra University,20.72,15,41.38,2017,43,9.53,43,50.39,2018,...,39.82,19,53.82,2020,19,42.86,18,51.10,2021,24
29,Sathyabama Institute of Science and Technology,11.08,38,41.30,2017,44,4.30,71,44.34,2018,...,19.47,114,48.77,2020,39,23.23,92,48.17,2021,40
30,Dr. D. Y. Patil Vidyapeeth Pune,11.61,33,40.59,2017,47,1.22,134,43.15,2018,...,33.54,34,47.92,2020,46,40.41,22,46.74,2021,49
31,North Eastern Hill University,3.24,93,40.51,2017,48,5.03,67,42.34,2018,...,23.48,81,46.88,2020,49,26.14,72,44.24,2021,59
32,Kalinga Institute of Industrial Technology,20.95,14,40.47,2017,49,3.55,82,44.81,2018,...,31.30,45,52.33,2020,24,31.74,50,52.06,2021,21
33,AMITY University,18.06,19,39.17,2017,52,5.40,64,42.99,2018,...,30.10,54,49.02,2020,37,32.53,44,50.90,2021,25
34,Banasthali Vidyapith,7.46,52,38.74,2017,53,4.30,71,41.88,2018,...,20.18,105,46.32,2020,55,37.34,29,48.57,2021,35
35,Bharati Vidyapeeth,30.64,8,38.73,2017,54,14.76,28,41.71,2018,...,39.00,20,44.84,2020,63,37.74,27,42.10,2021,68
36,Saveetha Institute of Medical and Technical Sc...,5.81,62,38.68,2017,55,3.17,88,44.00,2018,...,19.11,122,48.56,2020,42,19.52,123,50.36,2021,29
37,Calicut University,4.74,68,38.45,2017,57,5.76,59,40.06,2018,...,21.21,95,46.37,2020,54,20.01,115,44.13,2021,60
38,Shiv Nadar University,5.24,66,37.95,2017,60,0.00,203,43.68,2018,...,21.54,92,46.11,2020,56,27.30,67,45.00,2021,56
39,KLE Academy of Higher Education and Research,0.69,141,37.25,2017,62,2.79,96,42.76,2018,...,28.20,60,43.10,2020,70,31.74,50,39.44,2021,91
40,University of Jammu,0.59,157,37.23,2017,63,1.22,134,43.19,2018,...,31.47,42,46.55,2020,52,32.01,48,42.52,2021,66
41,Dayalbagh Educational Institute,15.65,22,36.36,2017,72,12.38,30,41.95,2018,...,30.70,48,41.21,2020,82,28.35,65,39.06,2021,94
42,University of Kashmir,0.10,184,36.32,2017,73,0.00,203,43.96,2018,...,25.82,68,46.99,2020,48,25.52,76,46.97,2021,48
43,Guru Nanak Dev University,4.65,71,35.83,2017,80,7.17,51,42.36,2018,...,35.48,29,46.58,2020,51,42.52,19,45.67,2021,53
44,Guru Gobind Singh Indraprastha University,3.37,90,35.60,2017,82,2.40,100,40.05,2018,...,4.53,229,40.24,2020,95,14.81,171,40.79,2021,79
45,Sri Balaji Vidyapeeth Mahatma Gandhi Medical C...,4.34,74,35.50,2017,83,0.00,203,40.25,2018,...,18.74,129,40.92,2020,88,20.01,115,40.42,2021,80
46,NITTE University,3.95,79,35.50,2017,84,8.53,46,39.70,2018,...,22.85,85,42.19,2020,74,24.51,85,41.04,2021,77
47,Periyar University,5.85,61,35.44,2017,85,4.30,71,38.58,2018,...,28.09,61,41.09,2020,83,19.52,123,41.38,2021,74
48,Cochin University of Science and Technology,1.89,109,35.42,2017,86,18.88,20,40.53,2018,...,29.39,56,45.02,2020,62,28.41,64,47.37,2021,44
49,Bharathidasan University,8.03,48,35.14,2017,88,26.30,11,41.63,2018,...,40.09,18,46.41,2020,53,37.19,32,44.63,2021,57
50,Alagappa University,4.17,77,33.66,2017,97,24.50,15,48.25,2018,...,44.76,12,49.22,2020,36,46.34,13,49.09,2021,33

In [42]:
df_data_21 = pd.merge(df_data_20,df_2021,on='Name',suffixes=('','_2021'))

In [43]:
df_data_21

,Name,infra_2017,placements_2017,academic_2017,Year_2017,Rank_2017,infra_2018,placements_2018,academic_2018,Year_2018,...,infra_2020,placements_2020,academic_2020,Year_2020,Rank_2020,infra_2021,placements_2021,academic_2021,Year_2021,Rank_2021
0,Indian Institute of Science Bangalore,83.33,1,52.74,2017,1,100.00,1,82.16,2018,...,100.00,1,84.18,2020,1,100.00,1,82.67,2021,1
1,Jawaharlal Nehru University,47.27,3,51.75,2017,2,46.28,3,67.57,2018,...,67.24,3,70.16,2020,2,67.88,2,67.99,2021,2
2,Banaras Hindu University,44.01,4,51.46,2017,3,43.62,4,63.52,2018,...,53.99,6,63.15,2020,3,58.57,5,64.02,2021,3
3,Jadavpur University,28.81,9,51.20,2017,5,35.50,6,59.68,2018,...,71.44,2,61.99,2020,5,67.31,3,60.33,2021,8
4,Anna University,43.94,5,48.90,2017,6,63.22,2,62.82,2018,...,65.89,4,58.71,2020,12,67.20,4,54.97,2021,16
5,University of Hyderabad,27.06,11,48.84,2017,7,21.66,19,60.54,2018,...,58.32,5,61.70,2020,6,52.49,7,59.71,2021,9
6,University of Delhi,30.76,7,48.27,2017,8,33.15,8,58.69,2018,...,53.44,7,60.10,2020,11,55.37,6,57.09,2021,12
7,Amrita Vishwa Vidyapeetham,26.12,12,48.19,2017,9,31.44,9,58.46,2018,...,44.33,13,62.27,2020,4,48.36,10,61.23,2021,5
8,Savitribai Phule Pune University,11.20,35,46.72,2017,10,15.04,26,58.24,2018,...,44.99,11,61.13,2020,9,41.49,20,58.34,2021,11
9,Aligarh Muslim University,16.62,21,83.28,2017,11,26.30,11,57.78,2018,...,38.99,23,54.30,2020,17,42.90,17,58.97,2021,10
10,Jamia Millia Islamia,9.73,42,61.53,2017,12,11.76,33,56.18,2018,...,31.60,41,61.07,2020,10,32.17,45,60.74,2021,6
11,Vellore Institute of Technology,32.95,6,58.25,2017,14,36.71,5,52.68,2018,...,49.00,8,55.22,2020,16,51.16,8,56.63,2021,13
12,Calcutta University,17.15,20,56.50,2017,16,26.30,11,53.38,2018,...,47.99,9,61.53,2020,7,45.77,14,62.06,2021,4
13,Manipal Academy of Higher Education-Manipal,27.67,10,55.37,2017,18,26.30,11,57.37,2018,...,43.95,15,61.51,2020,8,40.93,21,60.58,2021,7
14,Visva Bharati,4.71,69,54.70,2017,19,5.03,67,47.62,2018,...,19.30,121,46.84,2020,50,16.35,165,42.76,2021,64
15,Homi Bhabha National Institute,8.70,47,46.45,2017,21,9.85,42,48.98,2018,...,33.54,34,56.04,2020,14,34.35,39,53.24,2021,18
16,Bharath Institute of Higher Education & Research,3.79,84,46.45,2017,22,2.40,100,50.74,2018,...,21.87,89,45.67,2020,59,21.90,97,46.44,2021,51
17,Osmania University,11.16,36,45.52,2017,23,5.76,59,48.02,2018,...,39.00,20,51.15,2020,29,39.67,24,49.16,2021,32
18,Institute of Chemical Technology,20.69,16,44.95,2017,25,15.90,25,51.39,2018,...,44.07,14,54.10,2020,18,45.43,15,56.10,2021,15
19,Jamia Hamdard,1.87,110,44.84,2017,26,2.01,115,50.31,2018,...,23.16,83,52.60,2020,21,23.67,88,48.02,2021,41
20,Gauhati University,2.48,102,44.42,2017,27,6.11,57,45.44,2018,...,22.20,87,47.10,2020,47,25.34,79,47.35,2021,45
21,Bharathiar University,9.11,45,44.29,2017,28,22.63,17,55.08,2018,...,37.18,26,58.30,2020,13,35.22,37,56.44,2021,14
22,Kerala University,0.89,132,43.95,2017,29,7.17,51,47.72,2018,...,21.54,92,52.35,2020,23,21.44,102,50.52,2021,27
23,Tezpur University,7.09,54,43.78,2017,30,10.82,37,48.00,2018,...,34.88,30,48.77,2020,40,32.14,47,47.27,2021,46
24,Panjab University,18.99,18,43.13,2017,33,23.58,16,50.94,2018,...,42.39,16,51.85,2020,26,50.12,9,51.59,2021,23
25,Pondicherry University,4.67,70,42.70,2017,37,14.76,28,42.36,2018,...,28.88,58,45.82,2020,58,30.52,57,44.36,2021,58
26,University of Madras,10.82,40,41.85,2017,41,26.52,10,51.52,2018,...,38.30,24,52.55,2020,22,38.17,26,50.46,2021,28
27,Sri Venkateswara University,1.94,108,41.48,2017,42,2.01,115,43.44,2018,...,37.00,27,48.84,2020,38,33.90,40,45.61,2021,54
28,Andhra University,20.72,15,41.38,2017,43,9.53,43,50.39,2018,...,39.82,19,53.82,2020,19,42.86,18,51.10,2021,24
29,Sathyabama Institute of Science and Technology,11.08,38,41.30,2017,44,4.30,71,44.34,2018,...,19.47,114,48.77,2020,39,23.23,92,48.17,2021,40
30,Dr. D. Y. Patil Vidyapeeth Pune,11.61,33,40.59,2017,47,1.22,134,43.15,2018,...,33.54,34,47.92,2020,46,40.41,22,46.74,2021,49
31,North Eastern Hill University,3.24,93,40.51,2017,48,5.03,67,42.34,2018,...,23.48,81,46.88,2020,49,26.14,72,44.24,2021,59
32,Kalinga Institute of Industrial Technology,20.95,14,40.47,2017,49,3.55,82,44.81,2018,...,31.30,45,52.33,2020,24,31.74,50,52.06,2021,21
33,AMITY University,18.06,19,39.17,2017,52,5.40,64,42.99,2018,...,30.10,54,49.02,2020,37,32.53,44,50.90,2021,25
34,Banasthali Vidyapith,7.46,52,38.74,2017,53,4.30,71,41.88,2018,...,20.18,105,46.32,2020,55,37.34,29,48.57,2021,35
35,Bharati Vidyapeeth,30.64,8,38.73,2017,54,14.76,28,41.71,2018,...,39.00,20,44.84,2020,63,37.74,27,42.10,2021,68
36,Saveetha Institute of Medical and Technical Sc...,5.81,62,38.68,2017,55,3.17,88,44.00,2018,...,19.11,122,48.56,2020,42,19.52,123,50.36,2021,29
37,Calicut University,4.74,68,38.45,2017,57,5.76,59,40.06,2018,...,21.21,95,46.37,2020,54,20.01,115,44.13,2021,60
38,Shiv Nadar University,5.24,66,37.95,2017,60,0.00,203,43.68,2018,...,21.54,92,46.11,2020,56,27.30,67,45.00,2021,56
39,KLE Academy of Higher Education and Research,0.69,141,37.25,2017,62,2.79,96,42.76,2018,...,28.20,60,43.10,2020,70,31.74,50,39.44,2021,91
40,University of Jammu,0.59,157,37.23,2017,63,1.22,134,43.19,2018,...,31.47,42,46.55,2020,52,32.01,48,42.52,2021,66
41,Dayalbagh Educational Institute,15.65,22,36.36,2017,72,12.38,30,41.95,2018,...,30.70,48,41.21,2020,82,28.35,65,39.06,2021,94
42,University of Kashmir,0.10,184,36.32,2017,73,0.00,203,43.96,2018,...,25.82,68,46.99,2020,48,25.52,76,46.97,2021,48
43,Guru Nanak Dev University,4.65,71,35.83,2017,80,7.17,51,42.36,2018,...,35.48,29,46.58,2020,51,42.52,19,45.67,2021,53
44,Guru Gobind Singh Indraprastha University,3.37,90,35.60,2017,82,2.40,100,40.05,2018,...,4.53,229,40.24,2020,95,14.81,171,40.79,2021,79
45,Sri Balaji Vidyapeeth Mahatma Gandhi Medical C...,4.34,74,35.50,2017,83,0.00,203,40.25,2018,...,18.74,129,40.92,2020,88,20.01,115,40.42,2021,80
46,NITTE University,3.95,79,35.50,2017,84,8.53,46,39.70,2018,...,22.85,85,42.19,2020,74,24.51,85,41.04,2021,77
47,Periyar University,5.85,61,35.44,2017,85,4.30,71,38.58,2018,...,28.09,61,41.09,2020,83,19.52,123,41.38,2021,74
48,Cochin University of Science and Technology,1.89,109,35.42,2017,86,18.88,20,40.53,2018,...,29.39,56,45.02,2020,62,28.41,64,47.37,2021,44
49,Bharathidasan University,8.03,48,35.14,2017,88,26.30,11,41.63,2018,...,40.09,18,46.41,2020,53,37.19,32,44.63,2021,57
50,Alagappa University,4.17,77,33.66,2017,97,24.50,15,48.25,2018,...,44.76,12,49.22,2020,36,46.34,13,49.09,2021,33

In [44]:
df_data_21.drop('Name',inplace=True,axis=1)

In [45]:
df_data_21

,infra_2017,placements_2017,academic_2017,Year_2017,Rank_2017,infra_2018,placements_2018,academic_2018,Year_2018,Rank_2018,...,infra_2020,placements_2020,academic_2020,Year_2020,Rank_2020,infra_2021,placements_2021,academic_2021,Year_2021,Rank_2021
0,83.33,1,52.74,2017,1,100.00,1,82.16,2018,1,...,100.00,1,84.18,2020,1,100.00,1,82.67,2021,1
1,47.27,3,51.75,2017,2,46.28,3,67.57,2018,2,...,67.24,3,70.16,2020,2,67.88,2,67.99,2021,2
2,44.01,4,51.46,2017,3,43.62,4,63.52,2018,3,...,53.99,6,63.15,2020,3,58.57,5,64.02,2021,3
3,28.81,9,51.20,2017,5,35.50,6,59.68,2018,6,...,71.44,2,61.99,2020,5,67.31,3,60.33,2021,8
4,43.94,5,48.90,2017,6,63.22,2,62.82,2018,4,...,65.89,4,58.71,2020,12,67.20,4,54.97,2021,16
5,27.06,11,48.84,2017,7,21.66,19,60.54,2018,5,...,58.32,5,61.70,2020,6,52.49,7,59.71,2021,9
6,30.76,7,48.27,2017,8,33.15,8,58.69,2018,7,...,53.44,7,60.10,2020,11,55.37,6,57.09,2021,12
7,26.12,12,48.19,2017,9,31.44,9,58.46,2018,8,...,44.33,13,62.27,2020,4,48.36,10,61.23,2021,5
8,11.20,35,46.72,2017,10,15.04,26,58.24,2018,9,...,44.99,11,61.13,2020,9,41.49,20,58.34,2021,11
9,16.62,21,83.28,2017,11,26.30,11,57.78,2018,10,...,38.99,23,54.30,2020,17,42.90,17,58.97,2021,10
10,9.73,42,61.53,2017,12,11.76,33,56.18,2018,12,...,31.60,41,61.07,2020,10,32.17,45,60.74,2021,6
11,32.95,6,58.25,2017,14,36.71,5,52.68,2018,16,...,49.00,8,55.22,2020,16,51.16,8,56.63,2021,13
12,17.15,20,56.50,2017,16,26.30,11,53.38,2018,14,...,47.99,9,61.53,2020,7,45.77,14,62.06,2021,4
13,27.67,10,55.37,2017,18,26.30,11,57.37,2018,11,...,43.95,15,61.51,2020,8,40.93,21,60.58,2021,7
14,4.71,69,54.70,2017,19,5.03,67,47.62,2018,31,...,19.30,121,46.84,2020,50,16.35,165,42.76,2021,64
15,8.70,47,46.45,2017,21,9.85,42,48.98,2018,26,...,33.54,34,56.04,2020,14,34.35,39,53.24,2021,18
16,3.79,84,46.45,2017,22,2.40,100,50.74,2018,21,...,21.87,89,45.67,2020,59,21.90,97,46.44,2021,51
17,11.16,36,45.52,2017,23,5.76,59,48.02,2018,28,...,39.00,20,51.15,2020,29,39.67,24,49.16,2021,32
18,20.69,16,44.95,2017,25,15.90,25,51.39,2018,19,...,44.07,14,54.10,2020,18,45.43,15,56.10,2021,15
19,1.87,110,44.84,2017,26,2.01,115,50.31,2018,23,...,23.16,83,52.60,2020,21,23.67,88,48.02,2021,41
20,2.48,102,44.42,2017,27,6.11,57,45.44,2018,39,...,22.20,87,47.10,2020,47,25.34,79,47.35,2021,45
21,9.11,45,44.29,2017,28,22.63,17,55.08,2018,13,...,37.18,26,58.30,2020,13,35.22,37,56.44,2021,14
22,0.89,132,43.95,2017,29,7.17,51,47.72,2018,30,...,21.54,92,52.35,2020,23,21.44,102,50.52,2021,27
23,7.09,54,43.78,2017,30,10.82,37,48.00,2018,29,...,34.88,30,48.77,2020,40,32.14,47,47.27,2021,46
24,18.99,18,43.13,2017,33,23.58,16,50.94,2018,20,...,42.39,16,51.85,2020,26,50.12,9,51.59,2021,23
25,4.67,70,42.70,2017,37,14.76,28,42.36,2018,59,...,28.88,58,45.82,2020,58,30.52,57,44.36,2021,58
26,10.82,40,41.85,2017,41,26.52,10,51.52,2018,18,...,38.30,24,52.55,2020,22,38.17,26,50.46,2021,28
27,1.94,108,41.48,2017,42,2.01,115,43.44,2018,49,...,37.00,27,48.84,2020,38,33.90,40,45.61,2021,54
28,20.72,15,41.38,2017,43,9.53,43,50.39,2018,22,...,39.82,19,53.82,2020,19,42.86,18,51.10,2021,24
29,11.08,38,41.30,2017,44,4.30,71,44.34,2018,45,...,19.47,114,48.77,2020,39,23.23,92,48.17,2021,40
30,11.61,33,40.59,2017,47,1.22,134,43.15,2018,52,...,33.54,34,47.92,2020,46,40.41,22,46.74,2021,49
31,3.24,93,40.51,2017,48,5.03,67,42.34,2018,61,...,23.48,81,46.88,2020,49,26.14,72,44.24,2021,59
32,20.95,14,40.47,2017,49,3.55,82,44.81,2018,42,...,31.30,45,52.33,2020,24,31.74,50,52.06,2021,21
33,18.06,19,39.17,2017,52,5.40,64,42.99,2018,53,...,30.10,54,49.02,2020,37,32.53,44,50.90,2021,25
34,7.46,52,38.74,2017,53,4.30,71,41.88,2018,64,...,20.18,105,46.32,2020,55,37.34,29,48.57,2021,35
35,30.64,8,38.73,2017,54,14.76,28,41.71,2018,66,...,39.00,20,44.84,2020,63,37.74,27,42.10,2021,68
36,5.81,62,38.68,2017,55,3.17,88,44.00,2018,46,...,19.11,122,48.56,2020,42,19.52,123,50.36,2021,29
37,4.74,68,38.45,2017,57,5.76,59,40.06,2018,73,...,21.21,95,46.37,2020,54,20.01,115,44.13,2021,60
38,5.24,66,37.95,2017,60,0.00,203,43.68,2018,48,...,21.54,92,46.11,2020,56,27.30,67,45.00,2021,56
39,0.69,141,37.25,2017,62,2.79,96,42.76,2018,57,...,28.20,60,43.10,2020,70,31.74,50,39.44,2021,91
40,0.59,157,37.23,2017,63,1.22,134,43.19,2018,51,...,31.47,42,46.55,2020,52,32.01,48,42.52,2021,66
41,15.65,22,36.36,2017,72,12.38,30,41.95,2018,63,...,30.70,48,41.21,2020,82,28.35,65,39.06,2021,94
42,0.10,184,36.32,2017,73,0.00,203,43.96,2018,47,...,25.82,68,46.99,2020,48,25.52,76,46.97,2021,48
43,4.65,71,35.83,2017,80,7.17,51,42.36,2018,60,...,35.48,29,46.58,2020,51,42.52,19,45.67,2021,53
44,3.37,90,35.60,2017,82,2.40,100,40.05,2018,74,...,4.53,229,40.24,2020,95,14.81,171,40.79,2021,79
45,4.34,74,35.50,2017,83,0.00,203,40.25,2018,72,...,18.74,129,40.92,2020,88,20.01,115,40.42,2021,80
46,3.95,79,35.50,2017,84,8.53,46,39.70,2018,77,...,22.85,85,42.19,2020,74,24.51,85,41.04,2021,77
47,5.85,61,35.44,2017,85,4.30,71,38.58,2018,90,...,28.09,61,41.09,2020,83,19.52,123,41.38,2021,74
48,1.89,109,35.42,2017,86,18.88,20,40.53,2018,69,...,29.39,56,45.02,2020,62,28.41,64,47.37,2021,44
49,8.03,48,35.14,2017,88,26.30,11,41.63,2018,67,...,40.09,18,46.41,2020,53,37.19,32,44.63,2021,57
50,4.17,77,33.66,2017,97,24.50,15,48.25,2018,27,...,44.76,12,49.22,2020,36,46.34,13,49.09,2021,33

In [46]:
df_data_21.drop(['Year_2017','Year_2018','Year_2020','Year_2021'],inplace=True,axis=1)

In [47]:
df_data_21

,infra_2017,placements_2017,academic_2017,Rank_2017,infra_2018,placements_2018,academic_2018,Rank_2018,infra,placements,...,Year,Rank,infra_2020,placements_2020,academic_2020,Rank_2020,infra_2021,placements_2021,academic_2021,Rank_2021
0,83.33,1,52.74,1,100.00,1,82.16,1,100.00,1,...,2019,1,100.00,1,84.18,1,100.00,1,82.67,1
1,47.27,3,51.75,2,46.28,3,67.57,2,55.27,3,...,2019,2,67.24,3,70.16,2,67.88,2,67.99,2
2,44.01,4,51.46,3,43.62,4,63.52,3,47.28,5,...,2019,3,53.99,6,63.15,3,58.57,5,64.02,3
3,28.81,9,51.20,5,35.50,6,59.68,6,51.83,4,...,2019,6,71.44,2,61.99,5,67.31,3,60.33,8
4,43.94,5,48.90,6,63.22,2,62.82,4,62.72,2,...,2019,7,65.89,4,58.71,12,67.20,4,54.97,16
5,27.06,11,48.84,7,21.66,19,60.54,5,36.71,8,...,2019,4,58.32,5,61.70,6,52.49,7,59.71,9
6,30.76,7,48.27,8,33.15,8,58.69,7,41.11,6,...,2019,13,53.44,7,60.10,11,55.37,6,57.09,12
7,26.12,12,48.19,9,31.44,9,58.46,8,31.01,12,...,2019,8,44.33,13,62.27,4,48.36,10,61.23,5
8,11.20,35,46.72,10,15.04,26,58.24,9,16.55,28,...,2019,10,44.99,11,61.13,9,41.49,20,58.34,11
9,16.62,21,83.28,11,26.30,11,57.78,10,18.46,27,...,2019,11,38.99,23,54.30,17,42.90,17,58.97,10
10,9.73,42,61.53,12,11.76,33,56.18,12,14.26,37,...,2019,12,31.60,41,61.07,10,32.17,45,60.74,6
11,32.95,6,58.25,14,36.71,5,52.68,16,35.31,9,...,2019,19,49.00,8,55.22,16,51.16,8,56.63,13
12,17.15,20,56.50,16,26.30,11,53.38,14,37.39,7,...,2019,5,47.99,9,61.53,7,45.77,14,62.06,4
13,27.67,10,55.37,18,26.30,11,57.37,11,30.21,14,...,2019,9,43.95,15,61.51,8,40.93,21,60.58,7
14,4.71,69,54.70,19,5.03,67,47.62,31,11.52,44,...,2019,37,19.30,121,46.84,50,16.35,165,42.76,64
15,8.70,47,46.45,21,9.85,42,48.98,26,4.33,87,...,2019,17,33.54,34,56.04,14,34.35,39,53.24,18
16,3.79,84,46.45,22,2.40,100,50.74,21,3.19,103,...,2019,36,21.87,89,45.67,59,21.90,97,46.44,51
17,11.16,36,45.52,23,5.76,59,48.02,28,9.26,50,...,2019,26,39.00,20,51.15,29,39.67,24,49.16,32
18,20.69,16,44.95,25,15.90,25,51.39,19,20.28,21,...,2019,15,44.07,14,54.10,18,45.43,15,56.10,15
19,1.87,110,44.84,26,2.01,115,50.31,23,6.86,64,...,2019,18,23.16,83,52.60,21,23.67,88,48.02,41
20,2.48,102,44.42,27,6.11,57,45.44,39,9.59,49,...,2019,42,22.20,87,47.10,47,25.34,79,47.35,45
21,9.11,45,44.29,28,22.63,17,55.08,13,31.20,11,...,2019,14,37.18,26,58.30,13,35.22,37,56.44,14
22,0.89,132,43.95,29,7.17,51,47.72,30,8.59,51,...,2019,22,21.54,92,52.35,23,21.44,102,50.52,27
23,7.09,54,43.78,30,10.82,37,48.00,29,15.71,31,...,2019,29,34.88,30,48.77,40,32.14,47,47.27,46
24,18.99,18,43.13,33,23.58,16,50.94,20,27.09,16,...,2019,21,42.39,16,51.85,26,50.12,9,51.59,23
25,4.67,70,42.70,37,14.76,28,42.36,59,19.25,25,...,2019,48,28.88,58,45.82,58,30.52,57,44.36,58
26,10.82,40,41.85,41,26.52,10,51.52,18,30.01,15,...,2019,20,38.30,24,52.55,22,38.17,26,50.46,28
27,1.94,108,41.48,42,2.01,115,43.44,49,6.51,66,...,2019,49,37.00,27,48.84,38,33.90,40,45.61,54
28,20.72,15,41.38,43,9.53,43,50.39,22,14.55,34,...,2019,16,39.82,19,53.82,19,42.86,18,51.10,24
29,11.08,38,41.30,44,4.30,71,44.34,45,2.41,123,...,2019,41,19.47,114,48.77,39,23.23,92,48.17,40
30,11.61,33,40.59,47,1.22,134,43.15,52,7.56,59,...,2019,46,33.54,34,47.92,46,40.41,22,46.74,49
31,3.24,93,40.51,48,5.03,67,42.34,61,6.51,66,...,2019,39,23.48,81,46.88,49,26.14,72,44.24,59
32,20.95,14,40.47,49,3.55,82,44.81,42,14.55,34,...,2019,31,31.30,45,52.33,24,31.74,50,52.06,21
33,18.06,19,39.17,52,5.40,64,42.99,53,7.22,61,...,2019,58,30.10,54,49.02,37,32.53,44,50.90,25
34,7.46,52,38.74,53,4.30,71,41.88,64,4.33,87,...,2019,61,20.18,105,46.32,55,37.34,29,48.57,35
35,30.64,8,38.73,54,14.76,28,41.71,66,13.66,39,...,2019,62,39.00,20,44.84,63,37.74,27,42.10,68
36,5.81,62,38.68,55,3.17,88,44.00,46,0.00,222,...,2019,43,19.11,122,48.56,42,19.52,123,50.36,29
37,4.74,68,38.45,57,5.76,59,40.06,73,7.22,61,...,2019,64,21.21,95,46.37,54,20.01,115,44.13,60
38,5.24,66,37.95,60,0.00,203,43.68,48,6.15,70,...,2019,52,21.54,92,46.11,56,27.30,67,45.00,56
39,0.69,141,37.25,62,2.79,96,42.76,57,4.33,87,...,2019,69,28.20,60,43.10,70,31.74,50,39.44,91
40,0.59,157,37.23,63,1.22,134,43.19,51,2.02,135,...,2019,74,31.47,42,46.55,52,32.01,48,42.52,66
41,15.65,22,36.36,72,12.38,30,41.95,63,11.83,43,...,2019,77,30.70,48,41.21,82,28.35,65,39.06,94
42,0.10,184,36.32,73,0.00,203,43.96,47,1.63,148,...,2019,53,25.82,68,46.99,48,25.52,76,46.97,48
43,4.65,71,35.83,80,7.17,51,42.36,60,5.80,73,...,2019,55,35.48,29,46.58,51,42.52,19,45.67,53
44,3.37,90,35.60,82,2.40,100,40.05,74,3.58,98,...,2019,66,4.53,229,40.24,95,14.81,171,40.79,79
45,4.34,74,35.50,83,0.00,203,40.25,72,0.00,222,...,2019,72,18.74,129,40.92,88,20.01,115,40.42,80
46,3.95,79,35.50,84,8.53,46,39.70,77,6.51,66,...,2019,70,22.85,85,42.19,74,24.51,85,41.04,77
47,5.85,61,35.44,85,4.30,71,38.58,90,19.25,25,...,2019,68,28.09,61,41.09,83,19.52,123,41.38,74
48,1.89,109,35.42,86,18.88,20,40.53,69,14.84,32,...,2019,65,29.39,56,45.02,62,28.41,64,47.37,44
49,8.03,48,35.14,88,26.30,11,41.63,67,24.17,18,...,2019,60,40.09,18,46.41,53,37.19,32,44.63,57
50,4.17,77,33.66,97,24.50,15,48.25,27,26.65,17,...,2019,28,44.76,12,49.22,36,46.34,13,49.09,33

In [48]:
df_data_21.drop('Year',inplace=True,axis=1)

In [49]:
df_data_21

,infra_2017,placements_2017,academic_2017,Rank_2017,infra_2018,placements_2018,academic_2018,Rank_2018,infra,placements,academic,Rank,infra_2020,placements_2020,academic_2020,Rank_2020,infra_2021,placements_2021,academic_2021,Rank_2021
0,83.33,1,52.74,1,100.00,1,82.16,1,100.00,1,82.28,1,100.00,1,84.18,1,100.00,1,82.67,1
1,47.27,3,51.75,2,46.28,3,67.57,2,55.27,3,68.68,2,67.24,3,70.16,2,67.88,2,67.99,2
2,44.01,4,51.46,3,43.62,4,63.52,3,47.28,5,64.55,3,53.99,6,63.15,3,58.57,5,64.02,3
3,28.81,9,51.20,5,35.50,6,59.68,6,51.83,4,60.53,6,71.44,2,61.99,5,67.31,3,60.33,8
4,43.94,5,48.90,6,63.22,2,62.82,4,62.72,2,60.35,7,65.89,4,58.71,12,67.20,4,54.97,16
5,27.06,11,48.84,7,21.66,19,60.54,5,36.71,8,61.85,4,58.32,5,61.70,6,52.49,7,59.71,9
6,30.76,7,48.27,8,33.15,8,58.69,7,41.11,6,57.59,13,53.44,7,60.10,11,55.37,6,57.09,12
7,26.12,12,48.19,9,31.44,9,58.46,8,31.01,12,59.22,8,44.33,13,62.27,4,48.36,10,61.23,5
8,11.20,35,46.72,10,15.04,26,58.24,9,16.55,28,58.40,10,44.99,11,61.13,9,41.49,20,58.34,11
9,16.62,21,83.28,11,26.30,11,57.78,10,18.46,27,58.36,11,38.99,23,54.30,17,42.90,17,58.97,10
10,9.73,42,61.53,12,11.76,33,56.18,12,14.26,37,58.07,12,31.60,41,61.07,10,32.17,45,60.74,6
11,32.95,6,58.25,14,36.71,5,52.68,16,35.31,9,51.44,19,49.00,8,55.22,16,51.16,8,56.63,13
12,17.15,20,56.50,16,26.30,11,53.38,14,37.39,7,60.87,5,47.99,9,61.53,7,45.77,14,62.06,4
13,27.67,10,55.37,18,26.30,11,57.37,11,30.21,14,58.50,9,43.95,15,61.51,8,40.93,21,60.58,7
14,4.71,69,54.70,19,5.03,67,47.62,31,11.52,44,46.27,37,19.30,121,46.84,50,16.35,165,42.76,64
15,8.70,47,46.45,21,9.85,42,48.98,26,4.33,87,51.95,17,33.54,34,56.04,14,34.35,39,53.24,18
16,3.79,84,46.45,22,2.40,100,50.74,21,3.19,103,46.32,36,21.87,89,45.67,59,21.90,97,46.44,51
17,11.16,36,45.52,23,5.76,59,48.02,28,9.26,50,49.86,26,39.00,20,51.15,29,39.67,24,49.16,32
18,20.69,16,44.95,25,15.90,25,51.39,19,20.28,21,52.62,15,44.07,14,54.10,18,45.43,15,56.10,15
19,1.87,110,44.84,26,2.01,115,50.31,23,6.86,64,51.73,18,23.16,83,52.60,21,23.67,88,48.02,41
20,2.48,102,44.42,27,6.11,57,45.44,39,9.59,49,45.57,42,22.20,87,47.10,47,25.34,79,47.35,45
21,9.11,45,44.29,28,22.63,17,55.08,13,31.20,11,57.23,14,37.18,26,58.30,13,35.22,37,56.44,14
22,0.89,132,43.95,29,7.17,51,47.72,30,8.59,51,51.21,22,21.54,92,52.35,23,21.44,102,50.52,27
23,7.09,54,43.78,30,10.82,37,48.00,29,15.71,31,48.47,29,34.88,30,48.77,40,32.14,47,47.27,46
24,18.99,18,43.13,33,23.58,16,50.94,20,27.09,16,51.25,21,42.39,16,51.85,26,50.12,9,51.59,23
25,4.67,70,42.70,37,14.76,28,42.36,59,19.25,25,44.88,48,28.88,58,45.82,58,30.52,57,44.36,58
26,10.82,40,41.85,41,26.52,10,51.52,18,30.01,15,51.34,20,38.30,24,52.55,22,38.17,26,50.46,28
27,1.94,108,41.48,42,2.01,115,43.44,49,6.51,66,44.88,49,37.00,27,48.84,38,33.90,40,45.61,54
28,20.72,15,41.38,43,9.53,43,50.39,22,14.55,34,52.11,16,39.82,19,53.82,19,42.86,18,51.10,24
29,11.08,38,41.30,44,4.30,71,44.34,45,2.41,123,45.58,41,19.47,114,48.77,39,23.23,92,48.17,40
30,11.61,33,40.59,47,1.22,134,43.15,52,7.56,59,45.11,46,33.54,34,47.92,46,40.41,22,46.74,49
31,3.24,93,40.51,48,5.03,67,42.34,61,6.51,66,45.99,39,23.48,81,46.88,49,26.14,72,44.24,59
32,20.95,14,40.47,49,3.55,82,44.81,42,14.55,34,47.97,31,31.30,45,52.33,24,31.74,50,52.06,21
33,18.06,19,39.17,52,5.40,64,42.99,53,7.22,61,43.53,58,30.10,54,49.02,37,32.53,44,50.90,25
34,7.46,52,38.74,53,4.30,71,41.88,64,4.33,87,43.22,61,20.18,105,46.32,55,37.34,29,48.57,35
35,30.64,8,38.73,54,14.76,28,41.71,66,13.66,39,42.89,62,39.00,20,44.84,63,37.74,27,42.10,68
36,5.81,62,38.68,55,3.17,88,44.00,46,0.00,222,45.42,43,19.11,122,48.56,42,19.52,123,50.36,29
37,4.74,68,38.45,57,5.76,59,40.06,73,7.22,61,42.22,64,21.21,95,46.37,54,20.01,115,44.13,60
38,5.24,66,37.95,60,0.00,203,43.68,48,6.15,70,44.45,52,21.54,92,46.11,56,27.30,67,45.00,56
39,0.69,141,37.25,62,2.79,96,42.76,57,4.33,87,40.92,69,28.20,60,43.10,70,31.74,50,39.44,91
40,0.59,157,37.23,63,1.22,134,43.19,51,2.02,135,40.43,74,31.47,42,46.55,52,32.01,48,42.52,66
41,15.65,22,36.36,72,12.38,30,41.95,63,11.83,43,40.24,77,30.70,48,41.21,82,28.35,65,39.06,94
42,0.10,184,36.32,73,0.00,203,43.96,47,1.63,148,44.19,53,25.82,68,46.99,48,25.52,76,46.97,48
43,4.65,71,35.83,80,7.17,51,42.36,60,5.80,73,43.69,55,35.48,29,46.58,51,42.52,19,45.67,53
44,3.37,90,35.60,82,2.40,100,40.05,74,3.58,98,41.21,66,4.53,229,40.24,95,14.81,171,40.79,79
45,4.34,74,35.50,83,0.00,203,40.25,72,0.00,222,40.87,72,18.74,129,40.92,88,20.01,115,40.42,80
46,3.95,79,35.50,84,8.53,46,39.70,77,6.51,66,40.88,70,22.85,85,42.19,74,24.51,85,41.04,77
47,5.85,61,35.44,85,4.30,71,38.58,90,19.25,25,40.99,68,28.09,61,41.09,83,19.52,123,41.38,74
48,1.89,109,35.42,86,18.88,20,40.53,69,14.84,32,41.42,65,29.39,56,45.02,62,28.41,64,47.37,44
49,8.03,48,35.14,88,26.30,11,41.63,67,24.17,18,43.41,60,40.09,18,46.41,53,37.19,32,44.63,57
50,4.17,77,33.66,97,24.50,15,48.25,27,26.65,17,48.54,28,44.76,12,49.22,36,46.34,13,49.09,33

In [50]:
df_data_21.drop(['infra_2021','placements_2021','academic_2021'],inplace=True,axis=1)

In [51]:
df_data_21

,infra_2017,placements_2017,academic_2017,Rank_2017,infra_2018,placements_2018,academic_2018,Rank_2018,infra,placements,academic,Rank,infra_2020,placements_2020,academic_2020,Rank_2020,Rank_2021
0,83.33,1,52.74,1,100.00,1,82.16,1,100.00,1,82.28,1,100.00,1,84.18,1,1
1,47.27,3,51.75,2,46.28,3,67.57,2,55.27,3,68.68,2,67.24,3,70.16,2,2
2,44.01,4,51.46,3,43.62,4,63.52,3,47.28,5,64.55,3,53.99,6,63.15,3,3
3,28.81,9,51.20,5,35.50,6,59.68,6,51.83,4,60.53,6,71.44,2,61.99,5,8
4,43.94,5,48.90,6,63.22,2,62.82,4,62.72,2,60.35,7,65.89,4,58.71,12,16
5,27.06,11,48.84,7,21.66,19,60.54,5,36.71,8,61.85,4,58.32,5,61.70,6,9
6,30.76,7,48.27,8,33.15,8,58.69,7,41.11,6,57.59,13,53.44,7,60.10,11,12
7,26.12,12,48.19,9,31.44,9,58.46,8,31.01,12,59.22,8,44.33,13,62.27,4,5
8,11.20,35,46.72,10,15.04,26,58.24,9,16.55,28,58.40,10,44.99,11,61.13,9,11
9,16.62,21,83.28,11,26.30,11,57.78,10,18.46,27,58.36,11,38.99,23,54.30,17,10
10,9.73,42,61.53,12,11.76,33,56.18,12,14.26,37,58.07,12,31.60,41,61.07,10,6
11,32.95,6,58.25,14,36.71,5,52.68,16,35.31,9,51.44,19,49.00,8,55.22,16,13
12,17.15,20,56.50,16,26.30,11,53.38,14,37.39,7,60.87,5,47.99,9,61.53,7,4
13,27.67,10,55.37,18,26.30,11,57.37,11,30.21,14,58.50,9,43.95,15,61.51,8,7
14,4.71,69,54.70,19,5.03,67,47.62,31,11.52,44,46.27,37,19.30,121,46.84,50,64
15,8.70,47,46.45,21,9.85,42,48.98,26,4.33,87,51.95,17,33.54,34,56.04,14,18
16,3.79,84,46.45,22,2.40,100,50.74,21,3.19,103,46.32,36,21.87,89,45.67,59,51
17,11.16,36,45.52,23,5.76,59,48.02,28,9.26,50,49.86,26,39.00,20,51.15,29,32
18,20.69,16,44.95,25,15.90,25,51.39,19,20.28,21,52.62,15,44.07,14,54.10,18,15
19,1.87,110,44.84,26,2.01,115,50.31,23,6.86,64,51.73,18,23.16,83,52.60,21,41
20,2.48,102,44.42,27,6.11,57,45.44,39,9.59,49,45.57,42,22.20,87,47.10,47,45
21,9.11,45,44.29,28,22.63,17,55.08,13,31.20,11,57.23,14,37.18,26,58.30,13,14
22,0.89,132,43.95,29,7.17,51,47.72,30,8.59,51,51.21,22,21.54,92,52.35,23,27
23,7.09,54,43.78,30,10.82,37,48.00,29,15.71,31,48.47,29,34.88,30,48.77,40,46
24,18.99,18,43.13,33,23.58,16,50.94,20,27.09,16,51.25,21,42.39,16,51.85,26,23
25,4.67,70,42.70,37,14.76,28,42.36,59,19.25,25,44.88,48,28.88,58,45.82,58,58
26,10.82,40,41.85,41,26.52,10,51.52,18,30.01,15,51.34,20,38.30,24,52.55,22,28
27,1.94,108,41.48,42,2.01,115,43.44,49,6.51,66,44.88,49,37.00,27,48.84,38,54
28,20.72,15,41.38,43,9.53,43,50.39,22,14.55,34,52.11,16,39.82,19,53.82,19,24
29,11.08,38,41.30,44,4.30,71,44.34,45,2.41,123,45.58,41,19.47,114,48.77,39,40
30,11.61,33,40.59,47,1.22,134,43.15,52,7.56,59,45.11,46,33.54,34,47.92,46,49
31,3.24,93,40.51,48,5.03,67,42.34,61,6.51,66,45.99,39,23.48,81,46.88,49,59
32,20.95,14,40.47,49,3.55,82,44.81,42,14.55,34,47.97,31,31.30,45,52.33,24,21
33,18.06,19,39.17,52,5.40,64,42.99,53,7.22,61,43.53,58,30.10,54,49.02,37,25
34,7.46,52,38.74,53,4.30,71,41.88,64,4.33,87,43.22,61,20.18,105,46.32,55,35
35,30.64,8,38.73,54,14.76,28,41.71,66,13.66,39,42.89,62,39.00,20,44.84,63,68
36,5.81,62,38.68,55,3.17,88,44.00,46,0.00,222,45.42,43,19.11,122,48.56,42,29
37,4.74,68,38.45,57,5.76,59,40.06,73,7.22,61,42.22,64,21.21,95,46.37,54,60
38,5.24,66,37.95,60,0.00,203,43.68,48,6.15,70,44.45,52,21.54,92,46.11,56,56
39,0.69,141,37.25,62,2.79,96,42.76,57,4.33,87,40.92,69,28.20,60,43.10,70,91
40,0.59,157,37.23,63,1.22,134,43.19,51,2.02,135,40.43,74,31.47,42,46.55,52,66
41,15.65,22,36.36,72,12.38,30,41.95,63,11.83,43,40.24,77,30.70,48,41.21,82,94
42,0.10,184,36.32,73,0.00,203,43.96,47,1.63,148,44.19,53,25.82,68,46.99,48,48
43,4.65,71,35.83,80,7.17,51,42.36,60,5.80,73,43.69,55,35.48,29,46.58,51,53
44,3.37,90,35.60,82,2.40,100,40.05,74,3.58,98,41.21,66,4.53,229,40.24,95,79
45,4.34,74,35.50,83,0.00,203,40.25,72,0.00,222,40.87,72,18.74,129,40.92,88,80
46,3.95,79,35.50,84,8.53,46,39.70,77,6.51,66,40.88,70,22.85,85,42.19,74,77
47,5.85,61,35.44,85,4.30,71,38.58,90,19.25,25,40.99,68,28.09,61,41.09,83,74
48,1.89,109,35.42,86,18.88,20,40.53,69,14.84,32,41.42,65,29.39,56,45.02,62,44
49,8.03,48,35.14,88,26.30,11,41.63,67,24.17,18,43.41,60,40.09,18,46.41,53,57
50,4.17,77,33.66,97,24.50,15,48.25,27,26.65,17,48.54,28,44.76,12,49.22,36,33

In [52]:
X = df_data_21.drop('Rank_2021',axis=1)

In [53]:
X

,infra_2017,placements_2017,academic_2017,Rank_2017,infra_2018,placements_2018,academic_2018,Rank_2018,infra,placements,academic,Rank,infra_2020,placements_2020,academic_2020,Rank_2020
0,83.33,1,52.74,1,100.00,1,82.16,1,100.00,1,82.28,1,100.00,1,84.18,1
1,47.27,3,51.75,2,46.28,3,67.57,2,55.27,3,68.68,2,67.24,3,70.16,2
2,44.01,4,51.46,3,43.62,4,63.52,3,47.28,5,64.55,3,53.99,6,63.15,3
3,28.81,9,51.20,5,35.50,6,59.68,6,51.83,4,60.53,6,71.44,2,61.99,5
4,43.94,5,48.90,6,63.22,2,62.82,4,62.72,2,60.35,7,65.89,4,58.71,12
5,27.06,11,48.84,7,21.66,19,60.54,5,36.71,8,61.85,4,58.32,5,61.70,6
6,30.76,7,48.27,8,33.15,8,58.69,7,41.11,6,57.59,13,53.44,7,60.10,11
7,26.12,12,48.19,9,31.44,9,58.46,8,31.01,12,59.22,8,44.33,13,62.27,4
8,11.20,35,46.72,10,15.04,26,58.24,9,16.55,28,58.40,10,44.99,11,61.13,9
9,16.62,21,83.28,11,26.30,11,57.78,10,18.46,27,58.36,11,38.99,23,54.30,17
10,9.73,42,61.53,12,11.76,33,56.18,12,14.26,37,58.07,12,31.60,41,61.07,10
11,32.95,6,58.25,14,36.71,5,52.68,16,35.31,9,51.44,19,49.00,8,55.22,16
12,17.15,20,56.50,16,26.30,11,53.38,14,37.39,7,60.87,5,47.99,9,61.53,7
13,27.67,10,55.37,18,26.30,11,57.37,11,30.21,14,58.50,9,43.95,15,61.51,8
14,4.71,69,54.70,19,5.03,67,47.62,31,11.52,44,46.27,37,19.30,121,46.84,50
15,8.70,47,46.45,21,9.85,42,48.98,26,4.33,87,51.95,17,33.54,34,56.04,14
16,3.79,84,46.45,22,2.40,100,50.74,21,3.19,103,46.32,36,21.87,89,45.67,59
17,11.16,36,45.52,23,5.76,59,48.02,28,9.26,50,49.86,26,39.00,20,51.15,29
18,20.69,16,44.95,25,15.90,25,51.39,19,20.28,21,52.62,15,44.07,14,54.10,18
19,1.87,110,44.84,26,2.01,115,50.31,23,6.86,64,51.73,18,23.16,83,52.60,21
20,2.48,102,44.42,27,6.11,57,45.44,39,9.59,49,45.57,42,22.20,87,47.10,47
21,9.11,45,44.29,28,22.63,17,55.08,13,31.20,11,57.23,14,37.18,26,58.30,13
22,0.89,132,43.95,29,7.17,51,47.72,30,8.59,51,51.21,22,21.54,92,52.35,23
23,7.09,54,43.78,30,10.82,37,48.00,29,15.71,31,48.47,29,34.88,30,48.77,40
24,18.99,18,43.13,33,23.58,16,50.94,20,27.09,16,51.25,21,42.39,16,51.85,26
25,4.67,70,42.70,37,14.76,28,42.36,59,19.25,25,44.88,48,28.88,58,45.82,58
26,10.82,40,41.85,41,26.52,10,51.52,18,30.01,15,51.34,20,38.30,24,52.55,22
27,1.94,108,41.48,42,2.01,115,43.44,49,6.51,66,44.88,49,37.00,27,48.84,38
28,20.72,15,41.38,43,9.53,43,50.39,22,14.55,34,52.11,16,39.82,19,53.82,19
29,11.08,38,41.30,44,4.30,71,44.34,45,2.41,123,45.58,41,19.47,114,48.77,39
30,11.61,33,40.59,47,1.22,134,43.15,52,7.56,59,45.11,46,33.54,34,47.92,46
31,3.24,93,40.51,48,5.03,67,42.34,61,6.51,66,45.99,39,23.48,81,46.88,49
32,20.95,14,40.47,49,3.55,82,44.81,42,14.55,34,47.97,31,31.30,45,52.33,24
33,18.06,19,39.17,52,5.40,64,42.99,53,7.22,61,43.53,58,30.10,54,49.02,37
34,7.46,52,38.74,53,4.30,71,41.88,64,4.33,87,43.22,61,20.18,105,46.32,55
35,30.64,8,38.73,54,14.76,28,41.71,66,13.66,39,42.89,62,39.00,20,44.84,63
36,5.81,62,38.68,55,3.17,88,44.00,46,0.00,222,45.42,43,19.11,122,48.56,42
37,4.74,68,38.45,57,5.76,59,40.06,73,7.22,61,42.22,64,21.21,95,46.37,54
38,5.24,66,37.95,60,0.00,203,43.68,48,6.15,70,44.45,52,21.54,92,46.11,56
39,0.69,141,37.25,62,2.79,96,42.76,57,4.33,87,40.92,69,28.20,60,43.10,70
40,0.59,157,37.23,63,1.22,134,43.19,51,2.02,135,40.43,74,31.47,42,46.55,52
41,15.65,22,36.36,72,12.38,30,41.95,63,11.83,43,40.24,77,30.70,48,41.21,82
42,0.10,184,36.32,73,0.00,203,43.96,47,1.63,148,44.19,53,25.82,68,46.99,48
43,4.65,71,35.83,80,7.17,51,42.36,60,5.80,73,43.69,55,35.48,29,46.58,51
44,3.37,90,35.60,82,2.40,100,40.05,74,3.58,98,41.21,66,4.53,229,40.24,95
45,4.34,74,35.50,83,0.00,203,40.25,72,0.00,222,40.87,72,18.74,129,40.92,88
46,3.95,79,35.50,84,8.53,46,39.70,77,6.51,66,40.88,70,22.85,85,42.19,74
47,5.85,61,35.44,85,4.30,71,38.58,90,19.25,25,40.99,68,28.09,61,41.09,83
48,1.89,109,35.42,86,18.88,20,40.53,69,14.84,32,41.42,65,29.39,56,45.02,62
49,8.03,48,35.14,88,26.30,11,41.63,67,24.17,18,43.41,60,40.09,18,46.41,53
50,4.17,77,33.66,97,24.50,15,48.25,27,26.65,17,48.54,28,44.76,12,49.22,36

In [54]:
y = df_data_21['Rank_2020']

In [55]:
y

0      1
1      2
2      3
3      5
4     12
5      6
6     11
7      4
8      9
9     17
10    10
11    16
12     7
13     8
14    50
15    14
16    59
17    29
18    18
19    21
20    47
21    13
22    23
23    40
24    26
25    58
26    22
27    38
28    19
29    39
30    46
31    49
32    24
33    37
34    55
35    63
36    42
37    54
38    56
39    70
40    52
41    82
42    48
43    51
44    95
45    88
46    74
47    83
48    62
49    53
50    36
Name: Rank_2020, dtype: int64

In [56]:
'''Scikit-learn (Sklearn) is the most useful and robust library for machine learning in Python. 
It provides a selection of efficient tools for machine learning and statistical modeling including classification, 
regression, clustering and dimensionality
reduction via a consistence interface in Python.'''

'Scikit-learn (Sklearn) is the most useful and robust library for machine learning in Python. \nIt provides a selection of efficient tools for machine learning and statistical modeling including classification, \nregression, clustering and dimensionality\nreduction via a consistence interface in Python.'

In [57]:
from sklearn.model_selection import train_test_split#Model_selection is a method for setting a blueprint to analyze data and then using it to measure new data.

X_train, X_test, Y_train, Y_test = train_test_split(X,y, random_state=101, test_size=0.2)

In [58]:
X_train

,infra_2017,placements_2017,academic_2017,Rank_2017,infra_2018,placements_2018,academic_2018,Rank_2018,infra,placements,academic,Rank,infra_2020,placements_2020,academic_2020,Rank_2020
24,18.99,18,43.13,33,23.58,16,50.94,20,27.09,16,51.25,21,42.39,16,51.85,26
7,26.12,12,48.19,9,31.44,9,58.46,8,31.01,12,59.22,8,44.33,13,62.27,4
46,3.95,79,35.50,84,8.53,46,39.70,77,6.51,66,40.88,70,22.85,85,42.19,74
18,20.69,16,44.95,25,15.90,25,51.39,19,20.28,21,52.62,15,44.07,14,54.10,18
3,28.81,9,51.20,5,35.50,6,59.68,6,51.83,4,60.53,6,71.44,2,61.99,5
41,15.65,22,36.36,72,12.38,30,41.95,63,11.83,43,40.24,77,30.70,48,41.21,82
30,11.61,33,40.59,47,1.22,134,43.15,52,7.56,59,45.11,46,33.54,34,47.92,46
15,8.70,47,46.45,21,9.85,42,48.98,26,4.33,87,51.95,17,33.54,34,56.04,14
20,2.48,102,44.42,27,6.11,57,45.44,39,9.59,49,45.57,42,22.20,87,47.10,47
44,3.37,90,35.60,82,2.40,100,40.05,74,3.58,98,41.21,66,4.53,229,40.24,95
38,5.24,66,37.95,60,0.00,203,43.68,48,6.15,70,44.45,52,21.54,92,46.11,56
45,4.34,74,35.50,83,0.00,203,40.25,72,0.00,222,40.87,72,18.74,129,40.92,88
39,0.69,141,37.25,62,2.79,96,42.76,57,4.33,87,40.92,69,28.20,60,43.10,70
10,9.73,42,61.53,12,11.76,33,56.18,12,14.26,37,58.07,12,31.60,41,61.07,10
50,4.17,77,33.66,97,24.50,15,48.25,27,26.65,17,48.54,28,44.76,12,49.22,36
25,4.67,70,42.70,37,14.76,28,42.36,59,19.25,25,44.88,48,28.88,58,45.82,58
33,18.06,19,39.17,52,5.40,64,42.99,53,7.22,61,43.53,58,30.10,54,49.02,37
36,5.81,62,38.68,55,3.17,88,44.00,46,0.00,222,45.42,43,19.11,122,48.56,42
2,44.01,4,51.46,3,43.62,4,63.52,3,47.28,5,64.55,3,53.99,6,63.15,3
27,1.94,108,41.48,42,2.01,115,43.44,49,6.51,66,44.88,49,37.00,27,48.84,38
34,7.46,52,38.74,53,4.30,71,41.88,64,4.33,87,43.22,61,20.18,105,46.32,55
35,30.64,8,38.73,54,14.76,28,41.71,66,13.66,39,42.89,62,39.00,20,44.84,63
8,11.20,35,46.72,10,15.04,26,58.24,9,16.55,28,58.40,10,44.99,11,61.13,9
19,1.87,110,44.84,26,2.01,115,50.31,23,6.86,64,51.73,18,23.16,83,52.60,21
29,11.08,38,41.30,44,4.30,71,44.34,45,2.41,123,45.58,41,19.47,114,48.77,39
12,17.15,20,56.50,16,26.30,11,53.38,14,37.39,7,60.87,5,47.99,9,61.53,7
5,27.06,11,48.84,7,21.66,19,60.54,5,36.71,8,61.85,4,58.32,5,61.70,6
0,83.33,1,52.74,1,100.00,1,82.16,1,100.00,1,82.28,1,100.00,1,84.18,1
28,20.72,15,41.38,43,9.53,43,50.39,22,14.55,34,52.11,16,39.82,19,53.82,19
42,0.10,184,36.32,73,0.00,203,43.96,47,1.63,148,44.19,53,25.82,68,46.99,48
4,43.94,5,48.90,6,63.22,2,62.82,4,62.72,2,60.35,7,65.89,4,58.71,12
40,0.59,157,37.23,63,1.22,134,43.19,51,2.02,135,40.43,74,31.47,42,46.55,52
13,27.67,10,55.37,18,26.30,11,57.37,11,30.21,14,58.50,9,43.95,15,61.51,8
9,16.62,21,83.28,11,26.30,11,57.78,10,18.46,27,58.36,11,38.99,23,54.30,17
49,8.03,48,35.14,88,26.30,11,41.63,67,24.17,18,43.41,60,40.09,18,46.41,53
23,7.09,54,43.78,30,10.82,37,48.00,29,15.71,31,48.47,29,34.88,30,48.77,40
6,30.76,7,48.27,8,33.15,8,58.69,7,41.11,6,57.59,13,53.44,7,60.10,11
17,11.16,36,45.52,23,5.76,59,48.02,28,9.26,50,49.86,26,39.00,20,51.15,29
11,32.95,6,58.25,14,36.71,5,52.68,16,35.31,9,51.44,19,49.00,8,55.22,16
31,3.24,93,40.51,48,5.03,67,42.34,61,6.51,66,45.99,39,23.48,81,46.88,49

In [59]:
X_test

,infra_2017,placements_2017,academic_2017,Rank_2017,infra_2018,placements_2018,academic_2018,Rank_2018,infra,placements,academic,Rank,infra_2020,placements_2020,academic_2020,Rank_2020
37,4.74,68,38.45,57,5.76,59,40.06,73,7.22,61,42.22,64,21.21,95,46.37,54
14,4.71,69,54.70,19,5.03,67,47.62,31,11.52,44,46.27,37,19.30,121,46.84,50
21,9.11,45,44.29,28,22.63,17,55.08,13,31.20,11,57.23,14,37.18,26,58.30,13
32,20.95,14,40.47,49,3.55,82,44.81,42,14.55,34,47.97,31,31.30,45,52.33,24
22,0.89,132,43.95,29,7.17,51,47.72,30,8.59,51,51.21,22,21.54,92,52.35,23
1,47.27,3,51.75,2,46.28,3,67.57,2,55.27,3,68.68,2,67.24,3,70.16,2
26,10.82,40,41.85,41,26.52,10,51.52,18,30.01,15,51.34,20,38.30,24,52.55,22
47,5.85,61,35.44,85,4.30,71,38.58,90,19.25,25,40.99,68,28.09,61,41.09,83
43,4.65,71,35.83,80,7.17,51,42.36,60,5.80,73,43.69,55,35.48,29,46.58,51
48,1.89,109,35.42,86,18.88,20,40.53,69,14.84,32,41.42,65,29.39,56,45.02,62
16,3.79,84,46.45,22,2.40,100,50.74,21,3.19,103,46.32,36,21.87,89,45.67,59

In [60]:
Y_train

24    26
7      4
46    74
18    18
3      5
41    82
30    46
15    14
20    47
44    95
38    56
45    88
39    70
10    10
50    36
25    58
33    37
36    42
2      3
27    38
34    55
35    63
8      9
19    21
29    39
12     7
5      6
0      1
28    19
42    48
4     12
40    52
13     8
9     17
49    53
23    40
6     11
17    29
11    16
31    49
Name: Rank_2020, dtype: int64

In [61]:
Y_test

37    54
14    50
21    13
32    24
22    23
1      2
26    22
47    83
43    51
48    62
16    59
Name: Rank_2020, dtype: int64

In [62]:
from sklearn.preprocessing import StandardScaler #StandardScaler removes the mean and scales each feature/variable to unit variance.
sc = StandardScaler()

In [63]:
X_train_std = sc.fit_transform(X_train) #fit_transform() is used on the training data so that we can scale the training data and also learn the scaling parameters of that data

In [64]:
X_train_std

array([[ 0.20029778, -0.71698295, -0.17055939, -0.20645521,  0.33052814,
        -0.71686865,  0.14545823, -0.62554637,  0.37337917, -0.71320433,
         0.07921728, -0.54147869,  0.28647765, -0.64612339, -0.05366511,
        -0.35936112],
       [ 0.64690028, -0.85120753,  0.37800601, -1.09126324,  0.737141  ,
        -0.84177421,  1.00337657, -1.13446545,  0.56933543, -0.78808142,
         0.98797834, -1.08295737,  0.40157299, -0.71041428,  1.17532486,
        -1.22814625],
       [-0.74176417,  0.64763359, -0.99774398,  1.67376187, -0.44803719,
        -0.18155914, -1.13685588,  1.79181926, -0.65539122,  0.22275936,
        -1.1031983 ,  1.49947944, -0.87278162,  0.83256696, -1.19301666,
         1.53617007],
       [ 0.30678084, -0.76172448,  0.02675069, -0.50139122, -0.06677297,
        -0.5562758 ,  0.19679643, -0.66795629,  0.03295514, -0.61960796,
         0.23542841, -0.79139193,  0.38614784, -0.68898398,  0.2117118 ,
        -0.67528299],
       [ 0.81539408, -0.91831982,  0.70432654, -1.23873125,  0.94717258,
        -0.89530516,  1.14256013, -1.21928529,  1.61010314, -0.93783561,
         1.1373481 , -1.16626178,  2.0099414 , -0.94614752,  1.14230018,
        -1.18865602],
       [-0.00891013, -0.6274999 , -0.90450954,  1.23135785, -0.24886931,
        -0.46705755, -0.88016489,  1.19808033, -0.38945058, -0.20778394,
        -1.17617283,  1.79104488, -0.40706078,  0.03964605, -1.30860304,
         1.85209193],
       [-0.261964  , -0.38142151, -0.44592621,  0.30968281, -0.82619749,
         1.38868209, -0.74326303,  0.73157118, -0.60290294,  0.09172444,
        -0.6208822 ,  0.49982648, -0.23857069, -0.26037808, -0.51719012,
         0.43044354],
       [-0.44423795, -0.06823083,  0.1893689 , -0.64885923, -0.37975106,
        -0.25293374, -0.07814815, -0.37108683, -0.7643669 ,  0.6158641 ,
         0.15903318, -0.70808751, -0.23857069, -0.26037808,  0.44052568,
        -0.83324392],
       [-0.8338407 ,  1.16216113, -0.03070774, -0.42765722, -0.57322843,
         0.01472101, -0.48200864,  0.18024217, -0.50142559, -0.0954683 ,
        -0.56843175,  0.33321765, -0.91134449,  0.87542755, -0.61390526,
         0.46993377],
       [-0.77809368,  0.89371198, -0.98690276,  1.60002786, -0.76515383,
         0.78199798, -1.09692617,  1.66458949, -0.80185853,  0.82177612,
        -1.0655708 ,  1.33287061, -1.95966134,  3.91852943, -1.42300998,
         2.36546496],
       [-0.66096231,  0.35681367, -0.73213425,  0.78895383, -0.88931043,
         2.61989396, -0.68279804,  0.56193148, -0.67338721,  0.29763645,
        -0.69613719,  0.74973972, -0.95050064,  0.98257902, -0.7306711 ,
         0.82534587],
       [-0.7173357 ,  0.53577977, -0.99774398,  1.63689486, -0.88931043,
         2.61989396, -1.0741092 ,  1.57976964, -0.98081859,  3.14296605,
        -1.10433852,  1.58278385, -1.11661763,  1.77549994, -1.34280718,
         2.08903333],
       [-0.9459611 ,  2.03462088, -0.80802274,  0.86268783, -0.74497839,
         0.71062338, -0.78775613,  0.94362079, -0.7643669 ,  0.6158641 ,
        -1.09863739,  1.45782723, -0.55537952,  0.29680958, -1.08568644,
         1.37820914],
       [-0.37972174, -0.18008464,  1.82422389, -0.98066224, -0.2809431 ,
        -0.4135266 ,  0.74326303, -0.96482575, -0.26797769, -0.32009958,
         0.85685221, -0.91634855, -0.35366603, -0.11036602,  1.03379051,
        -0.99120485],
       [-0.72798401,  0.60289206, -1.19722231,  2.15303288,  0.37812151,
        -0.7347123 , -0.16143011, -0.3286769 ,  0.35138407, -0.69448505,
        -0.22978428, -0.24991324,  0.42708381, -0.73184457, -0.36386123,
         0.03554121],
       [-0.69666546,  0.44629672, -0.21717661, -0.0589872 , -0.12574735,
        -0.50274485, -0.83339009,  1.02844064, -0.01853336, -0.54473086,
        -0.64710743,  0.58313089, -0.51503682,  0.253949  , -0.76487524,
         0.90432634],
       [ 0.14204528, -0.69461219, -0.59987144,  0.49401782, -0.60995809,
         0.13962656, -0.76151661,  0.7739811 , -0.61989914,  0.12916299,
        -0.80103809,  0.99965296, -0.44265728,  0.16822782, -0.38745029,
         0.07503144],
       [-0.62525917,  0.26733062, -0.65299339,  0.60461882, -0.72532026,
         0.56787417, -0.64629088,  0.47711164, -0.98081859,  3.14296605,
        -0.58553516,  0.37486986, -1.09466646,  1.62548787, -0.44170513,
         0.27248261],
       [ 1.76747796, -1.03017363,  0.73251369, -1.31246525,  1.36723574,
        -0.93099246,  1.58064609, -1.34651506,  1.38265391, -0.91911634,
         1.59571942, -1.2912184 ,  0.9746766 , -0.86042634,  1.27911672,
        -1.26763648],
       [-0.86766473,  1.29638571, -0.34943941,  0.1253478 , -0.78532928,
         1.04965273, -0.71017841,  0.60434141, -0.65539122,  0.22275936,
        -0.64710743,  0.6247831 , -0.03329756, -0.41039015, -0.40868045,
         0.11452168],
       [-0.52190796,  0.04362299, -0.64648866,  0.53088482, -0.66686319,
         0.26453212, -0.88815083,  1.24049025, -0.7643669 ,  0.6158641 ,
        -0.83638514,  1.12460958, -1.03118604,  1.26117286, -0.70590259,
         0.78585564],
       [ 0.93001996, -0.94069058, -0.64757278,  0.56775182, -0.12574735,
        -0.50274485, -0.90754526,  1.3253101 , -0.297971  , -0.28266103,
        -0.87401263,  1.16626178,  0.08535743, -0.56040221, -0.88046162,
         1.1017775 ],
       [-0.28764521, -0.33667998,  0.21864017, -1.05439624, -0.11126242,
        -0.53843215,  0.97827789, -1.09205552, -0.15350324, -0.48857304,
         0.89447971, -0.99965296,  0.44072913, -0.75327487,  1.04086723,
        -1.03069508],
       [-0.87204933,  1.34112723,  0.01482536, -0.46452422, -0.78532928,
         1.04965273,  0.07358475, -0.4983166 , -0.63789513,  0.18532081,
         0.13394819, -0.66643531, -0.8543901 ,  0.78970637,  0.03479386,
        -0.55681229],
       [-0.29516166, -0.26956769, -0.3689536 ,  0.19908181, -0.66686319,
         0.26453212, -0.60750202,  0.43470171, -0.86034548,  1.28975796,
        -0.56729152,  0.29156545, -1.07330856,  1.45404551, -0.41693662,
         0.15401191],
       [ 0.08504552, -0.67224142,  1.27891085, -0.83319423,  0.47123895,
        -0.8060869 ,  0.42382535, -0.88000591,  0.88826425, -0.88167779,
         1.17611582, -1.20791399,  0.61871162, -0.79613546,  1.08804534,
        -1.10967555],
       [ 0.70577915, -0.87357829,  0.4484739 , -1.16499725,  0.23120286,
        -0.6633377 ,  1.24067313, -1.26169522,  0.85427184, -0.86295852,
         1.28785809, -1.2495662 ,  1.23156465, -0.88185664,  1.10809604,
        -1.14916578],
       [ 4.23036863, -1.09728592,  0.87128122, -1.38619925,  4.28388115,
        -0.98452341,  3.70718836, -1.43133491,  4.01806571, -0.99399343,
         3.6173422 , -1.37452282,  3.70433468, -0.96757782,  3.75950627,
        -1.34661695],
       [ 0.30865996, -0.78409524, -0.36028063,  0.16221481, -0.39630527,
        -0.23509009,  0.08271154, -0.54072652, -0.25348093, -0.3762574 ,
         0.17727682, -0.74973972,  0.13400598, -0.58183251,  0.17868712,
        -0.63579275],
       [-0.98291699,  2.99656369, -0.90884603,  1.26822485, -0.88931043,
         2.61989396, -0.65085427,  0.51952156, -0.89933678,  1.7577398 ,
        -0.7257831 ,  0.79139193, -0.69657896,  0.46825194, -0.62687924,
         0.50942401],
       [ 1.76309336, -1.00780287,  0.45497863, -1.20186425,  2.38118128,
        -0.96667976,  1.50078667, -1.30410514,  2.15448164, -0.97527416,
         1.11682401, -1.12460958,  1.6806738 , -0.90328693,  0.75543961,
        -0.91222438],
       [-0.95222481,  2.39255309, -0.81019099,  0.89955484, -0.82619749,
         1.38868209, -0.73869963,  0.68916125, -0.87984113,  1.51438924,
        -1.15450852,  1.66608826, -0.36137861, -0.08893572, -0.67877517,
         0.66738494],
       [ 0.74398778, -0.89594905,  1.15640514, -0.75946023,  0.47123895,
        -0.8060869 ,  0.87902404, -1.00723568,  0.52934436, -0.75064288,
         0.90588198, -1.04130517,  0.37902854, -0.66755369,  1.08568644,
        -1.07018532],
       [ 0.05184786, -0.64987066,  4.18218782, -1.01752924,  0.47123895,
        -0.8060869 ,  0.92579885, -1.0496456 , -0.05802455, -0.50729232,
         0.8899188 , -0.95800075,  0.08476416, -0.49611133,  0.23530086,
        -0.71477322],
       [-0.48620481, -0.04586006, -1.03677235,  1.82122987,  0.47123895,
        -0.8060869 , -0.91667206,  1.36772002,  0.22741174, -0.67576578,
        -0.81472082,  1.08295737,  0.1500244 , -0.6032628 , -0.69528751,
         0.70687517],
       [-0.54508368,  0.08836451, -0.1000915 , -0.31705621, -0.3295711 ,
        -0.342152  , -0.18995133, -0.24385706, -0.19549387, -0.43241522,
        -0.23776587, -0.20826103, -0.15907185, -0.34609926, -0.41693662,
         0.19350214],
       [ 0.93753642, -0.96306134,  0.38667898, -1.12813024,  0.82560258,
        -0.85961786,  1.02961609, -1.17687537,  1.07422274, -0.90039706,
         0.80212131, -0.87469634,  0.94204647, -0.83899605,  0.91938357,
        -0.95171462],
       [-0.29015069, -0.31430922,  0.08854561, -0.57512522, -0.5913346 ,
         0.05040831, -0.18766964, -0.28626698, -0.51792191, -0.07674902,
        -0.07927429, -0.33321765,  0.08535743, -0.56040221, -0.13622682,
        -0.24089042],
       [ 1.07471166, -0.9854321 ,  1.46863209, -0.90692824,  1.0097682 ,
        -0.91314881,  0.34396593, -0.79518606,  0.78428745, -0.84423924,
         0.1008816 , -0.6247831 ,  0.67863239, -0.81756575,  0.34381053,
        -0.75426345],
       [-0.78623651,  0.96082427, -0.45459918,  0.34654981, -0.62909889,
         0.19315752, -0.83567179,  1.11326048, -0.65539122,  0.22275936,
        -0.52054221,  0.20826103, -0.8354053 ,  0.74684578, -0.63985322,
         0.54891424]])

In [65]:
X_test_std = sc.transform(X_test)

In [66]:
X_test_std

array([[-0.69228086,  0.40155519, -0.67792818,  0.67835283, -0.5913346 ,
         0.05040831, -1.09578533,  1.62217956, -0.61989914,  0.12916299,
        -0.95040785,  1.2495662 , -0.97007872,  1.04686991, -0.70000532,
         0.74636541],
       [-0.69415997,  0.42392596,  1.08376901, -0.72259323, -0.62909889,
         0.19315752, -0.23330359, -0.15903721, -0.40494712, -0.18906466,
        -0.48861585,  0.12495662, -1.08339423,  1.60405758, -0.64457104,
         0.58840447],
       [-0.41855674, -0.11297235, -0.04480131, -0.39079022,  0.28138282,
        -0.699025  ,  0.61776966, -0.92241583,  0.57883331, -0.8068007 ,
         0.76107313, -0.83304413, -0.02261861, -0.43182044,  0.70708204,
        -0.87273415],
       [ 0.32306649, -0.806466  , -0.45893567,  0.38341682, -0.70566213,
         0.46081227, -0.55388212,  0.30747194, -0.25348093, -0.3762574 ,
        -0.29477723, -0.12495662, -0.37146428, -0.02464484,  0.00294863,
        -0.43834159],
       [-0.93343369,  1.83328402, -0.08166144, -0.35392321, -0.5183926 ,
        -0.09234089, -0.2218951 , -0.20144714, -0.55141443, -0.05802975,
         0.07465637, -0.49982648, -0.95050064,  0.98257902,  0.00530754,
        -0.47783182],
       [ 1.97167489, -1.05254439,  0.76395321, -1.34933225,  1.50484263,
        -0.94883611,  2.04268988, -1.38892499,  1.78206476, -0.95655489,
         2.06663325, -1.33287061,  1.76076591, -0.92471723,  2.10591324,
        -1.30712672],
       [-0.31144731, -0.22482617, -0.30932692,  0.0884808 ,  0.48261998,
        -0.82393056,  0.21162746, -0.71036621,  0.51934659, -0.7319236 ,
         0.08947933, -0.58313089,  0.04382819, -0.47468103,  0.0288966 ,
        -0.51732205],
       [-0.62275368,  0.24495985, -1.00424871,  1.71062887, -0.66686319,
         0.26453212, -1.26463096,  2.34314826, -0.01853336, -0.54473086,
        -1.0906558 ,  1.41617502, -0.56190554,  0.31823988, -1.32275648,
         1.89158217],
       [-0.6979182 ,  0.46866748, -0.96196797,  1.52629386, -0.5183926 ,
        -0.09234089, -0.83339009,  1.07085056, -0.6908833 ,  0.35379427,
        -0.78279446,  0.87469634, -0.12347535, -0.36752956, -0.67523681,
         0.62789471],
       [-0.87079659,  1.31875647, -1.00641695,  1.74749587,  0.08738814,
        -0.64549405, -1.04216543,  1.45253987, -0.23898416, -0.41369595,
        -1.04162603,  1.2912184 , -0.4847798 ,  0.21108841, -0.85923147,
         1.06228727],
       [-0.7517861 ,  0.7594874 ,  0.1893689 , -0.61199222, -0.76515383,
         0.78199798,  0.12264125, -0.58313644, -0.82135418,  0.91537248,
        -0.48291471,  0.08330441, -0.93092257,  0.91828814, -0.78256703,
         0.94381657]])

In [67]:
import joblib

In [68]:
joblib.dump(sc,r'C:\Users\Narasimha Reddy\OneDrive\Desktop\sih\model\sc.sav')

['C:\\Users\\Narasimha Reddy\\OneDrive\\Desktop\\sih\\model\\sc.sav']

In [69]:
X_train_std

array([[ 0.20029778, -0.71698295, -0.17055939, -0.20645521,  0.33052814,
        -0.71686865,  0.14545823, -0.62554637,  0.37337917, -0.71320433,
         0.07921728, -0.54147869,  0.28647765, -0.64612339, -0.05366511,
        -0.35936112],
       [ 0.64690028, -0.85120753,  0.37800601, -1.09126324,  0.737141  ,
        -0.84177421,  1.00337657, -1.13446545,  0.56933543, -0.78808142,
         0.98797834, -1.08295737,  0.40157299, -0.71041428,  1.17532486,
        -1.22814625],
       [-0.74176417,  0.64763359, -0.99774398,  1.67376187, -0.44803719,
        -0.18155914, -1.13685588,  1.79181926, -0.65539122,  0.22275936,
        -1.1031983 ,  1.49947944, -0.87278162,  0.83256696, -1.19301666,
         1.53617007],
       [ 0.30678084, -0.76172448,  0.02675069, -0.50139122, -0.06677297,
        -0.5562758 ,  0.19679643, -0.66795629,  0.03295514, -0.61960796,
         0.23542841, -0.79139193,  0.38614784, -0.68898398,  0.2117118 ,
        -0.67528299],
       [ 0.81539408, -0.91831982,  0.70432654, -1.23873125,  0.94717258,
        -0.89530516,  1.14256013, -1.21928529,  1.61010314, -0.93783561,
         1.1373481 , -1.16626178,  2.0099414 , -0.94614752,  1.14230018,
        -1.18865602],
       [-0.00891013, -0.6274999 , -0.90450954,  1.23135785, -0.24886931,
        -0.46705755, -0.88016489,  1.19808033, -0.38945058, -0.20778394,
        -1.17617283,  1.79104488, -0.40706078,  0.03964605, -1.30860304,
         1.85209193],
       [-0.261964  , -0.38142151, -0.44592621,  0.30968281, -0.82619749,
         1.38868209, -0.74326303,  0.73157118, -0.60290294,  0.09172444,
        -0.6208822 ,  0.49982648, -0.23857069, -0.26037808, -0.51719012,
         0.43044354],
       [-0.44423795, -0.06823083,  0.1893689 , -0.64885923, -0.37975106,
        -0.25293374, -0.07814815, -0.37108683, -0.7643669 ,  0.6158641 ,
         0.15903318, -0.70808751, -0.23857069, -0.26037808,  0.44052568,
        -0.83324392],
       [-0.8338407 ,  1.16216113, -0.03070774, -0.42765722, -0.57322843,
         0.01472101, -0.48200864,  0.18024217, -0.50142559, -0.0954683 ,
        -0.56843175,  0.33321765, -0.91134449,  0.87542755, -0.61390526,
         0.46993377],
       [-0.77809368,  0.89371198, -0.98690276,  1.60002786, -0.76515383,
         0.78199798, -1.09692617,  1.66458949, -0.80185853,  0.82177612,
        -1.0655708 ,  1.33287061, -1.95966134,  3.91852943, -1.42300998,
         2.36546496],
       [-0.66096231,  0.35681367, -0.73213425,  0.78895383, -0.88931043,
         2.61989396, -0.68279804,  0.56193148, -0.67338721,  0.29763645,
        -0.69613719,  0.74973972, -0.95050064,  0.98257902, -0.7306711 ,
         0.82534587],
       [-0.7173357 ,  0.53577977, -0.99774398,  1.63689486, -0.88931043,
         2.61989396, -1.0741092 ,  1.57976964, -0.98081859,  3.14296605,
        -1.10433852,  1.58278385, -1.11661763,  1.77549994, -1.34280718,
         2.08903333],
       [-0.9459611 ,  2.03462088, -0.80802274,  0.86268783, -0.74497839,
         0.71062338, -0.78775613,  0.94362079, -0.7643669 ,  0.6158641 ,
        -1.09863739,  1.45782723, -0.55537952,  0.29680958, -1.08568644,
         1.37820914],
       [-0.37972174, -0.18008464,  1.82422389, -0.98066224, -0.2809431 ,
        -0.4135266 ,  0.74326303, -0.96482575, -0.26797769, -0.32009958,
         0.85685221, -0.91634855, -0.35366603, -0.11036602,  1.03379051,
        -0.99120485],
       [-0.72798401,  0.60289206, -1.19722231,  2.15303288,  0.37812151,
        -0.7347123 , -0.16143011, -0.3286769 ,  0.35138407, -0.69448505,
        -0.22978428, -0.24991324,  0.42708381, -0.73184457, -0.36386123,
         0.03554121],
       [-0.69666546,  0.44629672, -0.21717661, -0.0589872 , -0.12574735,
        -0.50274485, -0.83339009,  1.02844064, -0.01853336, -0.54473086,
        -0.64710743,  0.58313089, -0.51503682,  0.253949  , -0.76487524,
         0.90432634],
       [ 0.14204528, -0.69461219, -0.59987144,  0.49401782, -0.60995809,
         0.13962656, -0.76151661,  0.7739811 , -0.61989914,  0.12916299,
        -0.80103809,  0.99965296, -0.44265728,  0.16822782, -0.38745029,
         0.07503144],
       [-0.62525917,  0.26733062, -0.65299339,  0.60461882, -0.72532026,
         0.56787417, -0.64629088,  0.47711164, -0.98081859,  3.14296605,
        -0.58553516,  0.37486986, -1.09466646,  1.62548787, -0.44170513,
         0.27248261],
       [ 1.76747796, -1.03017363,  0.73251369, -1.31246525,  1.36723574,
        -0.93099246,  1.58064609, -1.34651506,  1.38265391, -0.91911634,
         1.59571942, -1.2912184 ,  0.9746766 , -0.86042634,  1.27911672,
        -1.26763648],
       [-0.86766473,  1.29638571, -0.34943941,  0.1253478 , -0.78532928,
         1.04965273, -0.71017841,  0.60434141, -0.65539122,  0.22275936,
        -0.64710743,  0.6247831 , -0.03329756, -0.41039015, -0.40868045,
         0.11452168],
       [-0.52190796,  0.04362299, -0.64648866,  0.53088482, -0.66686319,
         0.26453212, -0.88815083,  1.24049025, -0.7643669 ,  0.6158641 ,
        -0.83638514,  1.12460958, -1.03118604,  1.26117286, -0.70590259,
         0.78585564],
       [ 0.93001996, -0.94069058, -0.64757278,  0.56775182, -0.12574735,
        -0.50274485, -0.90754526,  1.3253101 , -0.297971  , -0.28266103,
        -0.87401263,  1.16626178,  0.08535743, -0.56040221, -0.88046162,
         1.1017775 ],
       [-0.28764521, -0.33667998,  0.21864017, -1.05439624, -0.11126242,
        -0.53843215,  0.97827789, -1.09205552, -0.15350324, -0.48857304,
         0.89447971, -0.99965296,  0.44072913, -0.75327487,  1.04086723,
        -1.03069508],
       [-0.87204933,  1.34112723,  0.01482536, -0.46452422, -0.78532928,
         1.04965273,  0.07358475, -0.4983166 , -0.63789513,  0.18532081,
         0.13394819, -0.66643531, -0.8543901 ,  0.78970637,  0.03479386,
        -0.55681229],
       [-0.29516166, -0.26956769, -0.3689536 ,  0.19908181, -0.66686319,
         0.26453212, -0.60750202,  0.43470171, -0.86034548,  1.28975796,
        -0.56729152,  0.29156545, -1.07330856,  1.45404551, -0.41693662,
         0.15401191],
       [ 0.08504552, -0.67224142,  1.27891085, -0.83319423,  0.47123895,
        -0.8060869 ,  0.42382535, -0.88000591,  0.88826425, -0.88167779,
         1.17611582, -1.20791399,  0.61871162, -0.79613546,  1.08804534,
        -1.10967555],
       [ 0.70577915, -0.87357829,  0.4484739 , -1.16499725,  0.23120286,
        -0.6633377 ,  1.24067313, -1.26169522,  0.85427184, -0.86295852,
         1.28785809, -1.2495662 ,  1.23156465, -0.88185664,  1.10809604,
        -1.14916578],
       [ 4.23036863, -1.09728592,  0.87128122, -1.38619925,  4.28388115,
        -0.98452341,  3.70718836, -1.43133491,  4.01806571, -0.99399343,
         3.6173422 , -1.37452282,  3.70433468, -0.96757782,  3.75950627,
        -1.34661695],
       [ 0.30865996, -0.78409524, -0.36028063,  0.16221481, -0.39630527,
        -0.23509009,  0.08271154, -0.54072652, -0.25348093, -0.3762574 ,
         0.17727682, -0.74973972,  0.13400598, -0.58183251,  0.17868712,
        -0.63579275],
       [-0.98291699,  2.99656369, -0.90884603,  1.26822485, -0.88931043,
         2.61989396, -0.65085427,  0.51952156, -0.89933678,  1.7577398 ,
        -0.7257831 ,  0.79139193, -0.69657896,  0.46825194, -0.62687924,
         0.50942401],
       [ 1.76309336, -1.00780287,  0.45497863, -1.20186425,  2.38118128,
        -0.96667976,  1.50078667, -1.30410514,  2.15448164, -0.97527416,
         1.11682401, -1.12460958,  1.6806738 , -0.90328693,  0.75543961,
        -0.91222438],
       [-0.95222481,  2.39255309, -0.81019099,  0.89955484, -0.82619749,
         1.38868209, -0.73869963,  0.68916125, -0.87984113,  1.51438924,
        -1.15450852,  1.66608826, -0.36137861, -0.08893572, -0.67877517,
         0.66738494],
       [ 0.74398778, -0.89594905,  1.15640514, -0.75946023,  0.47123895,
        -0.8060869 ,  0.87902404, -1.00723568,  0.52934436, -0.75064288,
         0.90588198, -1.04130517,  0.37902854, -0.66755369,  1.08568644,
        -1.07018532],
       [ 0.05184786, -0.64987066,  4.18218782, -1.01752924,  0.47123895,
        -0.8060869 ,  0.92579885, -1.0496456 , -0.05802455, -0.50729232,
         0.8899188 , -0.95800075,  0.08476416, -0.49611133,  0.23530086,
        -0.71477322],
       [-0.48620481, -0.04586006, -1.03677235,  1.82122987,  0.47123895,
        -0.8060869 , -0.91667206,  1.36772002,  0.22741174, -0.67576578,
        -0.81472082,  1.08295737,  0.1500244 , -0.6032628 , -0.69528751,
         0.70687517],
       [-0.54508368,  0.08836451, -0.1000915 , -0.31705621, -0.3295711 ,
        -0.342152  , -0.18995133, -0.24385706, -0.19549387, -0.43241522,
        -0.23776587, -0.20826103, -0.15907185, -0.34609926, -0.41693662,
         0.19350214],
       [ 0.93753642, -0.96306134,  0.38667898, -1.12813024,  0.82560258,
        -0.85961786,  1.02961609, -1.17687537,  1.07422274, -0.90039706,
         0.80212131, -0.87469634,  0.94204647, -0.83899605,  0.91938357,
        -0.95171462],
       [-0.29015069, -0.31430922,  0.08854561, -0.57512522, -0.5913346 ,
         0.05040831, -0.18766964, -0.28626698, -0.51792191, -0.07674902,
        -0.07927429, -0.33321765,  0.08535743, -0.56040221, -0.13622682,
        -0.24089042],
       [ 1.07471166, -0.9854321 ,  1.46863209, -0.90692824,  1.0097682 ,
        -0.91314881,  0.34396593, -0.79518606,  0.78428745, -0.84423924,
         0.1008816 , -0.6247831 ,  0.67863239, -0.81756575,  0.34381053,
        -0.75426345],
       [-0.78623651,  0.96082427, -0.45459918,  0.34654981, -0.62909889,
         0.19315752, -0.83567179,  1.11326048, -0.65539122,  0.22275936,
        -0.52054221,  0.20826103, -0.8354053 ,  0.74684578, -0.63985322,
         0.54891424]])

In [70]:
X_test_std

array([[-0.69228086,  0.40155519, -0.67792818,  0.67835283, -0.5913346 ,
         0.05040831, -1.09578533,  1.62217956, -0.61989914,  0.12916299,
        -0.95040785,  1.2495662 , -0.97007872,  1.04686991, -0.70000532,
         0.74636541],
       [-0.69415997,  0.42392596,  1.08376901, -0.72259323, -0.62909889,
         0.19315752, -0.23330359, -0.15903721, -0.40494712, -0.18906466,
        -0.48861585,  0.12495662, -1.08339423,  1.60405758, -0.64457104,
         0.58840447],
       [-0.41855674, -0.11297235, -0.04480131, -0.39079022,  0.28138282,
        -0.699025  ,  0.61776966, -0.92241583,  0.57883331, -0.8068007 ,
         0.76107313, -0.83304413, -0.02261861, -0.43182044,  0.70708204,
        -0.87273415],
       [ 0.32306649, -0.806466  , -0.45893567,  0.38341682, -0.70566213,
         0.46081227, -0.55388212,  0.30747194, -0.25348093, -0.3762574 ,
        -0.29477723, -0.12495662, -0.37146428, -0.02464484,  0.00294863,
        -0.43834159],
       [-0.93343369,  1.83328402, -0.08166144, -0.35392321, -0.5183926 ,
        -0.09234089, -0.2218951 , -0.20144714, -0.55141443, -0.05802975,
         0.07465637, -0.49982648, -0.95050064,  0.98257902,  0.00530754,
        -0.47783182],
       [ 1.97167489, -1.05254439,  0.76395321, -1.34933225,  1.50484263,
        -0.94883611,  2.04268988, -1.38892499,  1.78206476, -0.95655489,
         2.06663325, -1.33287061,  1.76076591, -0.92471723,  2.10591324,
        -1.30712672],
       [-0.31144731, -0.22482617, -0.30932692,  0.0884808 ,  0.48261998,
        -0.82393056,  0.21162746, -0.71036621,  0.51934659, -0.7319236 ,
         0.08947933, -0.58313089,  0.04382819, -0.47468103,  0.0288966 ,
        -0.51732205],
       [-0.62275368,  0.24495985, -1.00424871,  1.71062887, -0.66686319,
         0.26453212, -1.26463096,  2.34314826, -0.01853336, -0.54473086,
        -1.0906558 ,  1.41617502, -0.56190554,  0.31823988, -1.32275648,
         1.89158217],
       [-0.6979182 ,  0.46866748, -0.96196797,  1.52629386, -0.5183926 ,
        -0.09234089, -0.83339009,  1.07085056, -0.6908833 ,  0.35379427,
        -0.78279446,  0.87469634, -0.12347535, -0.36752956, -0.67523681,
         0.62789471],
       [-0.87079659,  1.31875647, -1.00641695,  1.74749587,  0.08738814,
        -0.64549405, -1.04216543,  1.45253987, -0.23898416, -0.41369595,
        -1.04162603,  1.2912184 , -0.4847798 ,  0.21108841, -0.85923147,
         1.06228727],
       [-0.7517861 ,  0.7594874 ,  0.1893689 , -0.61199222, -0.76515383,
         0.78199798,  0.12264125, -0.58313644, -0.82135418,  0.91537248,
        -0.48291471,  0.08330441, -0.93092257,  0.91828814, -0.78256703,
         0.94381657]])

In [71]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)
regressor.fit(X_train, Y_train)

RandomForestRegressor(random_state=0)

In [72]:
y_pred = regressor.predict(X_test)

In [73]:
y_pred

array([58.69, 45.94, 13.74, 32.65, 27.3 ,  3.24, 22.94, 81.69, 52.01,
       65.16, 47.59])

In [74]:
from sklearn.metrics import r2_score

In [75]:
r2_score(Y_test,y_pred)

0.9548662721281438

In [76]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 51 entries, 0 to 50
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   infra_2017       51 non-null     float64
 1   placements_2017  51 non-null     int64
 2   academic_2017    51 non-null     float64
 3   Rank_2017        51 non-null     int64
 4   infra_2018       51 non-null     float64
 5   placements_2018  51 non-null     int64
 6   academic_2018    51 non-null     float64
 7   Rank_2018        51 non-null     int64
 8   infra            51 non-null     float64
 9   placements       51 non-null     int64
 10  academic         51 non-null     float64
 11  Rank             51 non-null     int64
 12  infra_2020       51 non-null     float64
 13  placements_2020  51 non-null     int64
 14  academic_2020    51 non-null     float64
 15  Rank_2020        51 non-null     int64
dtypes: float64(8), int64(8)
memory usage: 6.8 KB

In [77]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, Y_train)

DecisionTreeRegressor(random_state=0)

In [78]:
y_pred_d = regressor.predict(X_test)

In [79]:
from sklearn.metrics import r2_score
r2_score(Y_test, y_pred_d)

0.9370954871885806

In [80]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, Y_train)

SVR()

In [81]:
y_pred_s = regressor.predict(X_test)

In [82]:
from sklearn.metrics import r2_score
r2_score(Y_test, y_pred_s)

0.3052950807847169

In [83]:
joblib.dump(regressor,r'C:\Users\Narasimha Reddy\OneDrive\Desktop\sih\model\dcr.sav')

['C:\\Users\\Narasimha Reddy\\OneDrive\\Desktop\\sih\\model\\dcr.sav']

In [84]:
model= joblib.load(r'C:\Users\Narasimha Reddy\OneDrive\Desktop\sih\model\dcr.sav')

In [85]:
model.predict(X_test)

array([40.43576755, 37.35347151, 26.58807389, 33.23014649, 36.76106159,
       24.17608777, 27.62572918, 39.92449196, 38.56433022, 39.07968852,
       38.70428459])

In [86]:
yy = model.predict(X)

In [87]:
from sklearn.metrics import r2_score
r2_score(y, yy)

0.3366815515840339

In [88]:
model.predict(X)

array([29.63354997, 24.17608777, 23.72363825, 23.82118578, 24.68552021,
       23.64617382, 23.70655242, 23.73357102, 25.43086302, 25.43423792,
       27.59998052, 24.33418013, 24.07045165, 24.02160908, 37.35347151,
       31.47512829, 38.70428459, 30.55155018, 25.77625322, 37.03847777,
       37.92903866, 26.58807389, 36.76106159, 31.26635546, 26.40449453,
       36.28711783, 27.62572918, 38.10000002, 28.16583557, 38.90000004,
       37.3134072 , 39.56513993, 33.23014649, 36.39390933, 40.45892414,
       34.71238529, 38.15785405, 40.43576755, 38.65201223, 40.3848929 ,
       39.30128693, 38.06562203, 38.08826172, 38.56433022, 37.89765763,
       37.68963307, 40.97215272, 39.92449196, 39.07968852, 35.88722972,
       33.87090113])

In [89]:
yk = model.predict(X)

In [90]:
yk

array([29.63354997, 24.17608777, 23.72363825, 23.82118578, 24.68552021,
       23.64617382, 23.70655242, 23.73357102, 25.43086302, 25.43423792,
       27.59998052, 24.33418013, 24.07045165, 24.02160908, 37.35347151,
       31.47512829, 38.70428459, 30.55155018, 25.77625322, 37.03847777,
       37.92903866, 26.58807389, 36.76106159, 31.26635546, 26.40449453,
       36.28711783, 27.62572918, 38.10000002, 28.16583557, 38.90000004,
       37.3134072 , 39.56513993, 33.23014649, 36.39390933, 40.45892414,
       34.71238529, 38.15785405, 40.43576755, 38.65201223, 40.3848929 ,
       39.30128693, 38.06562203, 38.08826172, 38.56433022, 37.89765763,
       37.68963307, 40.97215272, 39.92449196, 39.07968852, 35.88722972,
       33.87090113])

In [91]:
l_check = df_data_check['Name'].tolist()

In [92]:
l_check

['Indian Institute of Science Bangalore',
 'Jawaharlal Nehru University',
 'Banaras Hindu University',
 'Jadavpur University',
 'Anna University',
 'University of Hyderabad',
 'University of Delhi',
 'Amrita Vishwa Vidyapeetham',
 'Savitribai Phule Pune University',
 'Aligarh Muslim University',
 'Jamia Millia Islamia',
 'Vellore Institute of Technology',
 'Calcutta University',
 'Manipal Academy of Higher Education-Manipal',
 'Visva Bharati',
 'Homi Bhabha National Institute',
 'Bharath Institute of Higher Education & Research',
 'Osmania University',
 'Institute of Chemical Technology',
 'Jamia Hamdard',
 'Gauhati University',
 'Bharathiar University',
 'Kerala University',
 'Tezpur University',
 'Panjab University',
 'Pondicherry University',
 'University of Madras',
 'Sri Venkateswara University',
 'Andhra University',
 'Sathyabama Institute of Science and Technology',
 'Dr. D. Y. Patil Vidyapeeth Pune',
 'North Eastern Hill University',
 'Kalinga Institute of Industrial Technology',
 'AMITY University',
 'Banasthali Vidyapith',
 'Bharati Vidyapeeth',
 'Saveetha Institute of Medical and Technical Sciences',
 'Calicut University',
 'Shiv Nadar University',
 'KLE Academy of Higher Education and Research',
 'University of Jammu',
 'Dayalbagh Educational Institute',
 'University of Kashmir',
 'Guru Nanak Dev University',
 'Guru Gobind Singh Indraprastha University',
 'Sri Balaji Vidyapeeth Mahatma Gandhi Medical College Campus',
 'NITTE University',
 'Periyar University',
 'Cochin University of Science and Technology',
 'Bharathidasan University',
 'Alagappa University']

In [93]:
percentile_list = pd.DataFrame({'Name' : [l_check],
                                'Rank' : [yk]})

In [94]:
percentile_list

,Name,Rank
0,"[Indian Institute of Science Bangalore, Jawaha...","[29.633549970782777, 24.17608776603732, 23.723..."

In [95]:
dd_check = pd.DataFrame(list(zip(l_check,yk)),
              columns=['Name','Rank'])

In [96]:
dd_check

                                                 Name       Rank
0               Indian Institute of Science Bangalore  29.633550
1                         Jawaharlal Nehru University  24.176088
2                            Banaras Hindu University  23.723638
3                                 Jadavpur University  23.821186
4                                     Anna University  24.685520
5                             University of Hyderabad  23.646174
6                                 University of Delhi  23.706552
7                          Amrita Vishwa Vidyapeetham  23.733571
8                    Savitribai Phule Pune University  25.430863
9                           Aligarh Muslim University  25.434238
10                               Jamia Millia Islamia  27.599981
11                    Vellore Institute of Technology  24.334180
12                                Calcutta University  24.070452
13        Manipal Academy of Higher Education-Manipal  24.021609
14                                      Visva Bharati  37.353472
15                     Homi Bhabha National Institute  31.475128
16   Bharath Institute of Higher Education & Research  38.704285
17                                 Osmania University  30.551550
18                   Institute of Chemical Technology  25.776253
19                                      Jamia Hamdard  37.038478
20                                 Gauhati University  37.929039
21                              Bharathiar University  26.588074
22                                  Kerala University  36.761062
23                                  Tezpur University  31.266355
24                                  Panjab University  26.404495
25                             Pondicherry University  36.287118
26                               University of Madras  27.625729
27                        Sri Venkateswara University  38.100000
28                                  Andhra University  28.165836
29     Sathyabama Institute of Science and Technology  38.900000
30                    Dr. D. Y. Patil Vidyapeeth Pune  37.313407
31                      North Eastern Hill University  39.565140
32         Kalinga Institute of Industrial Technology  33.230146
33                                   AMITY University  36.393909
34                               Banasthali Vidyapith  40.458924
35                                 Bharati Vidyapeeth  34.712385
36  Saveetha Institute of Medical and Technical Sc...  38.157854
37                                 Calicut University  40.435768
38                              Shiv Nadar University  38.652012
39       KLE Academy of Higher Education and Research  40.384893
40                                University of Jammu  39.301287
41                    Dayalbagh Educational Institute  38.065622
42                              University of Kashmir  38.088262
43                          Guru Nanak Dev University  38.564330
44          Guru Gobind Singh Indraprastha University  37.897658
45  Sri Balaji Vidyapeeth Mahatma Gandhi Medical C...  37.689633
46                                   NITTE University  40.972153
47                                 Periyar University  39.924492
48        Cochin University of Science and Technology  39.079689
49                           Bharathidasan University  35.887230
50                                Alagappa University  33.870901

In [97]:
dd_check.sort_values(by=['Rank'])

                                                 Name       Rank
5                             University of Hyderabad  23.646174
6                                 University of Delhi  23.706552
2                            Banaras Hindu University  23.723638
7                          Amrita Vishwa Vidyapeetham  23.733571
3                                 Jadavpur University  23.821186
13        Manipal Academy of Higher Education-Manipal  24.021609
12                                Calcutta University  24.070452
1                         Jawaharlal Nehru University  24.176088
11                    Vellore Institute of Technology  24.334180
4                                     Anna University  24.685520
8                    Savitribai Phule Pune University  25.430863
9                           Aligarh Muslim University  25.434238
18                   Institute of Chemical Technology  25.776253
24                                  Panjab University  26.404495
21                              Bharathiar University  26.588074
10                               Jamia Millia Islamia  27.599981
26                               University of Madras  27.625729
28                                  Andhra University  28.165836
0               Indian Institute of Science Bangalore  29.633550
17                                 Osmania University  30.551550
23                                  Tezpur University  31.266355
15                     Homi Bhabha National Institute  31.475128
32         Kalinga Institute of Industrial Technology  33.230146
50                                Alagappa University  33.870901
35                                 Bharati Vidyapeeth  34.712385
49                           Bharathidasan University  35.887230
25                             Pondicherry University  36.287118
33                                   AMITY University  36.393909
22                                  Kerala University  36.761062
19                                      Jamia Hamdard  37.038478
30                    Dr. D. Y. Patil Vidyapeeth Pune  37.313407
14                                      Visva Bharati  37.353472
45  Sri Balaji Vidyapeeth Mahatma Gandhi Medical C...  37.689633
44          Guru Gobind Singh Indraprastha University  37.897658
20                                 Gauhati University  37.929039
41                    Dayalbagh Educational Institute  38.065622
42                              University of Kashmir  38.088262
27                        Sri Venkateswara University  38.100000
36  Saveetha Institute of Medical and Technical Sc...  38.157854
43                          Guru Nanak Dev University  38.564330
38                              Shiv Nadar University  38.652012
16   Bharath Institute of Higher Education & Research  38.704285
29     Sathyabama Institute of Science and Technology  38.900000
48        Cochin University of Science and Technology  39.079689
40                                University of Jammu  39.301287
31                      North Eastern Hill University  39.565140
47                                 Periyar University  39.924492
39       KLE Academy of Higher Education and Research  40.384893
37                                 Calicut University  40.435768
34                               Banasthali Vidyapith  40.458924
46                                   NITTE University  40.972153

In [98]:
df_data_ck = pd.merge(df_data_20,df_2021,on='Name',suffixes=('','_2021'))

In [99]:
df_data_ck

,Name,infra_2017,placements_2017,academic_2017,Year_2017,Rank_2017,infra_2018,placements_2018,academic_2018,Year_2018,...,infra_2020,placements_2020,academic_2020,Year_2020,Rank_2020,infra_2021,placements_2021,academic_2021,Year_2021,Rank_2021
0,Indian Institute of Science Bangalore,83.33,1,52.74,2017,1,100.00,1,82.16,2018,...,100.00,1,84.18,2020,1,100.00,1,82.67,2021,1
1,Jawaharlal Nehru University,47.27,3,51.75,2017,2,46.28,3,67.57,2018,...,67.24,3,70.16,2020,2,67.88,2,67.99,2021,2
2,Banaras Hindu University,44.01,4,51.46,2017,3,43.62,4,63.52,2018,...,53.99,6,63.15,2020,3,58.57,5,64.02,2021,3
3,Jadavpur University,28.81,9,51.20,2017,5,35.50,6,59.68,2018,...,71.44,2,61.99,2020,5,67.31,3,60.33,2021,8
4,Anna University,43.94,5,48.90,2017,6,63.22,2,62.82,2018,...,65.89,4,58.71,2020,12,67.20,4,54.97,2021,16
5,University of Hyderabad,27.06,11,48.84,2017,7,21.66,19,60.54,2018,...,58.32,5,61.70,2020,6,52.49,7,59.71,2021,9
6,University of Delhi,30.76,7,48.27,2017,8,33.15,8,58.69,2018,...,53.44,7,60.10,2020,11,55.37,6,57.09,2021,12
7,Amrita Vishwa Vidyapeetham,26.12,12,48.19,2017,9,31.44,9,58.46,2018,...,44.33,13,62.27,2020,4,48.36,10,61.23,2021,5
8,Savitribai Phule Pune University,11.20,35,46.72,2017,10,15.04,26,58.24,2018,...,44.99,11,61.13,2020,9,41.49,20,58.34,2021,11
9,Aligarh Muslim University,16.62,21,83.28,2017,11,26.30,11,57.78,2018,...,38.99,23,54.30,2020,17,42.90,17,58.97,2021,10
10,Jamia Millia Islamia,9.73,42,61.53,2017,12,11.76,33,56.18,2018,...,31.60,41,61.07,2020,10,32.17,45,60.74,2021,6
11,Vellore Institute of Technology,32.95,6,58.25,2017,14,36.71,5,52.68,2018,...,49.00,8,55.22,2020,16,51.16,8,56.63,2021,13
12,Calcutta University,17.15,20,56.50,2017,16,26.30,11,53.38,2018,...,47.99,9,61.53,2020,7,45.77,14,62.06,2021,4
13,Manipal Academy of Higher Education-Manipal,27.67,10,55.37,2017,18,26.30,11,57.37,2018,...,43.95,15,61.51,2020,8,40.93,21,60.58,2021,7
14,Visva Bharati,4.71,69,54.70,2017,19,5.03,67,47.62,2018,...,19.30,121,46.84,2020,50,16.35,165,42.76,2021,64
15,Homi Bhabha National Institute,8.70,47,46.45,2017,21,9.85,42,48.98,2018,...,33.54,34,56.04,2020,14,34.35,39,53.24,2021,18
16,Bharath Institute of Higher Education & Research,3.79,84,46.45,2017,22,2.40,100,50.74,2018,...,21.87,89,45.67,2020,59,21.90,97,46.44,2021,51
17,Osmania University,11.16,36,45.52,2017,23,5.76,59,48.02,2018,...,39.00,20,51.15,2020,29,39.67,24,49.16,2021,32
18,Institute of Chemical Technology,20.69,16,44.95,2017,25,15.90,25,51.39,2018,...,44.07,14,54.10,2020,18,45.43,15,56.10,2021,15
19,Jamia Hamdard,1.87,110,44.84,2017,26,2.01,115,50.31,2018,...,23.16,83,52.60,2020,21,23.67,88,48.02,2021,41
20,Gauhati University,2.48,102,44.42,2017,27,6.11,57,45.44,2018,...,22.20,87,47.10,2020,47,25.34,79,47.35,2021,45
21,Bharathiar University,9.11,45,44.29,2017,28,22.63,17,55.08,2018,...,37.18,26,58.30,2020,13,35.22,37,56.44,2021,14
22,Kerala University,0.89,132,43.95,2017,29,7.17,51,47.72,2018,...,21.54,92,52.35,2020,23,21.44,102,50.52,2021,27
23,Tezpur University,7.09,54,43.78,2017,30,10.82,37,48.00,2018,...,34.88,30,48.77,2020,40,32.14,47,47.27,2021,46
24,Panjab University,18.99,18,43.13,2017,33,23.58,16,50.94,2018,...,42.39,16,51.85,2020,26,50.12,9,51.59,2021,23
25,Pondicherry University,4.67,70,42.70,2017,37,14.76,28,42.36,2018,...,28.88,58,45.82,2020,58,30.52,57,44.36,2021,58
26,University of Madras,10.82,40,41.85,2017,41,26.52,10,51.52,2018,...,38.30,24,52.55,2020,22,38.17,26,50.46,2021,28
27,Sri Venkateswara University,1.94,108,41.48,2017,42,2.01,115,43.44,2018,...,37.00,27,48.84,2020,38,33.90,40,45.61,2021,54
28,Andhra University,20.72,15,41.38,2017,43,9.53,43,50.39,2018,...,39.82,19,53.82,2020,19,42.86,18,51.10,2021,24
29,Sathyabama Institute of Science and Technology,11.08,38,41.30,2017,44,4.30,71,44.34,2018,...,19.47,114,48.77,2020,39,23.23,92,48.17,2021,40
30,Dr. D. Y. Patil Vidyapeeth Pune,11.61,33,40.59,2017,47,1.22,134,43.15,2018,...,33.54,34,47.92,2020,46,40.41,22,46.74,2021,49
31,North Eastern Hill University,3.24,93,40.51,2017,48,5.03,67,42.34,2018,...,23.48,81,46.88,2020,49,26.14,72,44.24,2021,59
32,Kalinga Institute of Industrial Technology,20.95,14,40.47,2017,49,3.55,82,44.81,2018,...,31.30,45,52.33,2020,24,31.74,50,52.06,2021,21
33,AMITY University,18.06,19,39.17,2017,52,5.40,64,42.99,2018,...,30.10,54,49.02,2020,37,32.53,44,50.90,2021,25
34,Banasthali Vidyapith,7.46,52,38.74,2017,53,4.30,71,41.88,2018,...,20.18,105,46.32,2020,55,37.34,29,48.57,2021,35
35,Bharati Vidyapeeth,30.64,8,38.73,2017,54,14.76,28,41.71,2018,...,39.00,20,44.84,2020,63,37.74,27,42.10,2021,68
36,Saveetha Institute of Medical and Technical Sc...,5.81,62,38.68,2017,55,3.17,88,44.00,2018,...,19.11,122,48.56,2020,42,19.52,123,50.36,2021,29
37,Calicut University,4.74,68,38.45,2017,57,5.76,59,40.06,2018,...,21.21,95,46.37,2020,54,20.01,115,44.13,2021,60
38,Shiv Nadar University,5.24,66,37.95,2017,60,0.00,203,43.68,2018,...,21.54,92,46.11,2020,56,27.30,67,45.00,2021,56
39,KLE Academy of Higher Education and Research,0.69,141,37.25,2017,62,2.79,96,42.76,2018,...,28.20,60,43.10,2020,70,31.74,50,39.44,2021,91
40,University of Jammu,0.59,157,37.23,2017,63,1.22,134,43.19,2018,...,31.47,42,46.55,2020,52,32.01,48,42.52,2021,66
41,Dayalbagh Educational Institute,15.65,22,36.36,2017,72,12.38,30,41.95,2018,...,30.70,48,41.21,2020,82,28.35,65,39.06,2021,94
42,University of Kashmir,0.10,184,36.32,2017,73,0.00,203,43.96,2018,...,25.82,68,46.99,2020,48,25.52,76,46.97,2021,48
43,Guru Nanak Dev University,4.65,71,35.83,2017,80,7.17,51,42.36,2018,...,35.48,29,46.58,2020,51,42.52,19,45.67,2021,53
44,Guru Gobind Singh Indraprastha University,3.37,90,35.60,2017,82,2.40,100,40.05,2018,...,4.53,229,40.24,2020,95,14.81,171,40.79,2021,79
45,Sri Balaji Vidyapeeth Mahatma Gandhi Medical C...,4.34,74,35.50,2017,83,0.00,203,40.25,2018,...,18.74,129,40.92,2020,88,20.01,115,40.42,2021,80
46,NITTE University,3.95,79,35.50,2017,84,8.53,46,39.70,2018,...,22.85,85,42.19,2020,74,24.51,85,41.04,2021,77
47,Periyar University,5.85,61,35.44,2017,85,4.30,71,38.58,2018,...,28.09,61,41.09,2020,83,19.52,123,41.38,2021,74
48,Cochin University of Science and Technology,1.89,109,35.42,2017,86,18.88,20,40.53,2018,...,29.39,56,45.02,2020,62,28.41,64,47.37,2021,44
49,Bharathidasan University,8.03,48,35.14,2017,88,26.30,11,41.63,2018,...,40.09,18,46.41,2020,53,37.19,32,44.63,2021,57
50,Alagappa University,4.17,77,33.66,2017,97,24.50,15,48.25,2018,...,44.76,12,49.22,2020,36,46.34,13,49.09,2021,33

In [100]:
df_data_ck.drop(['Year_2017','Year_2018','Year_2020','Year_2021','Year'],inplace=True,axis=1)

In [101]:
df_data_ck

,Name,infra_2017,placements_2017,academic_2017,Rank_2017,infra_2018,placements_2018,academic_2018,Rank_2018,infra,...,academic,Rank,infra_2020,placements_2020,academic_2020,Rank_2020,infra_2021,placements_2021,academic_2021,Rank_2021
0,Indian Institute of Science Bangalore,83.33,1,52.74,1,100.00,1,82.16,1,100.00,...,82.28,1,100.00,1,84.18,1,100.00,1,82.67,1
1,Jawaharlal Nehru University,47.27,3,51.75,2,46.28,3,67.57,2,55.27,...,68.68,2,67.24,3,70.16,2,67.88,2,67.99,2
2,Banaras Hindu University,44.01,4,51.46,3,43.62,4,63.52,3,47.28,...,64.55,3,53.99,6,63.15,3,58.57,5,64.02,3
3,Jadavpur University,28.81,9,51.20,5,35.50,6,59.68,6,51.83,...,60.53,6,71.44,2,61.99,5,67.31,3,60.33,8
4,Anna University,43.94,5,48.90,6,63.22,2,62.82,4,62.72,...,60.35,7,65.89,4,58.71,12,67.20,4,54.97,16
5,University of Hyderabad,27.06,11,48.84,7,21.66,19,60.54,5,36.71,...,61.85,4,58.32,5,61.70,6,52.49,7,59.71,9
6,University of Delhi,30.76,7,48.27,8,33.15,8,58.69,7,41.11,...,57.59,13,53.44,7,60.10,11,55.37,6,57.09,12
7,Amrita Vishwa Vidyapeetham,26.12,12,48.19,9,31.44,9,58.46,8,31.01,...,59.22,8,44.33,13,62.27,4,48.36,10,61.23,5
8,Savitribai Phule Pune University,11.20,35,46.72,10,15.04,26,58.24,9,16.55,...,58.40,10,44.99,11,61.13,9,41.49,20,58.34,11
9,Aligarh Muslim University,16.62,21,83.28,11,26.30,11,57.78,10,18.46,...,58.36,11,38.99,23,54.30,17,42.90,17,58.97,10
10,Jamia Millia Islamia,9.73,42,61.53,12,11.76,33,56.18,12,14.26,...,58.07,12,31.60,41,61.07,10,32.17,45,60.74,6
11,Vellore Institute of Technology,32.95,6,58.25,14,36.71,5,52.68,16,35.31,...,51.44,19,49.00,8,55.22,16,51.16,8,56.63,13
12,Calcutta University,17.15,20,56.50,16,26.30,11,53.38,14,37.39,...,60.87,5,47.99,9,61.53,7,45.77,14,62.06,4
13,Manipal Academy of Higher Education-Manipal,27.67,10,55.37,18,26.30,11,57.37,11,30.21,...,58.50,9,43.95,15,61.51,8,40.93,21,60.58,7
14,Visva Bharati,4.71,69,54.70,19,5.03,67,47.62,31,11.52,...,46.27,37,19.30,121,46.84,50,16.35,165,42.76,64
15,Homi Bhabha National Institute,8.70,47,46.45,21,9.85,42,48.98,26,4.33,...,51.95,17,33.54,34,56.04,14,34.35,39,53.24,18
16,Bharath Institute of Higher Education & Research,3.79,84,46.45,22,2.40,100,50.74,21,3.19,...,46.32,36,21.87,89,45.67,59,21.90,97,46.44,51
17,Osmania University,11.16,36,45.52,23,5.76,59,48.02,28,9.26,...,49.86,26,39.00,20,51.15,29,39.67,24,49.16,32
18,Institute of Chemical Technology,20.69,16,44.95,25,15.90,25,51.39,19,20.28,...,52.62,15,44.07,14,54.10,18,45.43,15,56.10,15
19,Jamia Hamdard,1.87,110,44.84,26,2.01,115,50.31,23,6.86,...,51.73,18,23.16,83,52.60,21,23.67,88,48.02,41
20,Gauhati University,2.48,102,44.42,27,6.11,57,45.44,39,9.59,...,45.57,42,22.20,87,47.10,47,25.34,79,47.35,45
21,Bharathiar University,9.11,45,44.29,28,22.63,17,55.08,13,31.20,...,57.23,14,37.18,26,58.30,13,35.22,37,56.44,14
22,Kerala University,0.89,132,43.95,29,7.17,51,47.72,30,8.59,...,51.21,22,21.54,92,52.35,23,21.44,102,50.52,27
23,Tezpur University,7.09,54,43.78,30,10.82,37,48.00,29,15.71,...,48.47,29,34.88,30,48.77,40,32.14,47,47.27,46
24,Panjab University,18.99,18,43.13,33,23.58,16,50.94,20,27.09,...,51.25,21,42.39,16,51.85,26,50.12,9,51.59,23
25,Pondicherry University,4.67,70,42.70,37,14.76,28,42.36,59,19.25,...,44.88,48,28.88,58,45.82,58,30.52,57,44.36,58
26,University of Madras,10.82,40,41.85,41,26.52,10,51.52,18,30.01,...,51.34,20,38.30,24,52.55,22,38.17,26,50.46,28
27,Sri Venkateswara University,1.94,108,41.48,42,2.01,115,43.44,49,6.51,...,44.88,49,37.00,27,48.84,38,33.90,40,45.61,54
28,Andhra University,20.72,15,41.38,43,9.53,43,50.39,22,14.55,...,52.11,16,39.82,19,53.82,19,42.86,18,51.10,24
29,Sathyabama Institute of Science and Technology,11.08,38,41.30,44,4.30,71,44.34,45,2.41,...,45.58,41,19.47,114,48.77,39,23.23,92,48.17,40
30,Dr. D. Y. Patil Vidyapeeth Pune,11.61,33,40.59,47,1.22,134,43.15,52,7.56,...,45.11,46,33.54,34,47.92,46,40.41,22,46.74,49
31,North Eastern Hill University,3.24,93,40.51,48,5.03,67,42.34,61,6.51,...,45.99,39,23.48,81,46.88,49,26.14,72,44.24,59
32,Kalinga Institute of Industrial Technology,20.95,14,40.47,49,3.55,82,44.81,42,14.55,...,47.97,31,31.30,45,52.33,24,31.74,50,52.06,21
33,AMITY University,18.06,19,39.17,52,5.40,64,42.99,53,7.22,...,43.53,58,30.10,54,49.02,37,32.53,44,50.90,25
34,Banasthali Vidyapith,7.46,52,38.74,53,4.30,71,41.88,64,4.33,...,43.22,61,20.18,105,46.32,55,37.34,29,48.57,35
35,Bharati Vidyapeeth,30.64,8,38.73,54,14.76,28,41.71,66,13.66,...,42.89,62,39.00,20,44.84,63,37.74,27,42.10,68
36,Saveetha Institute of Medical and Technical Sc...,5.81,62,38.68,55,3.17,88,44.00,46,0.00,...,45.42,43,19.11,122,48.56,42,19.52,123,50.36,29
37,Calicut University,4.74,68,38.45,57,5.76,59,40.06,73,7.22,...,42.22,64,21.21,95,46.37,54,20.01,115,44.13,60
38,Shiv Nadar University,5.24,66,37.95,60,0.00,203,43.68,48,6.15,...,44.45,52,21.54,92,46.11,56,27.30,67,45.00,56
39,KLE Academy of Higher Education and Research,0.69,141,37.25,62,2.79,96,42.76,57,4.33,...,40.92,69,28.20,60,43.10,70,31.74,50,39.44,91
40,University of Jammu,0.59,157,37.23,63,1.22,134,43.19,51,2.02,...,40.43,74,31.47,42,46.55,52,32.01,48,42.52,66
41,Dayalbagh Educational Institute,15.65,22,36.36,72,12.38,30,41.95,63,11.83,...,40.24,77,30.70,48,41.21,82,28.35,65,39.06,94
42,University of Kashmir,0.10,184,36.32,73,0.00,203,43.96,47,1.63,...,44.19,53,25.82,68,46.99,48,25.52,76,46.97,48
43,Guru Nanak Dev University,4.65,71,35.83,80,7.17,51,42.36,60,5.80,...,43.69,55,35.48,29,46.58,51,42.52,19,45.67,53
44,Guru Gobind Singh Indraprastha University,3.37,90,35.60,82,2.40,100,40.05,74,3.58,...,41.21,66,4.53,229,40.24,95,14.81,171,40.79,79
45,Sri Balaji Vidyapeeth Mahatma Gandhi Medical C...,4.34,74,35.50,83,0.00,203,40.25,72,0.00,...,40.87,72,18.74,129,40.92,88,20.01,115,40.42,80
46,NITTE University,3.95,79,35.50,84,8.53,46,39.70,77,6.51,...,40.88,70,22.85,85,42.19,74,24.51,85,41.04,77
47,Periyar University,5.85,61,35.44,85,4.30,71,38.58,90,19.25,...,40.99,68,28.09,61,41.09,83,19.52,123,41.38,74
48,Cochin University of Science and Technology,1.89,109,35.42,86,18.88,20,40.53,69,14.84,...,41.42,65,29.39,56,45.02,62,28.41,64,47.37,44
49,Bharathidasan University,8.03,48,35.14,88,26.30,11,41.63,67,24.17,...,43.41,60,40.09,18,46.41,53,37.19,32,44.63,57
50,Alagappa University,4.17,77,33.66,97,24.50,15,48.25,27,26.65,...,48.54,28,44.76,12,49.22,36,46.34,13,49.09,33

In [102]:
df_data_ck.drop(['infra_2017','placements_2017', 'academic_2017','Rank_2017'],inplace=True,axis=1)

In [103]:
df_data_ck

,Name,infra_2018,placements_2018,academic_2018,Rank_2018,infra,placements,academic,Rank,infra_2020,placements_2020,academic_2020,Rank_2020,infra_2021,placements_2021,academic_2021,Rank_2021
0,Indian Institute of Science Bangalore,100.00,1,82.16,1,100.00,1,82.28,1,100.00,1,84.18,1,100.00,1,82.67,1
1,Jawaharlal Nehru University,46.28,3,67.57,2,55.27,3,68.68,2,67.24,3,70.16,2,67.88,2,67.99,2
2,Banaras Hindu University,43.62,4,63.52,3,47.28,5,64.55,3,53.99,6,63.15,3,58.57,5,64.02,3
3,Jadavpur University,35.50,6,59.68,6,51.83,4,60.53,6,71.44,2,61.99,5,67.31,3,60.33,8
4,Anna University,63.22,2,62.82,4,62.72,2,60.35,7,65.89,4,58.71,12,67.20,4,54.97,16
5,University of Hyderabad,21.66,19,60.54,5,36.71,8,61.85,4,58.32,5,61.70,6,52.49,7,59.71,9
6,University of Delhi,33.15,8,58.69,7,41.11,6,57.59,13,53.44,7,60.10,11,55.37,6,57.09,12
7,Amrita Vishwa Vidyapeetham,31.44,9,58.46,8,31.01,12,59.22,8,44.33,13,62.27,4,48.36,10,61.23,5
8,Savitribai Phule Pune University,15.04,26,58.24,9,16.55,28,58.40,10,44.99,11,61.13,9,41.49,20,58.34,11
9,Aligarh Muslim University,26.30,11,57.78,10,18.46,27,58.36,11,38.99,23,54.30,17,42.90,17,58.97,10
10,Jamia Millia Islamia,11.76,33,56.18,12,14.26,37,58.07,12,31.60,41,61.07,10,32.17,45,60.74,6
11,Vellore Institute of Technology,36.71,5,52.68,16,35.31,9,51.44,19,49.00,8,55.22,16,51.16,8,56.63,13
12,Calcutta University,26.30,11,53.38,14,37.39,7,60.87,5,47.99,9,61.53,7,45.77,14,62.06,4
13,Manipal Academy of Higher Education-Manipal,26.30,11,57.37,11,30.21,14,58.50,9,43.95,15,61.51,8,40.93,21,60.58,7
14,Visva Bharati,5.03,67,47.62,31,11.52,44,46.27,37,19.30,121,46.84,50,16.35,165,42.76,64
15,Homi Bhabha National Institute,9.85,42,48.98,26,4.33,87,51.95,17,33.54,34,56.04,14,34.35,39,53.24,18
16,Bharath Institute of Higher Education & Research,2.40,100,50.74,21,3.19,103,46.32,36,21.87,89,45.67,59,21.90,97,46.44,51
17,Osmania University,5.76,59,48.02,28,9.26,50,49.86,26,39.00,20,51.15,29,39.67,24,49.16,32
18,Institute of Chemical Technology,15.90,25,51.39,19,20.28,21,52.62,15,44.07,14,54.10,18,45.43,15,56.10,15
19,Jamia Hamdard,2.01,115,50.31,23,6.86,64,51.73,18,23.16,83,52.60,21,23.67,88,48.02,41
20,Gauhati University,6.11,57,45.44,39,9.59,49,45.57,42,22.20,87,47.10,47,25.34,79,47.35,45
21,Bharathiar University,22.63,17,55.08,13,31.20,11,57.23,14,37.18,26,58.30,13,35.22,37,56.44,14
22,Kerala University,7.17,51,47.72,30,8.59,51,51.21,22,21.54,92,52.35,23,21.44,102,50.52,27
23,Tezpur University,10.82,37,48.00,29,15.71,31,48.47,29,34.88,30,48.77,40,32.14,47,47.27,46
24,Panjab University,23.58,16,50.94,20,27.09,16,51.25,21,42.39,16,51.85,26,50.12,9,51.59,23
25,Pondicherry University,14.76,28,42.36,59,19.25,25,44.88,48,28.88,58,45.82,58,30.52,57,44.36,58
26,University of Madras,26.52,10,51.52,18,30.01,15,51.34,20,38.30,24,52.55,22,38.17,26,50.46,28
27,Sri Venkateswara University,2.01,115,43.44,49,6.51,66,44.88,49,37.00,27,48.84,38,33.90,40,45.61,54
28,Andhra University,9.53,43,50.39,22,14.55,34,52.11,16,39.82,19,53.82,19,42.86,18,51.10,24
29,Sathyabama Institute of Science and Technology,4.30,71,44.34,45,2.41,123,45.58,41,19.47,114,48.77,39,23.23,92,48.17,40
30,Dr. D. Y. Patil Vidyapeeth Pune,1.22,134,43.15,52,7.56,59,45.11,46,33.54,34,47.92,46,40.41,22,46.74,49
31,North Eastern Hill University,5.03,67,42.34,61,6.51,66,45.99,39,23.48,81,46.88,49,26.14,72,44.24,59
32,Kalinga Institute of Industrial Technology,3.55,82,44.81,42,14.55,34,47.97,31,31.30,45,52.33,24,31.74,50,52.06,21
33,AMITY University,5.40,64,42.99,53,7.22,61,43.53,58,30.10,54,49.02,37,32.53,44,50.90,25
34,Banasthali Vidyapith,4.30,71,41.88,64,4.33,87,43.22,61,20.18,105,46.32,55,37.34,29,48.57,35
35,Bharati Vidyapeeth,14.76,28,41.71,66,13.66,39,42.89,62,39.00,20,44.84,63,37.74,27,42.10,68
36,Saveetha Institute of Medical and Technical Sc...,3.17,88,44.00,46,0.00,222,45.42,43,19.11,122,48.56,42,19.52,123,50.36,29
37,Calicut University,5.76,59,40.06,73,7.22,61,42.22,64,21.21,95,46.37,54,20.01,115,44.13,60
38,Shiv Nadar University,0.00,203,43.68,48,6.15,70,44.45,52,21.54,92,46.11,56,27.30,67,45.00,56
39,KLE Academy of Higher Education and Research,2.79,96,42.76,57,4.33,87,40.92,69,28.20,60,43.10,70,31.74,50,39.44,91
40,University of Jammu,1.22,134,43.19,51,2.02,135,40.43,74,31.47,42,46.55,52,32.01,48,42.52,66
41,Dayalbagh Educational Institute,12.38,30,41.95,63,11.83,43,40.24,77,30.70,48,41.21,82,28.35,65,39.06,94
42,University of Kashmir,0.00,203,43.96,47,1.63,148,44.19,53,25.82,68,46.99,48,25.52,76,46.97,48
43,Guru Nanak Dev University,7.17,51,42.36,60,5.80,73,43.69,55,35.48,29,46.58,51,42.52,19,45.67,53
44,Guru Gobind Singh Indraprastha University,2.40,100,40.05,74,3.58,98,41.21,66,4.53,229,40.24,95,14.81,171,40.79,79
45,Sri Balaji Vidyapeeth Mahatma Gandhi Medical C...,0.00,203,40.25,72,0.00,222,40.87,72,18.74,129,40.92,88,20.01,115,40.42,80
46,NITTE University,8.53,46,39.70,77,6.51,66,40.88,70,22.85,85,42.19,74,24.51,85,41.04,77
47,Periyar University,4.30,71,38.58,90,19.25,25,40.99,68,28.09,61,41.09,83,19.52,123,41.38,74
48,Cochin University of Science and Technology,18.88,20,40.53,69,14.84,32,41.42,65,29.39,56,45.02,62,28.41,64,47.37,44
49,Bharathidasan University,26.30,11,41.63,67,24.17,18,43.41,60,40.09,18,46.41,53,37.19,32,44.63,57
50,Alagappa University,24.50,15,48.25,27,26.65,17,48.54,28,44.76,12,49.22,36,46.34,13,49.09,33

In [104]:
X=df_data_ck.drop('Name',axis=1)

In [105]:
X

,infra_2018,placements_2018,academic_2018,Rank_2018,infra,placements,academic,Rank,infra_2020,placements_2020,academic_2020,Rank_2020,infra_2021,placements_2021,academic_2021,Rank_2021
0,100.00,1,82.16,1,100.00,1,82.28,1,100.00,1,84.18,1,100.00,1,82.67,1
1,46.28,3,67.57,2,55.27,3,68.68,2,67.24,3,70.16,2,67.88,2,67.99,2
2,43.62,4,63.52,3,47.28,5,64.55,3,53.99,6,63.15,3,58.57,5,64.02,3
3,35.50,6,59.68,6,51.83,4,60.53,6,71.44,2,61.99,5,67.31,3,60.33,8
4,63.22,2,62.82,4,62.72,2,60.35,7,65.89,4,58.71,12,67.20,4,54.97,16
5,21.66,19,60.54,5,36.71,8,61.85,4,58.32,5,61.70,6,52.49,7,59.71,9
6,33.15,8,58.69,7,41.11,6,57.59,13,53.44,7,60.10,11,55.37,6,57.09,12
7,31.44,9,58.46,8,31.01,12,59.22,8,44.33,13,62.27,4,48.36,10,61.23,5
8,15.04,26,58.24,9,16.55,28,58.40,10,44.99,11,61.13,9,41.49,20,58.34,11
9,26.30,11,57.78,10,18.46,27,58.36,11,38.99,23,54.30,17,42.90,17,58.97,10
10,11.76,33,56.18,12,14.26,37,58.07,12,31.60,41,61.07,10,32.17,45,60.74,6
11,36.71,5,52.68,16,35.31,9,51.44,19,49.00,8,55.22,16,51.16,8,56.63,13
12,26.30,11,53.38,14,37.39,7,60.87,5,47.99,9,61.53,7,45.77,14,62.06,4
13,26.30,11,57.37,11,30.21,14,58.50,9,43.95,15,61.51,8,40.93,21,60.58,7
14,5.03,67,47.62,31,11.52,44,46.27,37,19.30,121,46.84,50,16.35,165,42.76,64
15,9.85,42,48.98,26,4.33,87,51.95,17,33.54,34,56.04,14,34.35,39,53.24,18
16,2.40,100,50.74,21,3.19,103,46.32,36,21.87,89,45.67,59,21.90,97,46.44,51
17,5.76,59,48.02,28,9.26,50,49.86,26,39.00,20,51.15,29,39.67,24,49.16,32
18,15.90,25,51.39,19,20.28,21,52.62,15,44.07,14,54.10,18,45.43,15,56.10,15
19,2.01,115,50.31,23,6.86,64,51.73,18,23.16,83,52.60,21,23.67,88,48.02,41
20,6.11,57,45.44,39,9.59,49,45.57,42,22.20,87,47.10,47,25.34,79,47.35,45
21,22.63,17,55.08,13,31.20,11,57.23,14,37.18,26,58.30,13,35.22,37,56.44,14
22,7.17,51,47.72,30,8.59,51,51.21,22,21.54,92,52.35,23,21.44,102,50.52,27
23,10.82,37,48.00,29,15.71,31,48.47,29,34.88,30,48.77,40,32.14,47,47.27,46
24,23.58,16,50.94,20,27.09,16,51.25,21,42.39,16,51.85,26,50.12,9,51.59,23
25,14.76,28,42.36,59,19.25,25,44.88,48,28.88,58,45.82,58,30.52,57,44.36,58
26,26.52,10,51.52,18,30.01,15,51.34,20,38.30,24,52.55,22,38.17,26,50.46,28
27,2.01,115,43.44,49,6.51,66,44.88,49,37.00,27,48.84,38,33.90,40,45.61,54
28,9.53,43,50.39,22,14.55,34,52.11,16,39.82,19,53.82,19,42.86,18,51.10,24
29,4.30,71,44.34,45,2.41,123,45.58,41,19.47,114,48.77,39,23.23,92,48.17,40
30,1.22,134,43.15,52,7.56,59,45.11,46,33.54,34,47.92,46,40.41,22,46.74,49
31,5.03,67,42.34,61,6.51,66,45.99,39,23.48,81,46.88,49,26.14,72,44.24,59
32,3.55,82,44.81,42,14.55,34,47.97,31,31.30,45,52.33,24,31.74,50,52.06,21
33,5.40,64,42.99,53,7.22,61,43.53,58,30.10,54,49.02,37,32.53,44,50.90,25
34,4.30,71,41.88,64,4.33,87,43.22,61,20.18,105,46.32,55,37.34,29,48.57,35
35,14.76,28,41.71,66,13.66,39,42.89,62,39.00,20,44.84,63,37.74,27,42.10,68
36,3.17,88,44.00,46,0.00,222,45.42,43,19.11,122,48.56,42,19.52,123,50.36,29
37,5.76,59,40.06,73,7.22,61,42.22,64,21.21,95,46.37,54,20.01,115,44.13,60
38,0.00,203,43.68,48,6.15,70,44.45,52,21.54,92,46.11,56,27.30,67,45.00,56
39,2.79,96,42.76,57,4.33,87,40.92,69,28.20,60,43.10,70,31.74,50,39.44,91
40,1.22,134,43.19,51,2.02,135,40.43,74,31.47,42,46.55,52,32.01,48,42.52,66
41,12.38,30,41.95,63,11.83,43,40.24,77,30.70,48,41.21,82,28.35,65,39.06,94
42,0.00,203,43.96,47,1.63,148,44.19,53,25.82,68,46.99,48,25.52,76,46.97,48
43,7.17,51,42.36,60,5.80,73,43.69,55,35.48,29,46.58,51,42.52,19,45.67,53
44,2.40,100,40.05,74,3.58,98,41.21,66,4.53,229,40.24,95,14.81,171,40.79,79
45,0.00,203,40.25,72,0.00,222,40.87,72,18.74,129,40.92,88,20.01,115,40.42,80
46,8.53,46,39.70,77,6.51,66,40.88,70,22.85,85,42.19,74,24.51,85,41.04,77
47,4.30,71,38.58,90,19.25,25,40.99,68,28.09,61,41.09,83,19.52,123,41.38,74
48,18.88,20,40.53,69,14.84,32,41.42,65,29.39,56,45.02,62,28.41,64,47.37,44
49,26.30,11,41.63,67,24.17,18,43.41,60,40.09,18,46.41,53,37.19,32,44.63,57
50,24.50,15,48.25,27,26.65,17,48.54,28,44.76,12,49.22,36,46.34,13,49.09,33

In [106]:
X.columns

Index(['infra_2018', 'placements_2018', 'academic_2018', 'Rank_2018', 'infra',
       'placements', 'academic', 'Rank', 'infra_2020', 'placements_2020',
       'academic_2020', 'Rank_2020', 'infra_2021', 'placements_2021',
       'academic_2021', 'Rank_2021'],
      dtype='object')

In [107]:
df_data_21.columns

Index(['infra_2017', 'placements_2017', 'academic_2017', 'Rank_2017',
       'infra_2018', 'placements_2018', 'academic_2018', 'Rank_2018', 'infra',
       'placements', 'academic', 'Rank', 'infra_2020', 'placements_2020',
       'academic_2020', 'Rank_2020', 'Rank_2021'],
      dtype='object')

In [108]:
X.rename(columns = {'infra_2018':'infra_2017', 'placements_2018':'placements_2017',
                    'academic_2018':'academic_2017', 'Rank_2018':'Rank_2017',
                   'infra':'infra_2018', 'placements':'placements_2018',
                   'academic':'academic_2018', 'Rank':'Rank_2018',
                   'infra_2020':'infra', 'placements_2020':'placements',
                   'academic_2020':'academic', 'Rank_2020':'Rank',
                   'infra_2021':'infra_2020', 'placements_2021':'placements_2020',
                   'academic_2021':'academic_2020', 'Rank_2021':'Rank_2020'}, inplace = True)

In [109]:
X

,infra_2017,placements_2017,academic_2017,Rank_2017,infra_2018,placements_2018,academic_2018,Rank_2018,infra,placements,academic,Rank,infra_2020,placements_2020,academic_2020,Rank_2020
0,100.00,1,82.16,1,100.00,1,82.28,1,100.00,1,84.18,1,100.00,1,82.67,1
1,46.28,3,67.57,2,55.27,3,68.68,2,67.24,3,70.16,2,67.88,2,67.99,2
2,43.62,4,63.52,3,47.28,5,64.55,3,53.99,6,63.15,3,58.57,5,64.02,3
3,35.50,6,59.68,6,51.83,4,60.53,6,71.44,2,61.99,5,67.31,3,60.33,8
4,63.22,2,62.82,4,62.72,2,60.35,7,65.89,4,58.71,12,67.20,4,54.97,16
5,21.66,19,60.54,5,36.71,8,61.85,4,58.32,5,61.70,6,52.49,7,59.71,9
6,33.15,8,58.69,7,41.11,6,57.59,13,53.44,7,60.10,11,55.37,6,57.09,12
7,31.44,9,58.46,8,31.01,12,59.22,8,44.33,13,62.27,4,48.36,10,61.23,5
8,15.04,26,58.24,9,16.55,28,58.40,10,44.99,11,61.13,9,41.49,20,58.34,11
9,26.30,11,57.78,10,18.46,27,58.36,11,38.99,23,54.30,17,42.90,17,58.97,10
10,11.76,33,56.18,12,14.26,37,58.07,12,31.60,41,61.07,10,32.17,45,60.74,6
11,36.71,5,52.68,16,35.31,9,51.44,19,49.00,8,55.22,16,51.16,8,56.63,13
12,26.30,11,53.38,14,37.39,7,60.87,5,47.99,9,61.53,7,45.77,14,62.06,4
13,26.30,11,57.37,11,30.21,14,58.50,9,43.95,15,61.51,8,40.93,21,60.58,7
14,5.03,67,47.62,31,11.52,44,46.27,37,19.30,121,46.84,50,16.35,165,42.76,64
15,9.85,42,48.98,26,4.33,87,51.95,17,33.54,34,56.04,14,34.35,39,53.24,18
16,2.40,100,50.74,21,3.19,103,46.32,36,21.87,89,45.67,59,21.90,97,46.44,51
17,5.76,59,48.02,28,9.26,50,49.86,26,39.00,20,51.15,29,39.67,24,49.16,32
18,15.90,25,51.39,19,20.28,21,52.62,15,44.07,14,54.10,18,45.43,15,56.10,15
19,2.01,115,50.31,23,6.86,64,51.73,18,23.16,83,52.60,21,23.67,88,48.02,41
20,6.11,57,45.44,39,9.59,49,45.57,42,22.20,87,47.10,47,25.34,79,47.35,45
21,22.63,17,55.08,13,31.20,11,57.23,14,37.18,26,58.30,13,35.22,37,56.44,14
22,7.17,51,47.72,30,8.59,51,51.21,22,21.54,92,52.35,23,21.44,102,50.52,27
23,10.82,37,48.00,29,15.71,31,48.47,29,34.88,30,48.77,40,32.14,47,47.27,46
24,23.58,16,50.94,20,27.09,16,51.25,21,42.39,16,51.85,26,50.12,9,51.59,23
25,14.76,28,42.36,59,19.25,25,44.88,48,28.88,58,45.82,58,30.52,57,44.36,58
26,26.52,10,51.52,18,30.01,15,51.34,20,38.30,24,52.55,22,38.17,26,50.46,28
27,2.01,115,43.44,49,6.51,66,44.88,49,37.00,27,48.84,38,33.90,40,45.61,54
28,9.53,43,50.39,22,14.55,34,52.11,16,39.82,19,53.82,19,42.86,18,51.10,24
29,4.30,71,44.34,45,2.41,123,45.58,41,19.47,114,48.77,39,23.23,92,48.17,40
30,1.22,134,43.15,52,7.56,59,45.11,46,33.54,34,47.92,46,40.41,22,46.74,49
31,5.03,67,42.34,61,6.51,66,45.99,39,23.48,81,46.88,49,26.14,72,44.24,59
32,3.55,82,44.81,42,14.55,34,47.97,31,31.30,45,52.33,24,31.74,50,52.06,21
33,5.40,64,42.99,53,7.22,61,43.53,58,30.10,54,49.02,37,32.53,44,50.90,25
34,4.30,71,41.88,64,4.33,87,43.22,61,20.18,105,46.32,55,37.34,29,48.57,35
35,14.76,28,41.71,66,13.66,39,42.89,62,39.00,20,44.84,63,37.74,27,42.10,68
36,3.17,88,44.00,46,0.00,222,45.42,43,19.11,122,48.56,42,19.52,123,50.36,29
37,5.76,59,40.06,73,7.22,61,42.22,64,21.21,95,46.37,54,20.01,115,44.13,60
38,0.00,203,43.68,48,6.15,70,44.45,52,21.54,92,46.11,56,27.30,67,45.00,56
39,2.79,96,42.76,57,4.33,87,40.92,69,28.20,60,43.10,70,31.74,50,39.44,91
40,1.22,134,43.19,51,2.02,135,40.43,74,31.47,42,46.55,52,32.01,48,42.52,66
41,12.38,30,41.95,63,11.83,43,40.24,77,30.70,48,41.21,82,28.35,65,39.06,94
42,0.00,203,43.96,47,1.63,148,44.19,53,25.82,68,46.99,48,25.52,76,46.97,48
43,7.17,51,42.36,60,5.80,73,43.69,55,35.48,29,46.58,51,42.52,19,45.67,53
44,2.40,100,40.05,74,3.58,98,41.21,66,4.53,229,40.24,95,14.81,171,40.79,79
45,0.00,203,40.25,72,0.00,222,40.87,72,18.74,129,40.92,88,20.01,115,40.42,80
46,8.53,46,39.70,77,6.51,66,40.88,70,22.85,85,42.19,74,24.51,85,41.04,77
47,4.30,71,38.58,90,19.25,25,40.99,68,28.09,61,41.09,83,19.52,123,41.38,74
48,18.88,20,40.53,69,14.84,32,41.42,65,29.39,56,45.02,62,28.41,64,47.37,44
49,26.30,11,41.63,67,24.17,18,43.41,60,40.09,18,46.41,53,37.19,32,44.63,57
50,24.50,15,48.25,27,26.65,17,48.54,28,44.76,12,49.22,36,46.34,13,49.09,33

In [110]:
yk_ck = model.predict(X)

In [111]:
yk_ck

array([30.42138888, 24.76399774, 23.90780504, 24.5340346 , 25.40977134,
       23.94253557, 23.90875652, 23.54870247, 24.81844351, 24.57073831,
       27.1894591 , 24.31072481, 23.74554692, 23.97306383, 38.59081254,
       30.86468718, 39.41201677, 30.42077536, 25.17544518, 37.04053624,
       37.66115167, 25.30811748, 35.8449198 , 31.45187529, 25.42403302,
       36.08360285, 25.94022669, 37.10555353, 27.13806538, 39.5095223 ,
       36.96590801, 39.19330261, 33.17377333, 35.75197174, 38.52119266,
       35.69166603, 37.90271071, 40.55009525, 38.14156129, 40.24781539,
       38.86867211, 39.14674053, 37.81508121, 35.73110899, 37.48688785,
       37.16528565, 40.73382525, 39.86877246, 36.86717531, 33.66287038,
       27.05108654])

In [112]:
dd_check_yk = pd.DataFrame((zip(l_check,yk_ck)),
              columns=['Name','Rank'])

In [113]:
dd_check_yk

                                                 Name       Rank
0               Indian Institute of Science Bangalore  30.421389
1                         Jawaharlal Nehru University  24.763998
2                            Banaras Hindu University  23.907805
3                                 Jadavpur University  24.534035
4                                     Anna University  25.409771
5                             University of Hyderabad  23.942536
6                                 University of Delhi  23.908757
7                          Amrita Vishwa Vidyapeetham  23.548702
8                    Savitribai Phule Pune University  24.818444
9                           Aligarh Muslim University  24.570738
10                               Jamia Millia Islamia  27.189459
11                    Vellore Institute of Technology  24.310725
12                                Calcutta University  23.745547
13        Manipal Academy of Higher Education-Manipal  23.973064
14                                      Visva Bharati  38.590813
15                     Homi Bhabha National Institute  30.864687
16   Bharath Institute of Higher Education & Research  39.412017
17                                 Osmania University  30.420775
18                   Institute of Chemical Technology  25.175445
19                                      Jamia Hamdard  37.040536
20                                 Gauhati University  37.661152
21                              Bharathiar University  25.308117
22                                  Kerala University  35.844920
23                                  Tezpur University  31.451875
24                                  Panjab University  25.424033
25                             Pondicherry University  36.083603
26                               University of Madras  25.940227
27                        Sri Venkateswara University  37.105554
28                                  Andhra University  27.138065
29     Sathyabama Institute of Science and Technology  39.509522
30                    Dr. D. Y. Patil Vidyapeeth Pune  36.965908
31                      North Eastern Hill University  39.193303
32         Kalinga Institute of Industrial Technology  33.173773
33                                   AMITY University  35.751972
34                               Banasthali Vidyapith  38.521193
35                                 Bharati Vidyapeeth  35.691666
36  Saveetha Institute of Medical and Technical Sc...  37.902711
37                                 Calicut University  40.550095
38                              Shiv Nadar University  38.141561
39       KLE Academy of Higher Education and Research  40.247815
40                                University of Jammu  38.868672
41                    Dayalbagh Educational Institute  39.146741
42                              University of Kashmir  37.815081
43                          Guru Nanak Dev University  35.731109
44          Guru Gobind Singh Indraprastha University  37.486888
45  Sri Balaji Vidyapeeth Mahatma Gandhi Medical C...  37.165286
46                                   NITTE University  40.733825
47                                 Periyar University  39.868772
48        Cochin University of Science and Technology  36.867175
49                           Bharathidasan University  33.662870
50                                Alagappa University  27.051087

In [114]:
dd_check_yk.sort_values(by=['Rank'])

                                                 Name       Rank
7                          Amrita Vishwa Vidyapeetham  23.548702
12                                Calcutta University  23.745547
2                            Banaras Hindu University  23.907805
6                                 University of Delhi  23.908757
5                             University of Hyderabad  23.942536
13        Manipal Academy of Higher Education-Manipal  23.973064
11                    Vellore Institute of Technology  24.310725
3                                 Jadavpur University  24.534035
9                           Aligarh Muslim University  24.570738
1                         Jawaharlal Nehru University  24.763998
8                    Savitribai Phule Pune University  24.818444
18                   Institute of Chemical Technology  25.175445
21                              Bharathiar University  25.308117
4                                     Anna University  25.409771
24                                  Panjab University  25.424033
26                               University of Madras  25.940227
50                                Alagappa University  27.051087
28                                  Andhra University  27.138065
10                               Jamia Millia Islamia  27.189459
17                                 Osmania University  30.420775
0               Indian Institute of Science Bangalore  30.421389
15                     Homi Bhabha National Institute  30.864687
23                                  Tezpur University  31.451875
32         Kalinga Institute of Industrial Technology  33.173773
49                           Bharathidasan University  33.662870
35                                 Bharati Vidyapeeth  35.691666
43                          Guru Nanak Dev University  35.731109
33                                   AMITY University  35.751972
22                                  Kerala University  35.844920
25                             Pondicherry University  36.083603
48        Cochin University of Science and Technology  36.867175
30                    Dr. D. Y. Patil Vidyapeeth Pune  36.965908
19                                      Jamia Hamdard  37.040536
27                        Sri Venkateswara University  37.105554
45  Sri Balaji Vidyapeeth Mahatma Gandhi Medical C...  37.165286
44          Guru Gobind Singh Indraprastha University  37.486888
20                                 Gauhati University  37.661152
42                              University of Kashmir  37.815081
36  Saveetha Institute of Medical and Technical Sc...  37.902711
38                              Shiv Nadar University  38.141561
34                               Banasthali Vidyapith  38.521193
14                                      Visva Bharati  38.590813
40                                University of Jammu  38.868672
41                    Dayalbagh Educational Institute  39.146741
31                      North Eastern Hill University  39.193303
16   Bharath Institute of Higher Education & Research  39.412017
29     Sathyabama Institute of Science and Technology  39.509522
47                                 Periyar University  39.868772
39       KLE Academy of Higher Education and Research  40.247815
37                                 Calicut University  40.550095
46                                   NITTE University  40.733825

In [115]:
X

,infra_2017,placements_2017,academic_2017,Rank_2017,infra_2018,placements_2018,academic_2018,Rank_2018,infra,placements,academic,Rank,infra_2020,placements_2020,academic_2020,Rank_2020
0,100.00,1,82.16,1,100.00,1,82.28,1,100.00,1,84.18,1,100.00,1,82.67,1
1,46.28,3,67.57,2,55.27,3,68.68,2,67.24,3,70.16,2,67.88,2,67.99,2
2,43.62,4,63.52,3,47.28,5,64.55,3,53.99,6,63.15,3,58.57,5,64.02,3
3,35.50,6,59.68,6,51.83,4,60.53,6,71.44,2,61.99,5,67.31,3,60.33,8
4,63.22,2,62.82,4,62.72,2,60.35,7,65.89,4,58.71,12,67.20,4,54.97,16
5,21.66,19,60.54,5,36.71,8,61.85,4,58.32,5,61.70,6,52.49,7,59.71,9
6,33.15,8,58.69,7,41.11,6,57.59,13,53.44,7,60.10,11,55.37,6,57.09,12
7,31.44,9,58.46,8,31.01,12,59.22,8,44.33,13,62.27,4,48.36,10,61.23,5
8,15.04,26,58.24,9,16.55,28,58.40,10,44.99,11,61.13,9,41.49,20,58.34,11
9,26.30,11,57.78,10,18.46,27,58.36,11,38.99,23,54.30,17,42.90,17,58.97,10
10,11.76,33,56.18,12,14.26,37,58.07,12,31.60,41,61.07,10,32.17,45,60.74,6
11,36.71,5,52.68,16,35.31,9,51.44,19,49.00,8,55.22,16,51.16,8,56.63,13
12,26.30,11,53.38,14,37.39,7,60.87,5,47.99,9,61.53,7,45.77,14,62.06,4
13,26.30,11,57.37,11,30.21,14,58.50,9,43.95,15,61.51,8,40.93,21,60.58,7
14,5.03,67,47.62,31,11.52,44,46.27,37,19.30,121,46.84,50,16.35,165,42.76,64
15,9.85,42,48.98,26,4.33,87,51.95,17,33.54,34,56.04,14,34.35,39,53.24,18
16,2.40,100,50.74,21,3.19,103,46.32,36,21.87,89,45.67,59,21.90,97,46.44,51
17,5.76,59,48.02,28,9.26,50,49.86,26,39.00,20,51.15,29,39.67,24,49.16,32
18,15.90,25,51.39,19,20.28,21,52.62,15,44.07,14,54.10,18,45.43,15,56.10,15
19,2.01,115,50.31,23,6.86,64,51.73,18,23.16,83,52.60,21,23.67,88,48.02,41
20,6.11,57,45.44,39,9.59,49,45.57,42,22.20,87,47.10,47,25.34,79,47.35,45
21,22.63,17,55.08,13,31.20,11,57.23,14,37.18,26,58.30,13,35.22,37,56.44,14
22,7.17,51,47.72,30,8.59,51,51.21,22,21.54,92,52.35,23,21.44,102,50.52,27
23,10.82,37,48.00,29,15.71,31,48.47,29,34.88,30,48.77,40,32.14,47,47.27,46
24,23.58,16,50.94,20,27.09,16,51.25,21,42.39,16,51.85,26,50.12,9,51.59,23
25,14.76,28,42.36,59,19.25,25,44.88,48,28.88,58,45.82,58,30.52,57,44.36,58
26,26.52,10,51.52,18,30.01,15,51.34,20,38.30,24,52.55,22,38.17,26,50.46,28
27,2.01,115,43.44,49,6.51,66,44.88,49,37.00,27,48.84,38,33.90,40,45.61,54
28,9.53,43,50.39,22,14.55,34,52.11,16,39.82,19,53.82,19,42.86,18,51.10,24
29,4.30,71,44.34,45,2.41,123,45.58,41,19.47,114,48.77,39,23.23,92,48.17,40
30,1.22,134,43.15,52,7.56,59,45.11,46,33.54,34,47.92,46,40.41,22,46.74,49
31,5.03,67,42.34,61,6.51,66,45.99,39,23.48,81,46.88,49,26.14,72,44.24,59
32,3.55,82,44.81,42,14.55,34,47.97,31,31.30,45,52.33,24,31.74,50,52.06,21
33,5.40,64,42.99,53,7.22,61,43.53,58,30.10,54,49.02,37,32.53,44,50.90,25
34,4.30,71,41.88,64,4.33,87,43.22,61,20.18,105,46.32,55,37.34,29,48.57,35
35,14.76,28,41.71,66,13.66,39,42.89,62,39.00,20,44.84,63,37.74,27,42.10,68
36,3.17,88,44.00,46,0.00,222,45.42,43,19.11,122,48.56,42,19.52,123,50.36,29
37,5.76,59,40.06,73,7.22,61,42.22,64,21.21,95,46.37,54,20.01,115,44.13,60
38,0.00,203,43.68,48,6.15,70,44.45,52,21.54,92,46.11,56,27.30,67,45.00,56
39,2.79,96,42.76,57,4.33,87,40.92,69,28.20,60,43.10,70,31.74,50,39.44,91
40,1.22,134,43.19,51,2.02,135,40.43,74,31.47,42,46.55,52,32.01,48,42.52,66
41,12.38,30,41.95,63,11.83,43,40.24,77,30.70,48,41.21,82,28.35,65,39.06,94
42,0.00,203,43.96,47,1.63,148,44.19,53,25.82,68,46.99,48,25.52,76,46.97,48
43,7.17,51,42.36,60,5.80,73,43.69,55,35.48,29,46.58,51,42.52,19,45.67,53
44,2.40,100,40.05,74,3.58,98,41.21,66,4.53,229,40.24,95,14.81,171,40.79,79
45,0.00,203,40.25,72,0.00,222,40.87,72,18.74,129,40.92,88,20.01,115,40.42,80
46,8.53,46,39.70,77,6.51,66,40.88,70,22.85,85,42.19,74,24.51,85,41.04,77
47,4.30,71,38.58,90,19.25,25,40.99,68,28.09,61,41.09,83,19.52,123,41.38,74
48,18.88,20,40.53,69,14.84,32,41.42,65,29.39,56,45.02,62,28.41,64,47.37,44
49,26.30,11,41.63,67,24.17,18,43.41,60,40.09,18,46.41,53,37.19,32,44.63,57
50,24.50,15,48.25,27,26.65,17,48.54,28,44.76,12,49.22,36,46.34,13,49.09,33

In [116]:
import joblib

In [117]:
model=joblib.load(r"C:\Users\Narasimha Reddy\OneDrive\Desktop\sih\model\dcr.sav")

In [118]:
d_pred = df_data_check

In [119]:
d_pred.drop('infra_2017',inplace=True,axis=1)
d_pred.drop('infra_2018',inplace=True,axis=1)
d_pred.drop('infra_2020',inplace=True,axis=1)
d_pred.drop('infra_2021',inplace=True,axis=1)
d_pred.drop('infra',inplace=True,axis=1)
d_pred.drop('academic_2017',inplace=True,axis=1)
d_pred.drop('academic_2018',inplace=True,axis=1)
d_pred.drop('academic',inplace=True,axis=1)
d_pred.drop('academic_2020',inplace=True,axis=1)
d_pred.drop('academic_2021',inplace=True,axis=1)

In [120]:
d_pred

,Name,placements_2017,Year_2017,Rank_2017,placements_2018,Year_2018,Rank_2018,placements,Year,Rank,placements_2020,Year_2020,Rank_2020,placements_2021,Year_2021,Rank_2021
0,Indian Institute of Science Bangalore,1,2017,1,1,2018,1,1,2019,1,1,2020,1,1,2021,1
1,Jawaharlal Nehru University,3,2017,2,3,2018,2,3,2019,2,3,2020,2,2,2021,2
2,Banaras Hindu University,4,2017,3,4,2018,3,5,2019,3,6,2020,3,5,2021,3
3,Jadavpur University,9,2017,5,6,2018,6,4,2019,6,2,2020,5,3,2021,8
4,Anna University,5,2017,6,2,2018,4,2,2019,7,4,2020,12,4,2021,16
5,University of Hyderabad,11,2017,7,19,2018,5,8,2019,4,5,2020,6,7,2021,9
6,University of Delhi,7,2017,8,8,2018,7,6,2019,13,7,2020,11,6,2021,12
7,Amrita Vishwa Vidyapeetham,12,2017,9,9,2018,8,12,2019,8,13,2020,4,10,2021,5
8,Savitribai Phule Pune University,35,2017,10,26,2018,9,28,2019,10,11,2020,9,20,2021,11
9,Aligarh Muslim University,21,2017,11,11,2018,10,27,2019,11,23,2020,17,17,2021,10
10,Jamia Millia Islamia,42,2017,12,33,2018,12,37,2019,12,41,2020,10,45,2021,6
11,Vellore Institute of Technology,6,2017,14,5,2018,16,9,2019,19,8,2020,16,8,2021,13
12,Calcutta University,20,2017,16,11,2018,14,7,2019,5,9,2020,7,14,2021,4
13,Manipal Academy of Higher Education-Manipal,10,2017,18,11,2018,11,14,2019,9,15,2020,8,21,2021,7
14,Visva Bharati,69,2017,19,67,2018,31,44,2019,37,121,2020,50,165,2021,64
15,Homi Bhabha National Institute,47,2017,21,42,2018,26,87,2019,17,34,2020,14,39,2021,18
16,Bharath Institute of Higher Education & Research,84,2017,22,100,2018,21,103,2019,36,89,2020,59,97,2021,51
17,Osmania University,36,2017,23,59,2018,28,50,2019,26,20,2020,29,24,2021,32
18,Institute of Chemical Technology,16,2017,25,25,2018,19,21,2019,15,14,2020,18,15,2021,15
19,Jamia Hamdard,110,2017,26,115,2018,23,64,2019,18,83,2020,21,88,2021,41
20,Gauhati University,102,2017,27,57,2018,39,49,2019,42,87,2020,47,79,2021,45
21,Bharathiar University,45,2017,28,17,2018,13,11,2019,14,26,2020,13,37,2021,14
22,Kerala University,132,2017,29,51,2018,30,51,2019,22,92,2020,23,102,2021,27
23,Tezpur University,54,2017,30,37,2018,29,31,2019,29,30,2020,40,47,2021,46
24,Panjab University,18,2017,33,16,2018,20,16,2019,21,16,2020,26,9,2021,23
25,Pondicherry University,70,2017,37,28,2018,59,25,2019,48,58,2020,58,57,2021,58
26,University of Madras,40,2017,41,10,2018,18,15,2019,20,24,2020,22,26,2021,28
27,Sri Venkateswara University,108,2017,42,115,2018,49,66,2019,49,27,2020,38,40,2021,54
28,Andhra University,15,2017,43,43,2018,22,34,2019,16,19,2020,19,18,2021,24
29,Sathyabama Institute of Science and Technology,38,2017,44,71,2018,45,123,2019,41,114,2020,39,92,2021,40
30,Dr. D. Y. Patil Vidyapeeth Pune,33,2017,47,134,2018,52,59,2019,46,34,2020,46,22,2021,49
31,North Eastern Hill University,93,2017,48,67,2018,61,66,2019,39,81,2020,49,72,2021,59
32,Kalinga Institute of Industrial Technology,14,2017,49,82,2018,42,34,2019,31,45,2020,24,50,2021,21
33,AMITY University,19,2017,52,64,2018,53,61,2019,58,54,2020,37,44,2021,25
34,Banasthali Vidyapith,52,2017,53,71,2018,64,87,2019,61,105,2020,55,29,2021,35
35,Bharati Vidyapeeth,8,2017,54,28,2018,66,39,2019,62,20,2020,63,27,2021,68
36,Saveetha Institute of Medical and Technical Sc...,62,2017,55,88,2018,46,222,2019,43,122,2020,42,123,2021,29
37,Calicut University,68,2017,57,59,2018,73,61,2019,64,95,2020,54,115,2021,60
38,Shiv Nadar University,66,2017,60,203,2018,48,70,2019,52,92,2020,56,67,2021,56
39,KLE Academy of Higher Education and Research,141,2017,62,96,2018,57,87,2019,69,60,2020,70,50,2021,91
40,University of Jammu,157,2017,63,134,2018,51,135,2019,74,42,2020,52,48,2021,66
41,Dayalbagh Educational Institute,22,2017,72,30,2018,63,43,2019,77,48,2020,82,65,2021,94
42,University of Kashmir,184,2017,73,203,2018,47,148,2019,53,68,2020,48,76,2021,48
43,Guru Nanak Dev University,71,2017,80,51,2018,60,73,2019,55,29,2020,51,19,2021,53
44,Guru Gobind Singh Indraprastha University,90,2017,82,100,2018,74,98,2019,66,229,2020,95,171,2021,79
45,Sri Balaji Vidyapeeth Mahatma Gandhi Medical C...,74,2017,83,203,2018,72,222,2019,72,129,2020,88,115,2021,80
46,NITTE University,79,2017,84,46,2018,77,66,2019,70,85,2020,74,85,2021,77
47,Periyar University,61,2017,85,71,2018,90,25,2019,68,61,2020,83,123,2021,74
48,Cochin University of Science and Technology,109,2017,86,20,2018,69,32,2019,65,56,2020,62,64,2021,44
49,Bharathidasan University,48,2017,88,11,2018,67,18,2019,60,18,2020,53,32,2021,57
50,Alagappa University,77,2017,97,15,2018,27,17,2019,28,12,2020,36,13,2021,33

In [121]:
d_pred.columns

Index(['Name', 'placements_2017', 'Year_2017', 'Rank_2017', 'placements_2018',
       'Year_2018', 'Rank_2018', 'placements', 'Year', 'Rank',
       'placements_2020', 'Year_2020', 'Rank_2020', 'placements_2021',
       'Year_2021', 'Rank_2021'],
      dtype='object')

In [122]:
p=d_pred.head()
p

,Name,placements_2017,Year_2017,Rank_2017,placements_2018,Year_2018,Rank_2018,placements,Year,Rank,placements_2020,Year_2020,Rank_2020,placements_2021,Year_2021,Rank_2021
0,Indian Institute of Science Bangalore,1,2017,1,1,2018,1,1,2019,1,1,2020,1,1,2021,1
1,Jawaharlal Nehru University,3,2017,2,3,2018,2,3,2019,2,3,2020,2,2,2021,2
2,Banaras Hindu University,4,2017,3,4,2018,3,5,2019,3,6,2020,3,5,2021,3
3,Jadavpur University,9,2017,5,6,2018,6,4,2019,6,2,2020,5,3,2021,8
4,Anna University,5,2017,6,2,2018,4,2,2019,7,4,2020,12,4,2021,16

In [123]:
dd_check_yk1 = pd.DataFrame((zip(l_check,yk_ck)),
              columns=['Name','placements'])

In [124]:
dd_check_yk1

                                                 Name  placements
0               Indian Institute of Science Bangalore   30.421389
1                         Jawaharlal Nehru University   24.763998
2                            Banaras Hindu University   23.907805
3                                 Jadavpur University   24.534035
4                                     Anna University   25.409771
5                             University of Hyderabad   23.942536
6                                 University of Delhi   23.908757
7                          Amrita Vishwa Vidyapeetham   23.548702
8                    Savitribai Phule Pune University   24.818444
9                           Aligarh Muslim University   24.570738
10                               Jamia Millia Islamia   27.189459
11                    Vellore Institute of Technology   24.310725
12                                Calcutta University   23.745547
13        Manipal Academy of Higher Education-Manipal   23.973064
14                                      Visva Bharati   38.590813
15                     Homi Bhabha National Institute   30.864687
16   Bharath Institute of Higher Education & Research   39.412017
17                                 Osmania University   30.420775
18                   Institute of Chemical Technology   25.175445
19                                      Jamia Hamdard   37.040536
20                                 Gauhati University   37.661152
21                              Bharathiar University   25.308117
22                                  Kerala University   35.844920
23                                  Tezpur University   31.451875
24                                  Panjab University   25.424033
25                             Pondicherry University   36.083603
26                               University of Madras   25.940227
27                        Sri Venkateswara University   37.105554
28                                  Andhra University   27.138065
29     Sathyabama Institute of Science and Technology   39.509522
30                    Dr. D. Y. Patil Vidyapeeth Pune   36.965908
31                      North Eastern Hill University   39.193303
32         Kalinga Institute of Industrial Technology   33.173773
33                                   AMITY University   35.751972
34                               Banasthali Vidyapith   38.521193
35                                 Bharati Vidyapeeth   35.691666
36  Saveetha Institute of Medical and Technical Sc...   37.902711
37                                 Calicut University   40.550095
38                              Shiv Nadar University   38.141561
39       KLE Academy of Higher Education and Research   40.247815
40                                University of Jammu   38.868672
41                    Dayalbagh Educational Institute   39.146741
42                              University of Kashmir   37.815081
43                          Guru Nanak Dev University   35.731109
44          Guru Gobind Singh Indraprastha University   37.486888
45  Sri Balaji Vidyapeeth Mahatma Gandhi Medical C...   37.165286
46                                   NITTE University   40.733825
47                                 Periyar University   39.868772
48        Cochin University of Science and Technology   36.867175
49                           Bharathidasan University   33.662870
50                                Alagappa University   27.051087

In [125]:
k=dd_check_yk1.sort_values(by=['placements'])

In [126]:
k

                                                 Name  placements
7                          Amrita Vishwa Vidyapeetham   23.548702
12                                Calcutta University   23.745547
2                            Banaras Hindu University   23.907805
6                                 University of Delhi   23.908757
5                             University of Hyderabad   23.942536
13        Manipal Academy of Higher Education-Manipal   23.973064
11                    Vellore Institute of Technology   24.310725
3                                 Jadavpur University   24.534035
9                           Aligarh Muslim University   24.570738
1                         Jawaharlal Nehru University   24.763998
8                    Savitribai Phule Pune University   24.818444
18                   Institute of Chemical Technology   25.175445
21                              Bharathiar University   25.308117
4                                     Anna University   25.409771
24                                  Panjab University   25.424033
26                               University of Madras   25.940227
50                                Alagappa University   27.051087
28                                  Andhra University   27.138065
10                               Jamia Millia Islamia   27.189459
17                                 Osmania University   30.420775
0               Indian Institute of Science Bangalore   30.421389
15                     Homi Bhabha National Institute   30.864687
23                                  Tezpur University   31.451875
32         Kalinga Institute of Industrial Technology   33.173773
49                           Bharathidasan University   33.662870
35                                 Bharati Vidyapeeth   35.691666
43                          Guru Nanak Dev University   35.731109
33                                   AMITY University   35.751972
22                                  Kerala University   35.844920
25                             Pondicherry University   36.083603
48        Cochin University of Science and Technology   36.867175
30                    Dr. D. Y. Patil Vidyapeeth Pune   36.965908
19                                      Jamia Hamdard   37.040536
27                        Sri Venkateswara University   37.105554
45  Sri Balaji Vidyapeeth Mahatma Gandhi Medical C...   37.165286
44          Guru Gobind Singh Indraprastha University   37.486888
20                                 Gauhati University   37.661152
42                              University of Kashmir   37.815081
36  Saveetha Institute of Medical and Technical Sc...   37.902711
38                              Shiv Nadar University   38.141561
34                               Banasthali Vidyapith   38.521193
14                                      Visva Bharati   38.590813
40                                University of Jammu   38.868672
41                    Dayalbagh Educational Institute   39.146741
31                      North Eastern Hill University   39.193303
16   Bharath Institute of Higher Education & Research   39.412017
29     Sathyabama Institute of Science and Technology   39.509522
47                                 Periyar University   39.868772
39       KLE Academy of Higher Education and Research   40.247815
37                                 Calicut University   40.550095
46                                   NITTE University   40.733825

In [127]:

p=k.reset_index()
p

    index                                               Name  placements
0       7                         Amrita Vishwa Vidyapeetham   23.548702
1      12                                Calcutta University   23.745547
2       2                           Banaras Hindu University   23.907805
3       6                                University of Delhi   23.908757
4       5                            University of Hyderabad   23.942536
5      13        Manipal Academy of Higher Education-Manipal   23.973064
6      11                    Vellore Institute of Technology   24.310725
7       3                                Jadavpur University   24.534035
8       9                          Aligarh Muslim University   24.570738
9       1                        Jawaharlal Nehru University   24.763998
10      8                   Savitribai Phule Pune University   24.818444
11     18                   Institute of Chemical Technology   25.175445
12     21                              Bharathiar University   25.308117
13      4                                    Anna University   25.409771
14     24                                  Panjab University   25.424033
15     26                               University of Madras   25.940227
16     50                                Alagappa University   27.051087
17     28                                  Andhra University   27.138065
18     10                               Jamia Millia Islamia   27.189459
19     17                                 Osmania University   30.420775
20      0              Indian Institute of Science Bangalore   30.421389
21     15                     Homi Bhabha National Institute   30.864687
22     23                                  Tezpur University   31.451875
23     32         Kalinga Institute of Industrial Technology   33.173773
24     49                           Bharathidasan University   33.662870
25     35                                 Bharati Vidyapeeth   35.691666
26     43                          Guru Nanak Dev University   35.731109
27     33                                   AMITY University   35.751972
28     22                                  Kerala University   35.844920
29     25                             Pondicherry University   36.083603
30     48        Cochin University of Science and Technology   36.867175
31     30                    Dr. D. Y. Patil Vidyapeeth Pune   36.965908
32     19                                      Jamia Hamdard   37.040536
33     27                        Sri Venkateswara University   37.105554
34     45  Sri Balaji Vidyapeeth Mahatma Gandhi Medical C...   37.165286
35     44          Guru Gobind Singh Indraprastha University   37.486888
36     20                                 Gauhati University   37.661152
37     42                              University of Kashmir   37.815081
38     36  Saveetha Institute of Medical and Technical Sc...   37.902711
39     38                              Shiv Nadar University   38.141561
40     34                               Banasthali Vidyapith   38.521193
41     14                                      Visva Bharati   38.590813
42     40                                University of Jammu   38.868672
43     41                    Dayalbagh Educational Institute   39.146741
44     31                      North Eastern Hill University   39.193303
45     16   Bharath Institute of Higher Education & Research   39.412017
46     29     Sathyabama Institute of Science and Technology   39.509522
47     47                                 Periyar University   39.868772
48     39       KLE Academy of Higher Education and Research   40.247815
49     37                                 Calicut University   40.550095
50     46                                   NITTE University   40.733825

In [128]:
q=p.loc[:,"Name"]
q

0                            Amrita Vishwa Vidyapeetham
1                                   Calcutta University
2                              Banaras Hindu University
3                                   University of Delhi
4                               University of Hyderabad
5           Manipal Academy of Higher Education-Manipal
6                       Vellore Institute of Technology
7                                   Jadavpur University
8                             Aligarh Muslim University
9                           Jawaharlal Nehru University
10                     Savitribai Phule Pune University
11                     Institute of Chemical Technology
12                                Bharathiar University
13                                      Anna University
14                                    Panjab University
15                                 University of Madras
16                                  Alagappa University
17                                    Andhra University
18                                 Jamia Millia Islamia
19                                   Osmania University
20                Indian Institute of Science Bangalore
21                       Homi Bhabha National Institute
22                                    Tezpur University
23           Kalinga Institute of Industrial Technology
24                             Bharathidasan University
25                                   Bharati Vidyapeeth
26                            Guru Nanak Dev University
27                                     AMITY University
28                                    Kerala University
29                               Pondicherry University
30          Cochin University of Science and Technology
31                      Dr. D. Y. Patil Vidyapeeth Pune
32                                        Jamia Hamdard
33                          Sri Venkateswara University
34    Sri Balaji Vidyapeeth Mahatma Gandhi Medical C...
35            Guru Gobind Singh Indraprastha University
36                                   Gauhati University
37                                University of Kashmir
38    Saveetha Institute of Medical and Technical Sc...
39                                Shiv Nadar University
40                                 Banasthali Vidyapith
41                                        Visva Bharati
42                                  University of Jammu
43                      Dayalbagh Educational Institute
44                        North Eastern Hill University
45     Bharath Institute of Higher Education & Research
46       Sathyabama Institute of Science and Technology
47                                   Periyar University
48         KLE Academy of Higher Education and Research
49                                   Calicut University
50                                     NITTE University
Name: Name, dtype: object

In [129]:
list=[]
for i in range(5,11):
    list.append(q[i])

In [130]:
list

['Manipal Academy of Higher Education-Manipal',
 'Vellore Institute of Technology',
 'Jadavpur University',
 'Aligarh Muslim University',
 'Jawaharlal Nehru University',
 'Savitribai Phule Pune University']

In [131]:
import webbrowser
import time
html=f" <html> <head><body><table><tr><td>{list[0]}</td></tr><tr><td>{list[1]}</td></tr><tr><td>{list[2]}</td></tr><tr><td>{list[3]}</td></tr><tr><td>{list[4]}</td></tr></table></body></head></html>"
with open("techctryplace1.html","w") as html_file:
    html_file.write(html)
    print("   ")